### ISSUE TITLE
Add support for reading SVG images

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/bubblewrap#103]
`jimp`, which is used to read the images doesn't support SVGs. Implement a solution that accepts SVGs and outputs PNGs.

Alternatives:
 - ~~Migrate to Sharp (https://www.npmjs.com/package/sharp), as it has SVG support. It does depend on native libraries though. We did move from Sharp to jimp in the past #16  to avoid native dependencies (also, takes longer to install the package). https://www.npmjs.com/package/@types/sharp can be used for Typescript types.~~
 - Use https://www.npmjs.com/package/svg2img for SVGs only. Depends on `canvas`, which also has native library dependencies.

**Comment by chenlevy24** [comment]
Fixed the issue

**Comment by chenlevy24** [comment]
https://github.com/chenlevy24/bubblewrap/pull/new/SvgIcons

**Comment by andreban** [comment]
#193 adds SVG Icon support

**Comment by andreban** [comment]
Closed via #193

**Comment by andreban** [comment]
Re-opening this since we're reverting the move to sharp (See #259). We'll investigate SVG alternatives (#260).

**Comment by chenlevy24** [comment]
closed by https://github.com/GoogleChromeLabs/bubblewrap/pull/341
