### ISSUE TITLE
Run quality criteria checks before building the Android APK

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/bubblewrap#104]
- Run Lighthouse to collect information on the quality criteria
- Report the quality criteria information to the user
- If the PWA fails the quality criteria, fail the build step

More information on the Quality criteria [here](https://blog.chromium.org/2019/02/introducing-trusted-web-activity-for.html). Relevant bit:

> App users expect a great experience on their device. To ensure the quality of experience TWAs must meet PWA installability criteria and load fast. Loading speed is measured using Lighthouse and web content in TWAs must achieve a performance score of 80.

**Comment by FluorescentHallucinogen** [comment]
> If the PWA fails the quality criteria, fail the build step

Looks like not a good idea. IMO, warning is fine.

**Comment by FluorescentHallucinogen** [comment]
Or it should be configurable.

**Comment by andreban** [comment]
Thanks for the feedback. I'd be interested in hearing more on why it's not
a good idea, so we can address concerns in the solution.  Could you
elaborate?

Andre

**Comment by FluorescentHallucinogen** [comment]
What if the user knows that PWA fails the quality criteria, but still need to pack it in TWA (e.g. for tests).

I believe tools should just do their job, not create problems for users.

**Comment by andreban** [comment]
> I believe tools should just do their job, not create problems for users.
The quality criteria is a requirement when creating a Trusted Web Activity, so the tool is not creating a problem, but ensuring developers detect it earlier. The quality criteria is not currently being enforced elsewhere, but we expect this to change.

I agree we should provide a way for developers to test their application. We can add a flag to skip the checks when building the application.

**Comment by FluorescentHallucinogen** [comment]
+1 for adding a flag to skip the checks.

**Comment by andreban** [comment]
This was closed via #134

**Comment by nR-paK** [comment]
The PageSpeed Insights API has become overloaded (rate limited) and therefore it is now impossible to pass the check and use the bubblewrap build function.
Sorry in advance if I am placing this concern in the wrong location.
