### ISSUE TITLE
Please add support for TWA WebView Fallback

### ISSUE THREAD

**Issue by naveedahmed1** [GoogleChromeLabs/bubblewrap#105]
When a user starts a Trusted Web Activity (TWA) based application, a browser that supports TWAs may not be available on the device. In those situations, the default implementation will fallback to opening the URL in a Custom Tab or the default browser, if a browser that supports Custom Tabs is not found. This approach may be undesirable as it breaks the full-screen experience for users.

I would therefore suggest you to please add an option to the CLI that allow user to enable `WebView Fallback` with a single switch.

This could be based on 
https://github.com/GoogleChrome/android-browser-helper/tree/5a0accde2341108fcc7eb7d0b0e0d7ce45a29962/demos/twa-webview-fallback

**Comment by andreban** [comment]
Thanks @naveedahmed1 

The goal is to add the WebView fallback directly to android-browser-helper. The issue we're tracking this is here: https://github.com/GoogleChrome/android-browser-helper/issues/15, and the demo is the first step in that direction. We will start working on that soon. 

Once that is done, llama-pack will automatically get it.

**Comment by naveedahmed1** [comment]
That's great, thanks for the update @andreban :)

**Comment by andreban** [comment]
#105 adds this

1. Update `twa-manifest.json` and include / update the `fallbackStrategy` field to `webview`. 
2. Run `npx @bubblewrap/cli update` to apply the changes to the template
3.  Run `npx @bubblewrap/cli build` to generate the APK.

We still default to `customtab`, as it provides better compatibility for Web APIs. We strongly recommend  to comprehensively test the PWA inside the WebView when using it.

**Comment by naveedahmed1** [comment]
`bubblewrap` is the new name for `@llama-pack cli` right?

**Comment by naveedahmed1** [comment]
Can you please also add the basic instruction about this library to project read me file https://github.com/GoogleChromeLabs/bubblewrap/blob/master/README.md covering at least these two topics:

- Creating new project
- Updating existing project
- Different available settings

**Comment by andreban** [comment]
Work on more comprehensive docs will start soon.

**Comment by naveedahmed1** [comment]
Should a new project generated through `@bubblewrap/cli` already have the option `fallbackStrategy`?

I just installed `@bubblewrap/cli` and generated a new app, but `twa-manifest` doesn't contain `fallbackStrategy`.

**Comment by andreban** [comment]
We havent' published a version with the feature yet. Will publish it this week.
