### ISSUE TITLE
Please add support for Firebase tools 

### ISSUE THREAD

**Issue by naveedahmed1** [GoogleChromeLabs/bubblewrap#106]
It would be really nice if either below Firebase tools cloud be added to the CLI

Crashlytics
Performance
Analytics

or a documentation is provided that guides how to integrate these tools to TWA.

**Comment by andreban** [comment]
We'd probably want to support other non-Firebase tools, like [AppsFlyer](https://support.appsflyer.com/hc/en-us/articles/360002330178-Using-AppsFlyer-with-TWA#introduction)

**Comment by naveedahmed1** [comment]
Nice, but is there any specific reason for adding support of third party tool and not Google's own Firebase?

**Comment by andreban** [comment]
Some developers already use other tools in their apps. Making the solution work across apps allows developers to use their preferred tool

**Comment by naveedahmed1** [comment]
In case of AppsFlyer, we first need to send the event data to our server and then our server sends the event to AppsFlyer. This approach doesn't seems elegant.

**Comment by andreban** [comment]
Update: [`android-browser-helper]`](https://github.com/GoogleChrome/android-browser-helper) v2.2.0 enables calling code that runs asynchronously when starting the LauncherActivity and waiting for it to finish before launching the Trusted Web Activity. This was a blocker for Firebase running. There's a firebase analytics demo [here](https://github.com/GoogleChrome/android-browser-helper/tree/master/demos/twa-firebase-analytics).

**Comment by naveedahmed1** [comment]
That's awesome! Thank you so much @andreban :)

**Comment by naveedahmed1** [comment]
@andreban just a quick feedback, it would be great if you could please also add some brief docs/readme in each demo 
https://github.com/GoogleChrome/android-browser-helper/tree/master/demos so that people who're not much familiar with Android app development know what are the exact changes they need to make to their project to enable certain feature.

**Comment by andreban** [comment]
Updates on this: We won't add support for Firebase tools directly into Bubblewrap, as the output application wouldn't be compatible with Trusted Web Activity on Chrome OS.

**Comment by maddumarala** [comment]
> Update: [`android-browser-helper]`](https://github.com/GoogleChrome/android-browser-helper) v2.2.0 enables calling code that runs asynchronously when starting the LauncherActivity and waiting for it to finish before launching the Trusted Web Activity. This was a blocker for Firebase running. There's a firebase analytics demo [here](https://github.com/GoogleChrome/android-browser-helper/tree/master/demos/twa-firebase-analytics).

Did you found a bug relate to this ? Which hangs up in splash screen in the first load ?
