### ISSUE TITLE
Create documentation on how to update JDK and Android SDK configurations

### ISSUE THREAD

**Issue by nimit95** [GoogleChromeLabs/bubblewrap#132]
I in the initial setup didn't give the correct JDK path, I tried setting the correct path in env with JAVA_HOME and in twa manifest via jdkPath. Both of the first guesses failed. 

I had to dig in source code, I found ``gradlew`` ask to set the path in JAVA_HOME while the CLI updates the env JAVA_HOME from the llama config. So any env path setting is futile.

This can be included in README or can change the default behavior.

**Comment by andreban** [comment]
Overriding `JAVA_HOME` is the right behaviour. The Android SDK tools only runs in some specific versions of the JDK. If we used the JDK set in `JAVA_HOME`, it's likely users would have an incompatible JDK setup or they'd have to change their default SDK.

It seems to me that the right thing to do here is improve documentation, so its easier to change the Bubblewrap configuration.

#4 aims to improve this by making Bubblewrap setup its own dependencies

**Comment by nimit95** [comment]
Also if someone has given twa-manifest and llama manifets is also present, which config should take precedence?

**Comment by andreban** [comment]
twa-manifest is the configuration for generating the application and doesn't have fields for JDK configuration. The CLI configuration is in the llama configuration file.

**Comment by nimit95** [comment]
Oh okay, but that can have the field too right?

**Comment by andreban** [comment]
I don't think the extra field would break anything, but it won't be used.

**Comment by Stevie-Ray** [comment]
Had the same issue, config is located in: `${USER_HOME}/.llama-pack/llama-pack-config.json`

**Comment by andreban** [comment]
Created #133 . Let me know if that information is enough.

**Comment by titocosta** [comment]
> Had the same issue. If somebody has to reconfigure there PATHS the file is located at: `${USER_HOME}/.llama-pack/llama-pack-config.json`

Correct path is now `${USER_HOME}/.bubblewrap/llama-pack-config.json`

**Comment by andreban** [comment]
Docs are up to date: https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli#updating-the-location-of-the-jdk-and--or-the-android-command-line-tools
