### ISSUE TITLE
intent:// URL not working inside a Trusted Web Activity

### ISSUE THREAD

**Issue by tsukasagenesis** [GoogleChromeLabs/bubblewrap#136]
Hello,

**Describe the bug**
Intent are not working inside TWA from a fresh android install. Get the error : 
Navigation is blocked: intent://mirrorblender.top-ix.org/peach/bigbuckbunny_movies/big_buck_bunny_1080p_surround.avi#Intent;scheme=http;action=android.intent.action.VIEW;type=video/avi;end

**To Reproduce**
1. go to https://codepen.io/tsukasagenesis/pen/mdeJxvM from a TWA with Devtools
2. click on link

**The code to Reproduce**
`<a href="intent://media.xiph.org/mango/tears_of_steel_1080p.webm#Intent;scheme=http;action=android.intent.action.VIEW;type=video/avi;end">Intent test link</a>`

**Expected behavior**
Should open your video player, but instead display:
Navigation is blocked: intent://mirrorblender.top-ix.org/peach/bigbuckbunny_movies/big_buck_bunny_1080p_surround.avi#Intent;scheme=http;action=android.intent.action.VIEW;type=video/avi;end

![13-04-2020-11-42-58](https://user-images.githubusercontent.com/374009/79110994-ee426700-7d7b-11ea-9f91-bbfee596bb13.png)

The weird thing is this is working if you try directly from chrome. Do the same procedure and it will work. Just blocked from TWA.

**Smartphone (please complete the following information):**
 - Device: p20 mate pro
 - OS: android 10
 - Browser chrome
 - Version 81.0.4044.96

If you have any idea, I would gladly take it.

Best regards.

**Comment by andreban** [comment]
I created the following page and added that link: https://gigantic-xylocarp.glitch.me/ and setup a Trusted Web Activity that opens and correctly validates against it. The link seems to work as expected 

From your description, it looked like you were opening a different Trusted Web Activity and using Chrome DevTools to inject a link to codepen and then seeing the error. Is that correct?

**Comment by tsukasagenesis** [comment]
Hello,

I just try and do not work, look my screen.

I open my PWA and then changed the link, to have something clean, but it doesn't work neither directly in my pwa, whatever I visit by devtools or directly, it fail with this error.


![14-04-2020-04-54-40](https://user-images.githubusercontent.com/374009/79239244-a2251e80-7e70-11ea-8ef1-360ef62dd28f.png)

just to be sure, I rebuild with :

```java
def twaManifest = [
    applicationId: 'com.test',
    hostName: 'gigantic-xylocarp.glitch.me', // The domain being opened in the TWA.
    launchUrl: '/index.html', // The start path for the TWA. Must be relative to the domain.
    name: 'test', // The application name.
    launcherName: 'test', // The name shown on the Android Launcher.
    themeColor: '#FFC107', // The color used for the status bar.
    navigationColor: '#000000', // The color used for the navigation bar.
    backgroundColor: '#FFC107', // The color used for the splash screen background.
    enableNotifications: false, // Set to true to enable notification delegation.
    // Every shortcut must include the following fields:
    // - name: String that will show up in the shortcut.
    // - short_name: Shorter string used if |name| is too long.
    // - url: Absolute path of the URL to launch the app with (e.g '/create').
    // - icon: Name of the resource in the drawable folder to use as an icon.
    shortcuts: [],
    // The duration of fade out animation in milliseconds to be played when removing splash screen.
    splashScreenFadeOutDuration: 300,
    generatorApp: 'bubblewrap-cli', // Application that generated the Android Project
    // The fallback strategy for when Trusted Web Activity is not avilable. Possible values are
    // 'customtabs' and 'webview'.
    fallbackType: 'customtabs'
]
```
and get same error.

I can reproduce this beaviour, i'm looking to try to understand why, and how you can reproduce it.

**Comment by andreban** [comment]
When intenting to the app itself, a custom schema is preferable over `intent://`. See this StackOverflow issue for more: https://stackoverflow.com/questions/65752429/how-can-i-extend-twa-application-with-in-app-review/65779823#65779823

**Comment by tsukasagenesis** [comment]
Well sadly it doesn't solve anything because I wish to open VLC (video player), and not my app. That's why I need intent and their is no other way.

BTW the bug is rotting there https://bugs.chromium.org/p/chromium/issues/detail?id=1088090 and it's still a current issue.
