### ISSUE TITLE
path for android SDK

### ISSUE THREAD

**Issue by 2803media** [GoogleChromeLabs/bubblewrap#140]
Hi with the new version of android studio 3.6.3 (on a mac) the path for built in SDK package doesn't include the folder "tools" :

`/Users/john/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager `

Is there a way to update the AndroidSdkTools.ts file in order to reflect this change:

```
/**
   * Installs the build tools into the the Android SDK. Equivalent to running
   *
   * `tools/bin/sdkmanager --install "build-tools;29.0.2"`
   */
  async installBuildTools(): Promise<void> {
    const env = this.getEnv();

    console.log('Installing Build Tools');
    await util.execInteractive(
        /*this.pathJoin(this.getAndroidHome(), '/tools/bin/sdkmanager'),*/
        this.pathJoin(this.getAndroidHome(), '/bin/sdkmanager'),
        ['--install',
          `"build-tools;${BUILD_TOOLS_VERSION}"`],
        env,
    );
  }
```

It may be easier if the user already have Android Studio with SDK on his machine

Thanks for your help

**Comment by 2803media** [comment]
The trick to make it works is to use the old version of the SDK like describe in this page : https://flutter.dev/docs/get-started/install/macos#install-android-studio

**Comment by andreban** [comment]
You should also be able to download the command-line tools only, unzip into a different folder and use that one: https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli#get-the-android-command-line-tools
