### ISSUE TITLE
App names that end in a period produce invalid Android package name

### ISSUE THREAD

**Issue by JudahGabriel** [GoogleChromeLabs/bubblewrap#141]
A user [reported](https://github.com/pwa-builder/PWABuilder/issues/693) that running their app through PWABuilder (and bubblewrap) resulted in an invalid package name.

In fact, their manifest's app name was "represent." (with the period). This resulted in a default package name of `com.represent..twa`, which is apparently an invalid Android package name due to the double period.

We're accounting for this now in PWABuilder, but I thought you should know and perhaps should be accounted for in bubblewrap's package name generation code.

**Comment by andreban** [comment]
We recently improved validation on the CLI (https://github.com/GoogleChromeLabs/bubblewrap/blob/master/packages/core/src/lib/util.ts#L139-L167). Generation hasn't been updated though.

**Comment by andreban** [comment]
Oh, interesting - the CLI uses the domain name (`url.host`) to generate the package name, as described in the [Java package naming conventions][1], which the Android Package Name derives from and adds further restrictions. So, it wasn't expecting names ending with a `.`. Shouldn't be hard to fix though.

[1]: https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by andreban** [comment]
@JudahGabriel depending on the input, it may be impossible to generate a valid packageId. Examples:

- `..` would generate an empty id.
- `1example.com` - would output `com.1example.twa`, which is invalid (one section starts with a number).

On the Bubblewrap CLI implementation, we can simply skip generating the ID and ask the user to input one themselves. So, we could change `generatePackageId()` to return null in those cases, but wondering how that would affect CloudAPK.

I'm also considering calling `validatePackageId()` inside `TwaGenerator` when building the application, as we can display a better message at this point than the Android build error.

Let me know what you think.

Andre

**Comment by andreban** [comment]
#142 implements those changes
