### ISSUE TITLE
This app is incompatible with your device

### ISSUE THREAD

**Issue by MrPowerScripts** [GoogleChromeLabs/bubblewrap#146]
**Describe the bug**
When looking at my play store page it says the app is incompatible with my device. It's a Samsung Galaxy S8, which I feel should work. Model is samsung SM-G950F

**To Reproduce**
1. Follow the steps on the readme. deploy apk to app store. look at app store page

**Expected behavior**
The app to be available for my device

**Screenshots**
<img width="313" alt="image" src="https://user-images.githubusercontent.com/1307942/80743136-5d59e280-8b14-11ea-9898-3830d7352e93.png">
<img width="589" alt="image" src="https://user-images.githubusercontent.com/1307942/80743615-26d09780-8b15-11ea-9a0b-7d758874e1fc.png">

**Desktop (please complete the following information):**
all of them

**Smartphone (please complete the following information):**
Samsum Galazy S8, Android Version 9, Kernel 4.4.111

**Additional context**
I love this project so much <3

**Comment by andreban** [comment]
Would you have a link to the application on the Play Store?

**Comment by MrPowerScripts** [comment]
Actually it says I can install it now... I had contacted Google support earlier about the app not showing up in the play store and it seems to be searchable now as well. Maybe they flipped a switch? I don't think it's an issue with the project now. Sorry!!
