### ISSUE TITLE
bubblewrap init command - ERROR Cannot read property 'readFile' of undefined

### ISSUE THREAD

**Issue by JotinhaBR** [GoogleChromeLabs/bubblewrap#151]
**Describe the bug**
ERROR Cannot read property 'readFile' of undefined

**Screenshots**
![image](https://user-images.githubusercontent.com/6248317/80908302-22fb6b80-8cf5-11ea-90b6-e3974d350aa2.png)

**Desktop**
 - OS: Windows 10
 - Browser chrome

**Comment by andreban** [comment]
Can you check what happens if you run with npx?
```
npx @bubblewrap/cli init --manifest=https://stopstop.planetsweb.com.br/jogar/manifest.json
```

Which NodeJs version are you using?

Obrigado,
Andre

**Comment by JotinhaBR** [comment]
Acredito que você é Brasileiro, bom obrigado, estou me sentindo sentindo estupido na cabeça toda e não percebido que um pacote de vocês requer que tenha o NodeJS 10, atualize o pacote e funcionou!

Obrigado :)

EN:
Good thanks, i'm feeling stupid in the head and don't realize that a package of yours requires that you have NodeJS 10, update the package and it worked!

Thank you :)

**Comment by andreban** [comment]
Correto 😄 . 

I have filed #152 so we display a better error message when an unsupported NodeJs version is being used.
