### ISSUE TITLE
bubblewrap build - path not found, even though it exists

### ISSUE THREAD

**Issue by JotinhaBR** [GoogleChromeLabs/bubblewrap#153]
**Describe the bug**
I'm trying to build it, but he says he's not finding his way, but he doesn't talk about what is the Android SDK or the JDK.
And the two paths are right in the settings I tested typing in the CMD the paths exist, I downloaded the files recommended by your README doc.

**Screenshots**
![image](https://user-images.githubusercontent.com/6248317/80912434-3c131500-8d13-11ea-8b9e-815b097171df.png)

![image](https://user-images.githubusercontent.com/6248317/80912454-5816b680-8d13-11ea-901d-9b30c65bc684.png)

![image](https://user-images.githubusercontent.com/6248317/80912539-f86cdb00-8d13-11ea-8fd6-ebca815ebe28.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

can someone help me?

**Comment by andreban** [comment]
This looks like another instance of #147. Can you confirm? I've been trying to repro that, but without success. On your case, I wonder if the space in `Progream Files` is the culprit.

**Comment by JotinhaBR** [comment]
@andreban 

It can't be space as it copies these folders to the root of disk C but he still says he didn't find it even without having to go through the program folder.

**Comment by JotinhaBR** [comment]
problem solved for me, conclusion is at: #147
