### ISSUE TITLE
Add an option to generate the keystore

### ISSUE THREAD

**Issue by JotinhaBR** [GoogleChromeLabs/bubblewrap#154]
Hello,

Well, I believe that a good feature would be to have a keystore generator already in the CLI application, because I'm having the most trouble to be able to generate a keystore the right way without using Android Studio.

**Comment by andreban** [comment]
The `init` command does ask if the developers want it to generate the keystore when creating the project. Would the request be to have a separate command to generate it? (eg: `bubblewrap generate-keystore`)

**Comment by JotinhaBR** [comment]
@andreban 
I didn't know that this had already built into "init", well it was killing me trying to do it in other programs, but I believe that it would be good to have this option separate as it would be useful to use in other projects or to execute this command before even giving init.

Well, even so, I have already asked another question even though I generated my key through the init as recommended, I still get an error on the Google Play Console, follow this print:

![image](https://user-images.githubusercontent.com/6248317/80915994-370e8f80-8d2c-11ea-8669-c04729f57f50.png)

**Comment by andreban** [comment]
Can you check the name of the file being uploaded to the Play Store? It should be called ` app-release-signed.apk`.

FWIW, there's a bug in the current version of the Android SDK that is not generating the signed file (or displaying an error message): https://issuetracker.google.com/issues/150888434

**Comment by JotinhaBR** [comment]
the .apk file it generates for me is named `app-release-unsigned-aligned.apk`

follow my log of my init:
`
? Domain being opened in the TWA: stopstop.planetsweb.com.br
? Name of the application: StopStop - Stop, Adedonha, Adedanha
? Name to be shown on the Android Launcher: StopStop
? Color to be used for the status bar: #F86D6D
? Color to be used for the splash screen background: #F86D6D
? Relative path to open the TWA: /jogar
? URL to an image that is at least 512x512px: http://stopstop.planetsweb.com.br/artes/identidade-visual/APP-Icon.png
? URL to an image that is at least 512x512px to be used when generating maskable icons http://stopstop.planetsweb.com.br/artes/identidade-visual/APP-Icon.png
? Include app shortcuts?
[] Yes
? Android Package Name (or Application ID): com.wStopStop_10041742
? Location of the Signing Key: ./android.keystore
? Key name: android
Saving Config to: ./twa-manifest.jso
`

**Comment by andreban** [comment]
`app-release-unsigned-aligned.apk` is an intermediate file used to generate `app-release-signed.apk`. The issue in the Android SDK prevents it from being generated. I don't think there's a fix for it right now, and there's not much I can do on the Bubblewrap side.

The solution seems to be download an use an older version of the SDK Tools. https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip should work.

**Comment by JotinhaBR** [comment]
it worked, I recommend that you even put this link in the README for download or recommend the best version to be downloaded.

Thank you :)

**Comment by andreban** [comment]
Glad to know it worked. Tracking updating the docs on #155
