### ISSUE TITLE
Update quick documentation for android CLI tools

### ISSUE THREAD

**Issue by amanintech** [GoogleChromeLabs/bubblewrap#155]
Guide to suggest adding android-CLI tools to the tools folder

Which occurred in issue #147 

Fix
add a step by step more explained procedures to a quick start guide

**Comment by amanintech** [comment]
I can do this

**Comment by andreban** [comment]
@amanintech, I just found another issue with the current version of the Android SDK Tools:

This [issue](https://issuetracker.google.com/issues/150888434) is preventing it to output a signed APK to be uploaded to the Play Store.

I don't think there's a fix for it right now, and there's not much I can do on the Bubblewrap side. The workaround seems to be download an use an older version of the SDK Tools.
 
https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip do it.

This seems to be an issue on Windows only and seems to work fine on Linux and MacOS

**Comment by amanintech** [comment]
Also tried installing the apk it failed 
@andreban  do you think these issues are connected somehow

**Comment by andreban** [comment]
Yes. The APK needs to signed for it to be installed on the device. `app-release-unsigned-aligned.apk` is not signed and can't be uploaded to the store or installed on a device. The correct file should be `app-release-signed.apk`.

**Comment by andreban** [comment]
It seems #4 is getting more critical.
