### ISSUE TITLE
Add documentation section listing GUI tools alternatives powered by Bubblewrap

### ISSUE THREAD

**Issue by amanintech** [GoogleChromeLabs/bubblewrap#156]
Should we create a containerized web app the generates the APK from an online PWA using the bubblewrap CLI tool

**Comment by andreban** [comment]
Have you checked https://www.pwabuilder.com/? Their APK generation is powered by Bubblewrap.

**Comment by amanintech** [comment]
Oop then it might be helpful to mention that in the documentation that can help initial developers

**Comment by andreban** [comment]
Sounds like a good idea. I think it's worth creating a section on the docs about GUI tools powered by Bubblewrap. @jgw96 FYI

**Comment by amanintech** [comment]
BTW currently it doesn't work https://github.com/pwa-builder/CloudAPK/issues/20

**Comment by andreban** [comment]
Thanks for filing that. Added some details to the issue.

**Comment by JudahGabriel** [comment]
Hey, sorry about the APK not working. Something must have busted over the weekend. We'll have it back up shortly. I'll post here when it's up.

**Comment by jgw96** [comment]
Hello all! Thanks for the ping @andreban . As Judah said, looks like our service went down over the weekend. I am currently looking into this.

**Comment by amanintech** [comment]
@andreban where do you think the best location to add this information might be. 
Just first thoughts 
Should we set up a GitHub page that tells about bubble wrap?

**Comment by andreban** [comment]
@amanintech We can add a GUI Tools section to README.md. Creating a Github page would be great too, as we could host tsdocs for the core library too.

**Comment by amanintech** [comment]
Awesome let's do that. Will be throwing some initial templates.

**Comment by amanintech** [comment]
I almost forgot about this one. @andreban  can you please assign this to me ?

**Comment by andreban** [comment]
@amanintech done, thanks for this!
