### ISSUE TITLE
Change configuration file name from `llama-pack-config.json` to `bubblewrap-config.json`

### ISSUE THREAD

**Issue by amanintech** [GoogleChromeLabs/bubblewrap#159]
As the project name and its CLI command has been changed from `llama-pack` to `bubblewrap` , we should those name calls everywhere to avoid any confusions 
Possible places to change - `llama-pack.config.json` which contains the dependency directory.

**Comment by andreban** [comment]
I don't mind much keeping or changing the config name. But if changing, we need to ensure that users who already have a config with the old name don't lose it.

**Comment by amanintech** [comment]
Should we check both the old one and the new one in that case as a fallback condition or just leave it as it is

**Comment by andreban** [comment]
It sounds to me we should:
1. try reading the config with the new name.
2. If it fails, try loading the config with the old name..
3. If it succeeds, save a config file with the new name.
4. If loading the old name fails, prompt user for input the config.

**Comment by amanintech** [comment]
Yup, sounds right

**Comment by andreban** [comment]
Closed via #198
