### ISSUE TITLE
Create `version`, `--version` and `--help` commands

### ISSUE THREAD

**Issue by PEConn** [GoogleChromeLabs/bubblewrap#168]
Unix commands tend to support the `--help` and `--version` options (eg, `rm`, `find`, `ls`, `mv` all do).

Bubblewrap currently supports `help`, but does not recognize `--help`.

It would be good if we supported `--help` and `--version` (and since we have `help` we may as well support `version` too).

**Comment by andreban** [comment]
I think this can be done by:

1. adding `package.json` to the list of files on the `packages/cli/package.json`:
```json
  "files": [
    "dist",
    "bin",
    "package.json"
  ],
```

2. Creating code that reads `package.json`, parses and prints the version. Something similar to:
```typescript
const packageJsonFile = path.join(__dirname, '../../package.json');
const packageJsonContents = await (await fs.promises.readFile(packageJsonFile)).toString();
const packageJson = JSON.parse(packageJsonContents);
console.log(packageJson.version);
```
