### ISSUE TITLE
Support using pre-existing Android Studio Key

### ISSUE THREAD

**Issue by PEConn** [GoogleChromeLabs/bubblewrap#169]
If a developer has Android Studio installed, we could use the developer key that Android Studio creates for them.

We would want to:

- [ ] Have a look for the key in the default location for that OS.
- [ ] Change our default key alias from `android` to `androiddebugkey`.
- [ ] Either automatically use the default passwords or mention them to the user when prompting.

The default location and key set up can be found [here](https://stackoverflow.com/a/42858945).

**Comment by andreban** [comment]
In our case, we're not creating a debug key, and we should avoid using the debug key for deploying apps on Play.

That key we need to generate is either the upload key or the production key.

**Comment by PEConn** [comment]
Ah, user error on my part - maybe it would be nice to explicitly disallow it as I was able to use my debug key by just pointing to the path and using the default passwords.

**Comment by andreban** [comment]
We need at least to show a warning.

**Comment by andreban** [comment]
Closing this, as using the default key is not recommended for security reasons.
