### ISSUE TITLE
Lighthouse PWA check returns no even though it passes in Chrome

### ISSUE THREAD

**Issue by sceee** [GoogleChromeLabs/bubblewrap#173]
**Describe the bug**
When I build my app or run `bubblewrap validate`, the Lighthouse pwa check always returns "no":
![image](https://user-images.githubusercontent.com/11340487/82119971-fb8bb080-9782-11ea-8322-e3bbf53c728f.png)
I don't know the reason for this because when I execute the Lighthouse PWA check in Chrome, it passes.
Lighthouse also reports a performance score so it does seem to work generally.

**To Reproduce**
1. Execute `bubblewrap validate` or init new project from existing PWA and build it

**Expected behavior**
bubblewrap returns a positive PWA check result as Chrome does.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Windows 10 building an Android App
 - Browser: Chrome
 - Version: 81

**Smartphone (please complete the following information):**
Not relevant

**Additional context**

**Comment by andreban** [comment]
Can you provide information on the `start_url` being validated? 

We're using the PageSpeedInsights API (https://developers.google.com/speed/pagespeed/insights/) and results should be consistent to that.

**Comment by sceee** [comment]
@andreban with `start_url` you meant the PWA url, right?
Actually I have to admin I am a bit confused now about the PageSpeedInsights itself.
The PWA url is [https://app.traggr.com](https://app.traggr.com), the manifest url is [https://app.traggr.com/manifest.json](https://app.traggr.com/manifest.json).

For validation, I execute `bubblewrap validate --url=https://app.traggr.com`, results are as above (Lighthouse PWA check: No):
![image](https://user-images.githubusercontent.com/11340487/82141949-0acd3580-9839-11ea-9641-ce90468d80db.png)

Just for reference, for `init` I use `bubblewrap init --manifest https://app.traggr.com/manifest.json`

Now when I check the PWA via [https://developers.google.com/speed/pagespeed/insights/](https://developers.google.com/speed/pagespeed/insights/), it does not report anything regarding PWA. Just "regular" scoring:
![image](https://user-images.githubusercontent.com/11340487/82141999-80d19c80-9839-11ea-9638-aafcfaae1b85.png)


But if I execute the Lighthouse Audit in Chrome 81 DevTools, it reports the PWA compatibility as follows:
![image](https://user-images.githubusercontent.com/11340487/82141862-d48fb600-9838-11ea-9a63-ca0f52d9bcec.png)


I don't know if there is anything wrong with the PWA itself or with the PageSpeed Insights check that differs from the Lighthouse Check in Chrome DevTools. Do you have any idea what could be the reason for this?

**Comment by andreban** [comment]
On the Lighthouse audit, you do get the "Fast & Reliable" badge, but not the "Installable" badge, which is which the Bubblewrap check says "NO".

I your case, you are making an http request to googletagmanager.com. If you switch that to https (GTM should support that), you'll get full score.

The Lighthouse docs have [more information on badging](https://github.com/GoogleChrome/lighthouse/blob/master/docs/scoring.md). 

I think we can make the Bubblewrap validation better and breakdown those scores (and possibly link to the Lighthouse docs).

**Comment by sceee** [comment]
@andreban ah I see, thank you very much for your help and the insights.

Unfortunately, the http call to googletagmanager.com is resulting from this issue https://github.com/firebase/firebase-js-sdk/issues/2628 which is something out of our hands but this is definitely not an issue of bubblewrap. Still, it might affect a lot of PWAs (basically all using FB Analytics) and I will mention it over there.

And it's probably also a good idea to break the scores down better so users can better trace what's causing the "No".
Thanks again, from my point of view this can be closed.

**Comment by andreban** [comment]
Created another issue to track improvements for validation.

**Comment by Rahman24** [comment]
@andreban I too have the same issue 
chrome checks my pwa is perfect but the lighthouse pwa checks no
Please let me know the things I can do

**Comment by andreban** [comment]
Bubblewrap does not block building the APK when it fails the Lighthouse validation. The score is advisory.
