### ISSUE TITLE
Add support for fullscreen/immersive mode

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/bubblewrap#175]
`android-browser-helper` is making the Immersive Mode API easier to use:  is making the Immersive Mode API easier to use: https://github.com/GoogleChrome/android-browser-helper/issues/95

1. During the `init` command, Bubblewrap should use read `display` attribute from the Web Manifest.
2. If the `display` is fullscreen, default the configuration to use immersive mode. Otherwise, default to regular mode.
3. Ask the developer to confirm the choice.

**Comment by andreban** [comment]
A quick note that this came up on StackOverflow: https://stackoverflow.com/questions/61863976/hide-android-soft-navigation-in-twa-bubblewrap/61868961#61868961

**Comment by arpu** [comment]
i tested this with my small app on start it looks good on the splashscreen is fullscreen but than ist go back to normal  statusbar (test app is https://play.google.com/store/apps/details?id=com.vrland.twa)

**Comment by arpu** [comment]
found the problem i had to update the assetlinks.json  to new apk

**Comment by JohnRSim** [comment]
Could we add an enhancement to have fullscreen optional as either default or immersive?

So that fullscreen mode can still have the status and nav bar without the need to touch and toggle to display these items?

With the status bar being and overlay of the we content?

Thanks.
