### ISSUE TITLE
Missing debug output prevents tracking down errors

### ISSUE THREAD

**Issue by pianomister** [GoogleChromeLabs/bubblewrap#177]
**Is your feature request related to a problem? Please describe.**
The bubblewrap build can fail for a couple of reasons, especially if the error occurs in a tool used through bubblewrap (e.g. gradle commands or Android helpers like keytool and adb). In these cases, the error message, e.g. "error command failed", does not help to track down the issue that caused the error.

**Describe the solution you'd like**
More verbose or additional debug output (probably using an additional --debug parameter) would help to understand the cause for an error. Routing through the errors thrown by the external tool or custom error messages by bubblewrap for common errors, would help to understand the underlying issue.

**Describe alternatives you've considered**
Options to get additional output:
- Route through error messages by 3rd party tools into bubblewrap's console output (perhaps only via a --debug or --verbose param)
- Custom error messages by bubblewrap for common errors with instructions what to check for fixing
- A separate debug log file (perhaps only written with --debug param), also helps with error reporting

**Additional context**
Example output for a non-descriptive error:
```
my-macbookpro% bubblewrap build --skipPwaValidation
? KeyStore password: *******
? Key password: *******
build Building the Android App...


cli ERROR Command failed: ./gradlew assembleRelease --stacktrace


my-macbookpro%
```

**Comment by arpu** [comment]
i hitting this right now 

```
 arpu@hokuspokus  ~/Work/projects/twa_test  bubblewrap build                                                                                                                                                                                                                                          ✔  10110  21:31:20
? KeyStore password: ************
? Key password: ************
build Building the Android App...


cli ERROR Command failed: ./gradlew assembleRelease --stacktrace



 arpu@hokuspokus  ~/Work/projects/twa_test  ./gradlew assembleRelease --stacktrace                                                                                                                                                                                                                  1 ↵  10111  21:31:40

BUILD SUCCESSFUL in 8s
24 actionable tasks: 22 executed, 2 up-to-date


```

**Comment by arpu** [comment]
problem for me was wrong java lib path in .llama-pack/llama-pack-config.json

**Comment by andreban** [comment]
Thanks for the update. We're looking into implementing #181 to make it easy to check if the config and dependencies are correct.

**Comment by nitzanashi** [comment]
I have the same issue, only that on my local machine it works fine but then on the CI `build` is not working but when I'm running `./gradlew assembleRelease --stacktrace`  it works as expected

**Comment by andreban** [comment]
We're currently working on #181 that should improve debugging the configuration.

**Comment by andreban** [comment]
The `doctor` command was landed and should improve this.
