### ISSUE TITLE
Create a `doctor` command

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/bubblewrap#181]
`bubblewrap doctor` should check the configuration file and if settings for the location of the Java JDK and Android SDK are valid, along with information on how to download and setup.

See https://flutter.dev/docs/get-started/install/windows#run-flutter-doctor for an example of what the command could look like.

**Comment by PEConn** [comment]
We can also check whether the version of the JDK is valid (==8).

**Comment by andreban** [comment]
Closed via #296
