### ISSUE TITLE
Llama-pack in Google docs

### ISSUE THREAD

**Issue by Maxim-Mazurok** [GoogleChromeLabs/bubblewrap#185]
In the [Trusted Web Activities, the Lay of the Land](https://developers.google.com/web/android/trusted-web-activity/lay-of-the-land) article by @PEConn there are two mentions of "Llama-pack" - the old name of the package.
Should be renamed, I think.

**Comment by Maxim-Mazurok** [comment]
Let me know if I should submit this issue to [google/webfundamentals](https://github.com/google/webfundamentals/issues/new) instead

**Comment by andreban** [comment]
Thanks for the report. We replaced in most docs, but seems those instances escaped. We should definitely fix it. Let me know if you'd like to make a pull-request to WebFundamentals. Otherwise, happy to do it.

**Comment by Maxim-Mazurok** [comment]
I will! Didn't realize that the content was open-source :)
