### ISSUE TITLE
Use icon purpose to style shortcut icons

### ISSUE THREAD

**Issue by NotWoods** [GoogleChromeLabs/bubblewrap#200]
**Is your feature request related to a problem? Please describe.**
Currently web apps can specify app shortcuts, but the icons must be styled to match Android rather than being generic for any OS. Otherwise, the icons will look out of place on Android.

**Describe the solution you'd like**
I've been working on adding a new icon purpose with the W3C. It would be nice for this new purpose, along with maskable, to have an effect on the resulting shortcut.

Shortcut icons can be automatically styled differently depending on their `"purpose"` field. In addition to the default "any" purpose, there are now "maskable" and "monochrome" purposes. 

"maskable" icons should fill up the entire shortcut area, like contact shortcuts on Android.
![Avatar shortcut](https://user-images.githubusercontent.com/1782266/84925541-e99d7600-b07e-11ea-9574-6226e5361489.png)

"monochrome" icons should automatically be scaled and tinted with `theme_color` to match other Android shortcut icons. This way, a colored icon could be used for a shortcut on Windows while a single color icon can be used on Android.
![Standard shortcut](https://user-images.githubusercontent.com/1782266/84925831-5ca6ec80-b07f-11ea-9370-0a07ea088469.png)

Corresponding WebAPK request: https://bugs.chromium.org/p/chromium/issues/detail?id=1093086#c1

**Comment by PEConn** [comment]
This could help fix Issue #180
