### ISSUE TITLE
Using existing Android Studio SDK installation does not work

### ISSUE THREAD

**Issue by EricHier** [GoogleChromeLabs/bubblewrap#202]
**Describe the bug**
When using the SDK path created by Android Studio in the llama config, the build process does not work. I get a `java.lang.ClassNotFoundException: ''`. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Android Studio
2. When initializing a new project, paste the SDK path from Android Studio settings. 
3. Build the application

**Expected behaviour**
Bubblewrap should use the installation of the Android SDK. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Android Build Tools: 30.0.2
 - Buublewrap: 1.3.1 (latest)

**Comment by andreban** [comment]
We do [recommend download the Android CLI Tools separately](https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli#get-the-android-command-line-tools) as the easiest path.

What's the path being used on the config as the SDK location?

**Comment by andreban** [comment]
Tested using the tools installed by Android Studio, and it does work. This is the path I'm using in the config:

```
C:\Users\andre\AppData\Local\Android\sdk
```

**Comment by EricHier** [comment]
I found out that the problem was the wrong Java path.
