### ISSUE TITLE
Unclear about build options

### ISSUE THREAD

**Issue by leolux** [GoogleChromeLabs/bubblewrap#206]
After the `init` step has been completed by bubblewrap I can open the generated files with Android Studio. Regarding the documentation the build step seems to require bubblewrap. But I was able to build the APK with Android Studio as well. 
Is the command `bubblewrap build` absolutely required to build the APK correctly or is it just fine to use Android Studio as well?

**Comment by andreban** [comment]
Added a note to the README via #207.  Information on JDK requirements are documented here: https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli#get-the-java-development-kit-jdk-8

TL;DR is that Bubblewrap doesn't use the JDK directly and requirements are from the Android CLI tools.

**Comment by andreban** [comment]
Closed via #207
