### ISSUE TITLE
Support Web Share Target

### ISSUE THREAD

**Issue by NotWoods** [GoogleChromeLabs/bubblewrap#21]
Similar to shortcuts, generate XML entries for the [Web Share Target](https://wicg.github.io/web-share-target/) API. These entries would probably be intent filters in the Android Manifest.

**Comment by andreban** [comment]
Thanks for filing this.
The [shortcuts section](https://github.com/GoogleChromeLabs/llama-pack/blob/master/template_project/app/build.gradle#L31-L39) of the template project can be used to add this support.

We are missing code to extract details from an existing Web Manifest, confirm those details with the developer and then generate the shortcut section.

**Comment by andreban** [comment]
This has now been implemented.

**Comment by anuragvohraec** [comment]
> This has now been implemented.
It seems to be not working though.
Here is my pwa manifest file: https://yeio.app/manifest.json
It works all find when installed directly using "Add to homescreen".
However ever since pubslishing this to Play store, it do not works.
Please help.
