### ISSUE TITLE
Option to run bubblewrap on CI/CD

### ISSUE THREAD

**Issue by nitzanashi** [GoogleChromeLabs/bubblewrap#213]
**Is your feature request related to a problem? Please describe.**
I would like to use bubble wrap in my  CI/CD pipeline, at the moment I'm using GitHub actions but I don't think this issue is related to on which platform I use the CI/CD rather the option to setup bubblewrap.

Currently I don't have an option to config the bubblewrap with CI since I need to setup the OpenJDK, AndroidSDK. which will then be setup outside of the project scope on the root directory, when working on the project with someone else he will have to do the same setup but also outside of the project.

**Describe the solution you'd like**
It will be nice to have the option to setup the config file `llama-pack-config.json` inside the project scope, so that other contributions would be able to work with same configuration. My guess that it will also resolve the issue with settings for CI/CD

**Comment by andreban** [comment]
Would #172 solve the problem for you?

**Comment by nitzanashi** [comment]
> Would #172 solve the problem for you?

@andreban yes this exactly what I want, well, in this case, I guess we can close this issue, will follow the other one

**Comment by andreban** [comment]
Duplicate of #172
