### ISSUE TITLE
Allow iconUrl to be empty in TWA manifest

### ISSUE THREAD

**Issue by victorenaud** [GoogleChromeLabs/bubblewrap#214]
**Is your feature request related to a problem? Please describe.**
It is impossible to `update` the build with no `iconUrl`

**Describe the solution you'd like**
Allow `iconUrl` to be empty, and don't generate the splash screen when it occurs

**Additional context**
On `update`, the validation of the TWA manifest fail when `iconUrl` is empty.
In `TwaManifest.validate()`:
```
    if (!this.iconUrl) {
      return 'iconUrl cannot be empty';
    }
```

But when I look at the code of update, the case of an empty `iconUrl` seems to be allowed. (the splash screen will not be generated in this case)
In `TwaGenerator.createTwaProject()`:
``` 
    if (twaManifest.iconUrl) {
      await this.generateIcons(twaManifest.iconUrl, targetDirectory, IMAGES);
    }
```

**Comment by andreban** [comment]
`iconUrl` is used to generate the splash screen and home screen icons, so it *is* required. Disabling splash screens causes a flash of white content when the app is opened from the home screen, which is also a bad user experience. This would cause issues on `init` too btw, so we the CLI prevents not having an icon. Did you manually change the `twa-manifest to remove the `iconUrl`?

**Comment by victorenaud** [comment]
In my understanding, it is possible to set the splash screen background color with the `backgroundColor` attribute.

We would be interested in only having a colored splash screen, but not an image.
Thus it would remove the white content on opening, while removing the use of an `iconUrl`

Yes, I manually changed the `twa-manifest` to get the error.

**Comment by andreban** [comment]
On the browser side, not providing a splash screen image removes the splash screen entirely.

Bubblewrap aims to be consistent (see #66) with installable PWAs and uses `iconUrl` for both the launcher icons and splash screen. There is a higher degree of flexibility though, but an `iconUrl` is still needed to generate the icons for the home screen. 

The main request here seems to be to enable providing a different image for the home screen icon and for the splash screen. With that, a transparent image or one with the same colour as the background colour could be used for the splash screen.

One thing to keep in mind is that a [PWA](https://web.dev/progressive-web-apps/) opened inside a Trusted Web Activity must meet the [Quality Criteria](https://web.dev/using-a-pwa-in-your-android-app/#quality-criteria), which includes the full PWA check on Lighthouse. For that, the PWA [must provide an icon with a minimum dimension of 512x512px](https://web.dev/install-criteria/#criteria). So, you'll still need an icon to fulfil the criteria. That same icon is used when the PWA added to the home screen via the browser *add to-home screen* prompt.

**Comment by andreban** [comment]
Created #226 to track allowing a different image for the splash screen, which should solve this.
