### ISSUE TITLE
Display badge for the number of push notifications

### ISSUE THREAD

**Issue by leolux** [GoogleChromeLabs/bubblewrap#219]
There is a difference between PWA and TWA regarding push notifications. PWAs work as expected and display the number push notifications as a badge on top of the app icon. TWA do not display a badge for push notifications. Has anyone dived into this?

**Comment by andreban** [comment]
This is the first time we see this report, so I don't think anyone has taken a deep dive. Do you have `enableNotifications: true` in the `twa-manifest.json`?

**Comment by leolux** [comment]
No, but I have set  `enableNotifications: false` in the file `build.gradle`. As far as I can remember `false `is the default. There is a comment for the property which says; "Set to true to enable notification delegation." I thought that the `delegation` to the native app would not be required because PWA should be able to handles notifcations and badges already.

**Comment by mcmultimedia** [comment]
@andreban can you teach me more about push Notification. I think it will help me so much

**Comment by JohnRSim** [comment]
Any updates on this?

PWA I'm guessing would using web push and work as normal.

TWA could use web push but guessing notification icons won't display?

Instead TWA should use native android notifications with event delegation enabled?

https://github.com/GoogleChrome/android-browser-helper/tree/master/demos/twa-notification-delegation

**Comment by andreban** [comment]
This issue is no obsolete, as notification Delegation is now enabled by default in Bubblewrap.
