### ISSUE TITLE
ServeiceWorker update with reload

### ISSUE THREAD

**Issue by arpu** [GoogleChromeLabs/bubblewrap#221]
after updating the webside on normal chrome the webside gets reloaded with the new version with this serviceWorker config:

```
export default {
	onUpdate: registration => {

		registration.unregister().then( () => {

			window.location.reload();

		} );

	},
	onSuccess: registration => {

		console.info( 'service worker on success state' );
		console.log( registration );

	},
};



```

the TWA/PWA app do not reload the web contend

**Comment by andreban** [comment]
It seems you are having caching issues on the Service Worker. The Service Worker behaviour in a Trusted Web Activity is exactly the same as in the regular Progressive Web App.

**Comment by arpu** [comment]
Hey @andreban,

any idea how i can debug this? it just works in normal chrome ( pc and android)

**Comment by arpu** [comment]
ok after i clear the cache in the android apps  than the new version is loaded!

**Comment by andreban** [comment]
Overall, you shouldn't need uninstall / reload the to update the Service Worker. Here are some resources that may help:

- https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/update
- https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#manual_updates

Workbox is a tool that takes away the complexity of Service Workers and may help: https://web.dev/workbox/

Finally, if you still have questions, I'd recommend asking on https://stackoverflow.com/questions/tagged/service-worker

I'm closing this issue as it's unrelated to Bubblewrap.

**Comment by arpu** [comment]
hmm
i not complete understand why this is unrelated to pwa/twa the service-worker implementation i use is with 
workbox and works just fine on chrome android and pc and firefox but not on pwa/twa with Bubblewrap 

webpack config is
```
new WorkboxWebpackPlugin.GenerateSW( {
    			clientsClaim: true,
    			exclude: [ /\.map$/, /asset-manifest\.json$/ ],
    			navigateFallback: './index.html',
    			navigateFallbackDenylist: [
				  // Exclude URLs starting with /_, as they're likely an API call
				  new RegExp( '^/_' ),
				  // Exclude any URLs whose last part seems to be a file extension
				  // as they're likely a resource and not a SPA route.
				  // URLs containing a "?" character won't be blacklisted as they're likely
				  // a route with query params (e.g. auth callbacks).
				  new RegExp( '/[^/?]+\\.[^/]+$' ),
    			],
			  } ),

```

so lets be clear service-worker works just fine ( with manual update )

**Comment by arpu** [comment]
or is the idea i need to Release a new twa app each time if i changed something in the webappß
