### ISSUE TITLE
Provide Keystore Password and Key Password as build command options 

### ISSUE THREAD

**Issue by jkowalczyk** [GoogleChromeLabs/bubblewrap#222]
**Is your feature request related to a problem? Please describe.**
The build task is executed automatically with gitlab-ci. 

**Describe the solution you'd like**
So far, I need to use the [expect](https://linux.die.net/man/1/expect) tool for the interactive part.

**Describe alternatives you've considered**
The 2 options could be added as build command options 

```
bubblewrap build --keyStorePassword $myKeyStorePassword --keyPassword $myKeyPassword 
```

**Comment by andreban** [comment]
Te `build` step supports using environment variables as passwords:

 - `BUBBLEWRAP_KEYSTORE_PASSWORD` for the key store password,
 - `BUBBLEWRAP_KEY_PASSWORD` as the key password. 

Does this solve the issue?

**Comment by jkowalczyk** [comment]
Yes that's perfect.

You should probably update the documentation :p
