### ISSUE TITLE
twa-manifest host can not contain `https://`

### ISSUE THREAD

**Issue by nitzanashi** [GoogleChromeLabs/bubblewrap#227]
**Describe the bug**
when a host parameter is passed to the `twa-manifest` with `https://` prefix the TWA will be built successfully but once installed, we will get an error.The TWA will point to an empty `https` address.

**To Reproduce**
1. on the TWA-manifest add `https://` prefix to the `host` parameter
2. run `bubblewrap update` then `build`  everything should be OK
3. Install TWA on a Device or run on emulotor

**Expected behavior**
Well here there are 2 scenarios that I can see:
1. bubblewrap will complain to the user on `update` that the host parameter is not acceptable.
2. bubblewrap will phrase the host correctly and get rid of `https://` prefix if needed.

I will suggest to go with option 2, this can be achieved with [URL constructor](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) it will also be more consistent with the`iconUrl` and `webManifestUrl`

**Desktop (please complete the following information):**
 - OS: iOS
 - Chrome

**Comment by andreban** [comment]
I don't think option 2 invalidates option 1. Validating the host should happen, regardless of accepting or not `https`. A not that, when allowing the schema to be added only `https` is accepted and anything else (eg: `http`) will be an error.

**Comment by andreban** [comment]
Related: I'm working #230, to refactoring on prompting the user for input and validating. Added support for `https://` when the URL is typed on `init`.

**Comment by andreban** [comment]
Closed via #230
