### ISSUE TITLE
Include Android CLI path requirements in README

### ISSUE THREAD

**Issue by jamieoneill** [GoogleChromeLabs/bubblewrap#233]
Android CLI location should not contain whitespace.

an error i made when following the tutorial. [#223](https://github.com/GoogleChromeLabs/bubblewrap/issues/223#issuecomment-656181524).

Please include a note in the Readme to this effect when setting llama-pack-config.json

**Comment by jamieoneill** [comment]
and include this check as part of doctor command #181

**Comment by andreban** [comment]
There are 3 things we need to do to improve this:

- [ ] Add the this information to the docs
- [ ] Have `doctor` check for spaces in the SDK path
- [ ] Make [createConfig](https://github.com/GoogleChromeLabs/bubblewrap/blob/master/packages/cli/src/lib/config.ts#L32-L45) check for spaces in the path and reject the input:

**Comment by andreban** [comment]
@chenlevy24 FYI
