### ISSUE TITLE
Build error when running `@bubblewrap/cli build`: ERROR Command failed: ./gradlew assembleRelease --stacktrace

### ISSUE THREAD

**Issue by d-koppenhagen** [GoogleChromeLabs/bubblewrap#235]
**Describe the bug**

```bash
npx @bubblewrap/cli build
? KeyStore password: ********
? Key password: ********
build Building the Android App...


cli ERROR Command failed: ./gradlew assembleRelease --stacktrace
```

**To Reproduce**
1. init bubblewrap project without an existing keystore :
```bash
npx @bubblewrap/cli init --manifest https://bm4-pwa.angular-buch.com/manifest.json
init Fetching Manifest:  https://bm4-pwa.angular-buch.com/manifest.json
? Domain being opened in the TWA: bm4-pwa.angular-buch.com
? Name of the application: BookMonkey 4 PWA
? Name to be shown on the Android Launcher: BookMonkey
? Color to be used for the status bar: #DB2828
? Color to be used for the splash screen background: #FAFAFA
? Relative path to open the TWA: /
? URL to an image that is at least 512x512px: https://bm4-pwa.angular-buch.com/assets/icons/icon-512x512.png
? URL to an image that is at least 512x512px to be used when generating maskable icons undefined
? Include app shortcuts?
[] Yes
? Android Package Name (or Application ID): com.angular_buch.bm4_pwa.twa
? Location of the Signing Key: ./android.keystore
? Key name: android
Saving Config to: ./twa-manifest.json
twa-generator Generating Android Project files:
twa-generator    /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/settings.gradle
twa-generator    /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/gradle.properties
twa-generator    /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/build.gradle
twa-generator    /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/gradlew
twa-generator    /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/gradlew.bat
twa-generator    /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/gradle/wrapper/gradle-wrapper.jar
twa-generator    /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/gradle/wrapper/gradle-wrapper.properties
twa-generator    /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/src/main/res/values/styles.xml
twa-generator    /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/src/main/res/xml/filepaths.xml
twa-generator    /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/src/main/res/xml/shortcuts.xml
twa-generator    /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/build.gradle
twa-generator    /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/src/main/AndroidManifest.xml
twa-generator    72x72 Icon: /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/src/main/res/mipmap-hdpi/ic_launcher.png
twa-generator    48x48 Icon: /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/src/main/res/mipmap-mdpi/ic_launcher.png
twa-generator    96x96 Icon: /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/src/main/res/mipmap-xhdpi/ic_launcher.png
twa-generator    144x144 Icon: /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
twa-generator    192x192 Icon: /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
twa-generator    450x450 Icon: /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/src/main/res/drawable-hdpi/splash.png
twa-generator    300x300 Icon: /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/src/main/res/drawable-mdpi/splash.png
twa-generator    600x600 Icon: /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/src/main/res/drawable-xhdpi/splash.png
twa-generator    900x900 Icon: /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/src/main/res/drawable-xxhdpi/splash.png
twa-generator    1200x1200 Icon: /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/app/src/main/res/drawable-xxxhdpi/splash.png
twa-generator    512x512 Icon: /Users/my-user/dev/book-monkey4-pwa-twa-wrapper/store_icon.png
? Signing Key could not be found at "./android.keystore". Do you want to create one now? Yes
? First and Last names (eg: John Doe): John Doe
? Organizational Unit (eg: Engineering Dept): Engineering Dept
? Organization (eg: Company Name): My Company
? Country (2 letter code): DE
? Password for the Key Store: [hidden]
? Password for the Key: [hidden]
keytool Signing Key created successfully
init 
init Project generated successfully. Build it by running "@bubblewrap/cli build"
```
2. Run the build
```bash
npx @bubblewrap/cli build
```
3. the error message appears after entering the korrekt passwords:
```bash
cli ERROR Command failed: ./gradlew assembleRelease --stacktrace
```

**Expected behavior**

**Screenshots**
<img width="1440" alt="Screenshot 2020-07-12 at 20 09 07" src="https://user-images.githubusercontent.com/4279702/87253453-a2d34e00-c47b-11ea-8725-052f2c463a5b.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.5
- NPM: 6.14.5
- Node.js: v13.12.0
- openjdk version "1.8.0_252"
- OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
- OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)

**Additional context**
When I just proceed running `bubblewrap init` with all it's step and I build the signed APK with Android Studio by setting up a new keystore with a new key, the build process for the signed APK works fine.

Are there any stept to debug the problem and to get some more information about the concrete problem that appeared?

**Comment by d-koppenhagen** [comment]
PS: my JAVA SDK Path seems to be ok:
<img width="1134" alt="Screenshot 2020-07-12 at 20 30 45" src="https://user-images.githubusercontent.com/4279702/87253844-a87e6300-c47e-11ea-8030-e2a9ec62c075.png">

**Comment by andreban** [comment]
Can you paste the content of `~/.llama-pack/llama-pack-config.json`?

**Comment by d-koppenhagen** [comment]
Sure:

```json
{
  "jdkPath":"/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home",
  "androidSdkPath":"/Users/my-user/Library/Android/sdk"
}
```

**Comment by andreban** [comment]
Your config is pointing to a sub-directory of where the JDK was unzipped. (Just realized [this section](https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli#tell-bubblewrap-where-the-jdk-and-android-command-line-tools-are) of docs is not clear for MacOS).

Try the following:
```json
{
  "jdkPath":"/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/",
  "androidSdkPath":"/Users/my-user/Library/Android/sdk"
}
```

**Comment by d-koppenhagen** [comment]
Awesome, with this change it works.
Yes I think the problematic part in the docs is:

> The OpenJDK path should contain bin,com,include ..

This should be changed I think

**Comment by Jun711** [comment]
@andreban
@d-koppenhagen 

I was giving BubbleWrap a try by running commands from this page https://web.dev/using-a-pwa-in-your-android-app/#bubblewrap
`npx @bubblewrap/cli init --manifest=https://pwa-directory.appspot.com/manifest.json`

Then, I realized I needed to set up JDK. 
To do that, I followed the steps on https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli

1) Download a version of JDK 8 that is compatible with your OS from AdoptOpenJDK and extract it in its own folder.
https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot

I downloaded OpenJDK 8

2) I downloaded CLI tools
https://developer.android.com/studio#command-tools

After unzipping, I have these folders
![Screen Shot 2020-07-14 at 5 41 00 PM](https://user-images.githubusercontent.com/6880939/87489945-2fefe180-c5f9-11ea-8fe4-e9c87d102864.png)
<img width="568" alt="Screen Shot 2020-07-14 at 5 47 18 PM" src="https://user-images.githubusercontent.com/6880939/87490237-113e1a80-c5fa-11ea-855f-befc7c7de3eb.png">

I have these in my llama-pack-config.json
```
{ 
  "jdkPath":"/Users/jun/Downloads/jdk8u252-b09",                 
  "androidSdkPath":"/Users/jun/Downloads/tools"
}   
```

When I ran `npx @bubblewrap/cli init --manifest=https://pwa-directory.appspot.com/manifest.json`, I got this error. 

![Screen Shot 2020-07-14 at 5 50 30 PM](https://user-images.githubusercontent.com/6880939/87490419-84479100-c5fa-11ea-9134-808336fa7948.png)

Error message:
```
cli ERROR Command failed: keytool -genkeypair -dname "cn=JD, ou=Eng, o=C, c=CA" -alias "./android.keystore" -keypass "123456" -keystore "./android.keystore" -storepass "123456" -validity 20000 -keyalg RSA
No Java runtime present, requesting install.
```
I think it is probably the same issue as this. Could you help me with this? Thank you.

**Comment by d-koppenhagen** [comment]
I think is's a bit different from the original reported issue. So at least I didn't got an error message like this one.

**Comment by d-koppenhagen** [comment]
Maybe you don't have access rights for the keytool.
Can you show the console log for the JDK and Android SDK path when executing `la -lha`

**Comment by andreban** [comment]
This is indeed a different issue. It seems `keytool` is unable to find the Java runtime. Would you mind filing a another issue for this?
