### ISSUE TITLE
keytool is unable to find the Java runtime

### ISSUE THREAD

**Issue by Jun711** [GoogleChromeLabs/bubblewrap#239]
@andreban
@d-koppenhagen 

I was giving BubbleWrap a try by running commands from this page https://web.dev/using-a-pwa-in-your-android-app/#bubblewrap
`npx @bubblewrap/cli init --manifest=https://pwa-directory.appspot.com/manifest.json`

Then, I realized I needed to set up JDK. 
To do that, I followed the steps on https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli

1) Download a version of JDK 8 that is compatible with your OS from AdoptOpenJDK and extract it in its own folder.
https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot

I downloaded OpenJDK 8

2) I downloaded CLI tools
https://developer.android.com/studio#command-tools

After unzipping, I have these folders
![Screen Shot 2020-07-14 at 5 41 00 PM](https://user-images.githubusercontent.com/6880939/87489945-2fefe180-c5f9-11ea-8fe4-e9c87d102864.png)
<img width="568" alt="Screen Shot 2020-07-14 at 5 47 18 PM" src="https://user-images.githubusercontent.com/6880939/87490237-113e1a80-c5fa-11ea-855f-befc7c7de3eb.png">

I have these in my llama-pack-config.json
```
{ 
  "jdkPath":"/Users/jun/Downloads/jdk8u252-b09",                 
  "androidSdkPath":"/Users/jun/Downloads/tools"
}   
```

When I ran `npx @bubblewrap/cli init --manifest=https://pwa-directory.appspot.com/manifest.json`, I got this error. 

![Screen Shot 2020-07-14 at 5 50 30 PM](https://user-images.githubusercontent.com/6880939/87490419-84479100-c5fa-11ea-9134-808336fa7948.png)

Error message:
```
cli ERROR Command failed: keytool -genkeypair -dname "cn=JD, ou=Eng, o=C, c=CA" -alias "./android.keystore" -keypass "123456" -keystore "./android.keystore" -storepass "123456" -validity 20000 -keyalg RSA
No Java runtime present, requesting install.
```

folder access
```
-rw-r--r--@  1 jun  staff    96M 14 Jul 17:19 OpenJDK8U-jdk_x64_mac_hotspot_8u252b09.tar.gz
-rw-r--r--@  1 jun  staff    83M 14 Jul 17:19 commandlinetools-mac-6609375_latest.zip
drwxr-xr-x@  3 jun  staff    96B 22 Apr 01:54 jdk8u252-b09
drwxr-xr-x@  6 jun  staff   192B 14 Jul 17:21 tools
```

**Comment by d-koppenhagen** [comment]
can you show the output of `last -lha` of the content from the JDK and Android SDK dir (`tools`)?

**Comment by Jun711** [comment]
JDK
```
ls -lha                                                jdk8u252-b09  11:10am
total 0
drwxr-xr-x@ 3 jun  staff    96B 22 Apr 01:54 .
drwx------@ 8 jun  staff   256B 15 Jul 10:00 ..
drwxr-xr-x@ 6 jun  staff   192B 22 Apr 01:57 Contents
```

SDK dir (tools)
```
ls -lha                                                       tools  11:11am
total 176
drwxr-xr-x@  6 jun  staff   192B 14 Jul 17:21 .
drwx------@  8 jun  staff   256B 15 Jul 10:00 ..
-rwxr-xr-x@  1 jun  staff    83K  1 Jan  2010 NOTICE.txt
drwxr-xr-x@  7 jun  staff   224B 14 Jul 17:21 bin
drwxr-xr-x@ 22 jun  staff   704B 14 Jul 17:21 lib
-rwxr-xr-x@  1 jun  staff    84B  1 Jan  2010 source.properties
```

**Comment by andreban** [comment]
Do you have a file at `~/.bubblewrap/config.json`? Could you paste the content if you do? Also the output of `npx @bubblewrap/cli version`

**Comment by Jun711** [comment]
yes, 
`~/.bubblewrap/config.json`. It it different from what I wrote in `llama-pack-config.json` 
Which config file is being used?
```
{"jdkPath":"/Users/jun/Downloads/jdk8u252-b09/Contents/Home","androidSdkPath":"/Users/jun/Downloads/tools"}
```

`npx @bubblewrap/cli version`
```
info sharp Using cached /Users/jun/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz
,-----.        ,--.  ,--.  ,--.
|  |) /_,--.,--|  |-.|  |-.|  |,---.,--.   ,--,--.--.,--,--.,---.
|  .-.  |  ||  | .-. | .-. |  | .-. |  |.'.|  |  .--' ,-.  | .-. |
|  '--' '  ''  | `-' | `-' |  \   --|   .'.   |  |  \ '-'  | '-' '
`------' `----' `---' `---'`--'`----'--'   '--`--'   `--`--|  |-'
                                                           `--'    
version 1.4.0
```

**Comment by Jun711** [comment]
@andreban 
I fixed the jdkPath in `~/.bubblewrap/config.json` and I could run `npx @bubblewrap/cli init --manifest=https://pwa-directory.appspot.com/manifest.json` successfully. 

I guess `llama-pack-config.json` is not needed? 

![Screen Shot 2020-07-15 at 11 35 32 AM](https://user-images.githubusercontent.com/6880939/87582524-5d876a00-c68f-11ea-9ddf-74e07dee4479.png)

**Comment by Jun711** [comment]
I proceeded with the build step but it cannot find the sdkmanager from the downloaded SDK dir
```
npx @bubblewrap/cli build                                 Downloads  11:35am
info sharp Using cached /Users/jun/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz
,-----.        ,--.  ,--.  ,--.
|  |) /_,--.,--|  |-.|  |-.|  |,---.,--.   ,--,--.--.,--,--.,---.
|  .-.  |  ||  | .-. | .-. |  | .-. |  |.'.|  |  .--' ,-.  | .-. |
|  '--' '  ''  | `-' | `-' |  \   --|   .'.   |  |  \ '-'  | '-' '
`------' `----' `---' `---'`--'`----'--'   '--`--'   `--`--|  |-'
                                                           `--'    
Installing Android Build Tools. Please, read and accept the license agreement


cli ERROR Could not find sdkmanager at: /Users/jun/Downloads/tools/tools/bin/sdkmanager

```

**Comment by Jun711** [comment]
@andreban 
I removed `tools` from the androidPath in `~/.bubblewrap/config.json`

The content in `~/.bubblewrap/config.json` is now
```
{
  "jdkPath":"/Users/jun/Downloads/jdk8u252-b09",
  "androidSdkPath":"/Users/jun/Downloads"
}
```

Now, I can proceed with build stage but it can't find twa-manifest.json
```
cli ERROR ENOENT: no such file or directory, open './twa-manifest.json'
```

```
info sharp Using cached /Users/jun/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz
,-----.        ,--.  ,--.  ,--.
|  |) /_,--.,--|  |-.|  |-.|  |,---.,--.   ,--,--.--.,--,--.,---.
|  .-.  |  ||  | .-. | .-. |  | .-. |  |.'.|  |  .--' ,-.  | .-. |
|  '--' '  ''  | `-' | `-' |  \   --|   .'.   |  |  \ '-'  | '-' '
`------' `----' `---' `---'`--'`----'--'   '--`--'   `--`--|  |-'
                                                           `--'    
Installing Android Build Tools. Please, read and accept the license agreement
build Installing Build Tools
(node:4225) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/jun/Downloads/tools/twa-manifest.json'
(node:4225) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4225) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by andreban** [comment]
Looks like you are running bubblewrap from the `/Users/jun/Downloads/tools/twa-manifest.json`. You should run it in the same folder where you executed `init` (which will have a `twa-manifest.json` file)

**Comment by Jun711** [comment]
Thanks @andreban I have successfully built and got the apk file `app-release-signed.apk`
 
I think the https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli can be updated.
Does it use `llama-pack-config.json`?

**Comment by andreban** [comment]
Updated  README.md

**Comment by Jun711** [comment]
@andreban 
I have some further questions regarding app directory and what androidSdkPath should actually be. 
Did I miss a step in configuring the paths?

1
my bubblewrap config had this
```
{"jdkPath":"/Users/jun/Downloads/jdk8u252-b09","androidSdkPath":"/Users/jun/Downloads/tools"}
```
I was in the Downloads dir and I ran 
```
npx @bubblewrap/cli init --manifest=https://pwa-directory.appspot.com/manifest.json --directory='./pwa-android' 
```

Downloads dir has this in the beginning
![Screen Shot 2020-07-15 at 2 12 22 PM](https://user-images.githubusercontent.com/6880939/87596577-363b9780-c6a5-11ea-85ff-900759e2a680.png)

After running the command, I noticed that `./twa-manifest.json` is saved in the current directory instead of the directory I specified `--directory='./pwa-android'`
![Screen Shot 2020-07-15 at 2 17 52 PM](https://user-images.githubusercontent.com/6880939/87597056-faed9880-c6a5-11ea-93ef-c64814b86d58.png)

2 
Then, I moved `twa-manifest.json` into `pwa-android` dir.
In `pwa-android` dir, I ran `npx @bubblewrap/cli build` and I got this error. `cli ERROR Could not find sdkmanager at: /Users/jun/Downloads/tools/tools/bin/sdkmanager`. I encountered this error earlier and it can be fixed by changing my androidSdkPath to `/Users/jun/Downloads` instead of `/Users/jun/Downloads/tools`

```
{"jdkPath":"/Users/jun/Downloads/jdk8u252-b09","androidSdkPath":"/Users/jun/Downloads"}
```

![Screen Shot 2020-07-15 at 2 21 55 PM](https://user-images.githubusercontent.com/6880939/87597373-8bc47400-c6a6-11ea-943c-022a423e2d8c.png)

3
After I changed my androidSdkPath, I ran `npx @bubblewrap/cli build` in `pwa-android` dir again.

This time, it could build
![Screen Shot 2020-07-15 at 2 25 30 PM](https://user-images.githubusercontent.com/6880939/87597670-0bead980-c6a7-11ea-9120-d74215747617.png)

After accepting the license, a new dir: `licenses` appears in the Downloads dir which I expected to be in `pwa-android` dir.
![Screen Shot 2020-07-15 at 2 27 13 PM](https://user-images.githubusercontent.com/6880939/87597802-494f6700-c6a7-11ea-8383-2a3e3db2aca4.png)

4 
After it built successfully, a few more dirs: `build-tools`, `platform-tools` and `platforms` appear in Downloads dir instead of `pwa-android` dir. Is this expected?
![Screen Shot 2020-07-15 at 2 30 17 PM](https://user-images.githubusercontent.com/6880939/87598047-b662fc80-c6a7-11ea-84fd-e661221b5d4e.png)

5
apk works as I can install it on my phone.

```
npx @bubblewrap/cli install                                                     pwa-android   2:36pm
info sharp Using cached /Users/jun/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz
,-----.        ,--.  ,--.  ,--.
|  |) /_,--.,--|  |-.|  |-.|  |,---.,--.   ,--,--.--.,--,--.,---.
|  .-.  |  ||  | .-. | .-. |  | .-. |  |.'.|  |  .--' ,-.  | .-. |
|  '--' '  ''  | `-' | `-' |  \   --|   .'.   |  |  \ '-'  | '-' '
`------' `----' `---' `---'`--'`----'--'   '--`--'   `--`--|  |-'
                                                           `--'   
```

**Comment by andreban** [comment]
> After running the command, I noticed that ./twa-manifest.json is saved in the current directory instead of the directory I specified --directory='./pwa-android'

This is a bug. The file should have been created at `./pwa-android`

> I encountered this error earlier and it can be fixed by changing my androidSdkPath to /Users/jun/Downloads instead of /Users/jun/Downloads/tools

Unfortunately, unzip the Android command-line tools from the UI ends up unzipping it to the current folder, because the zip file only contains the `/tools` folder. But, as you noticed, the SDK downloads more files and adds them to the same folder level as `tools`. So, I'd recommend unzipping the files to an `android-sdk` folder and pointing to that. 

`licence`, `build-tools`, `platform-tools`, etc are part of the Android command-line tools (and it's that tool that creates them), not the Android project. They are indeed created in the "right" place.

You may be interested in the flow here: https://www.youtube.com/watch?v=QJlbMfW3jPc

**Comment by Jun711** [comment]
thanks @andreban 
I understand the whole process better now.

Sorry for another question,
With the signed apk alone, my colleague should be able to install the app without having to run `bubblewrap build`, right?
He told me he could install it but he couldn't get past the loading page of the app.

Is there any limitation regarding Android version?
