### ISSUE TITLE
[Windows] 'keytool' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ThaDaVos** [GoogleChromeLabs/bubblewrap#250]
**Describe the bug**

When running `bubblewrap init`  it fails with the error: `'keytool' is not recognized as an internal or external command`
I tried in CMD and in Powershell

**To Reproduce**
1. run `bubblewrap init --manifest {MANIFEST}`
2. have no keystore yet, create one when asked
3. See error

**Expected behavior**
I expected it to generate the application

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by ThaDaVos** [comment]
Partial reason was I didn't have the JDK in my path -> but the bubblewrap cli asked for the path to the JDK but it seems not to be used

**Comment by andreban** [comment]
It does use the JDK in the path. Any change the jdk path is pointing to the incorrect folder? There's more info on how to check it here: https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli#updating-the-location-of-the-jdk-and--or-the-android-command-line-tools

Overall, the `doctor` command tracked on #181 and implemented on #220  should make it easier to debug this in the near future.

**Comment by andreban** [comment]
Closing this as the `doctor` command now exists and dependencies can be installed automatically.

**Comment by zamuka** [comment]
I hit this problem while trying to run bubblewrap on windows using gitbash. Even bubblewrap installed JDK fails to run keytool. 
Executing bubblewrap using windows cmd works fine.
