### ISSUE TITLE
"Image exceeds pixel limit" for SVG icon

### ISSUE THREAD

**Issue by JudahGabriel** [GoogleChromeLabs/bubblewrap#258]
I seem to recall that Bubblewrap now properly supports SVG images for app icons. Is this correct? If so, I'm seeing an error in Bubblewrap 1.4.1.

When I specify an SVG file as my app's monochrome icon, Bubblewrap throws the following error:

> Input image exceeds pixel limit

I'm using [this SVG file](https://messianicradio.com/images/chavah-monochrome512x512.svg) as the monochrome icon. If I instead use [this PNG file](https://messianicradio.com/images/chavah-monochrome512x512.png), no error is thrown.

I'm also able to repro this same issue when using an SVG for the app's primary icon.

**Comment by andreban** [comment]
Created #259 to discuss reverting from sharp.

**Comment by andreban** [comment]
This is now obsolete, as we have removed SVG support / sharp via #262. Re-opened #103 for SVG support.
