### ISSUE TITLE
Investigate alternatives for SVG support

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/bubblewrap#260]
The migration to sharp is creating issues and we are planning to revert (see #259). Nevertheless, we still want the SVG support. Investigate the following alternatives:
- [ ] https://www.npmjs.com/package/svg2img
- [ ] ImageMagick

**Comment by lborgman** [comment]
Any time estimate for fixing this?

I was told to ask here in this issue:
https://github.com/pwa-builder/PWABuilder/issues/1009#issuecomment-670008875

**Comment by andreban** [comment]
We're currently looking into it, but it's more of an exploration of existing libraries and their impact at this point.

**Comment by lborgman** [comment]
Thanks for the answer. This problem is kind of blocking for those of us that want to investigate if Bubblewrap Eric is useful for us yet.

**Comment by andreban** [comment]
Is there a specific field that you need to be an SVG and couldn't be a PNG?

**Comment by andreban** [comment]
Closed via #341
