### ISSUE TITLE
Can't build apps with bubblewrap because Android SDK tools won't install

### ISSUE THREAD

**Issue by marsnebulasoup** [GoogleChromeLabs/bubblewrap#266]
When I try to build my app, by running `bubblewrap build`, bubblewrap can't seem to be able to install Android Build Tools, and throws an undefined error instead of building the application:

In CMD:

```
C:\Users\Me\Desktop\app>bubblewrap build
,-----.        ,--.  ,--.  ,--.
|  |) /_,--.,--|  |-.|  |-.|  |,---.,--.   ,--,--.--.,--,--.,---.
|  .-.  |  ||  | .-. | .-. |  | .-. |  |.'.|  |  .--' ,-.  | .-. |
|  '--' '  ''  | `-' | `-' |  \   --|   .'.   |  |  \ '-'  | '-' '
`------' `----' `---' `---'`--'`----'--'   '--`--'   `--`--|  |-'
                                                           `--'
Installing Android Build Tools. Please, read and accept the license agreement
build Installing Build Tools
Error: Could not find or load main class com.android.sdklib.tool.sdkmanager.SdkManagerCli


cli ERROR undefined
```

Here is the structure of the `.bubblewrap` directory in `C:/Users/Me/.bubblewrap`:

```
.bubblewrap/
┣ cmdline-tools/
┃ ┗ tools/
┣ openjdk/
┃ ┣ bin/
┃ ┣ include/
┃ ┣ jre/
┃ ┣ lib/
┃ ┣ sample/
┃ ┣ ASSEMBLY_EXCEPTION
┃ ┣ LICENSE
┃ ┣ release
┃ ┣ src.zip
┃ ┗ THIRD_PARTY_README
┗ config.json
```

And the content of `config.json` within `.bubblewrap`:

```
{
    "jdkPath": "C:/Users/Me/.bubblewrap/openjdk",
    "androidSdkPath": "C:/Users/Me/.bubblewrap/cmdline-tools"
}
```

I am running Windows 10 v2004:
Windows Build Number: 19041.388

Bubblewrap version: 1.4.1

--

I can't seem to figure out what is wrong. Thanks in advance.

**Comment by marsnebulasoup** [comment]
Okay...I have solved the problem by installing an earlier version of Android SDK tools as suggested by @krayanni in [this post ](https://github.com/NativeScript/nativescript-cli/issues/5304#issuecomment-623235449) from a different repo.

> I think latest version '6200805' has some issue, even I got the same problem.
> 
> Solution: Use the older sdkmanager version, please find below links for older version.
> 
> Windows no installer: https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip
> 
> MacOSX: https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip
> 
> Linux: https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip

**Comment by andreban** [comment]
I reported this issue on the Android bugtracker a while ago, it's been fixed but hasn't made it to production yet: https://issuetracker.google.com/issues/154298380

A short fix is unzipping the tools with something like 7-zip instead of the Windows explorer tool.

**Comment by marsnebulasoup** [comment]
I see. Thanks.

**Comment by ankitaivd** [comment]
I am also facing same issue in bubblewrap build in react pwa.
