### ISSUE TITLE
Lock orientation of my TWA to landscape

### ISSUE THREAD

**Issue by MrNeilRobbins** [GoogleChromeLabs/bubblewrap#281]
I need to be able to lock the orientation of my TWA to landscape

**Comment by andreban** [comment]
Support for this has recently added to android-browser-helper: https://github.com/GoogleChrome/android-browser-helper/pull/127 alpha. The change depends on the underlying `androidx.browser` version to become stable, which should happen in a couple of months. Once both libraries are stable we can incorporate that into Bubblewrap.

**Comment by andreban** [comment]
Closed via #390
