### ISSUE TITLE
Share target is not supported

### ISSUE THREAD

**Issue by greyGuy11** [GoogleChromeLabs/bubblewrap#298]
I have got declared share_target in manifest.json. As PWA it works perfectly.
For app generated via bubblewrap it doesn't work.

**Comment by andreban** [comment]
There's work that needs to happen on android-browser-helper before Bubblewrap supports it. You can check progress here: https://github.com/GoogleChrome/android-browser-helper/issues/66

**Comment by andreban** [comment]
Duplicate of #21
