### ISSUE TITLE
Add a "first-run" query parameter optional feature

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/bubblewrap#301]
Add an option feature to Bubblewrap that allows it to append an extra parameter to `launchUrl` when the Trusted Web Activity is running for the first time. The value should be persisted and the parameter not attached / having a different value on the 2nd launch and onwards.

**Comment by PEConn** [comment]
What's the context/use case for this?

**Comment by andreban** [comment]
The idea is allowing the web app to know if it's being opened for the first time, even if the browser local storage is cleaned between runs. Then, the app can take decisions on showing their own 1st run experience based on that.

**Comment by comp615** [comment]
As an added benefit this may enable TWAs to be advertised and referrer off-platform. The current Android native Intent that happens when you install and launch for the first time is generally where attribution is handled. It may be beneficial to pass through the play store referrer param from the intent here too. https://developer.android.com/google/play/installreferrer/library

**Comment by andreban** [comment]
Yes, that's similar to what some analytics libraries do. Example: https://github.com/GoogleChromeLabs/bubblewrap/blob/master/packages/core/src/lib/features/AppsFlyerFeature.ts

**Comment by andreban** [comment]
This is how the implementation could work to append a "first-run" parameter - the parameter name could default to something, but we could allow developers to set any name they'd like. 

```java
public class LauncherActivity
        extends com.google.androidbrowserhelper.trusted.LauncherActivity {

    private static final String KEY_FIRST_OPEN = "bubblewrap.first_open";
    private static final String PARAM_FIRST_OPEN = "firstOpen";

    private boolean checkAndMarkFirstOpen() {
        SharedPreferences preferences = getPreferences(MODE_PRIVATE);
        if (!preferences.getBoolean(KEY_FIRST_OPEN, false)) {
            return false;
        }
        preferences.edit().putBoolean(KEY_FIRST_OPEN, true).apply();
        return true;
    }

    @Override
    protected Uri getLaunchingUrl() {
        // Get the original launch Url.
        Uri uri = super.getLaunchingUrl();

        uri = uri.buildUpon()
                .appendQueryParameter(PARAM_FIRST_OPEN, String.valueOf(checkAndMarkFirstOpen()))
                .build();

        return uri;
    }
}
```

This does not handle https://developer.android.com/google/play/installreferrer/library - the challenge with this particular case is that the call is async and might introduce a larger delay when opening the app. @comp615, how critical is having the install-referrer detail? A couple of alternatives would be:

 1. Delay launching the app until the referrer is received (needs some research on how large the delay is).
 2. Listen for the referrer asynchronously, store it and inject the next time the app is opened (which would be the first open). 
 3. A third option, which is not available for Trusted Web Activity today, would be using `postMessage()` to send the information to the client once it becomes available.

@PEConn for thoughts.

**Comment by PEConn** [comment]
So launching a TWA already relies on an asynchronous connection (connecting to the Custom Tabs Service in the browser), so waiting for the Install Referrer wouldn't require rearchitecting the whole thing (though it probably won't be trivial either).

Your code sample seems fine, but it may trigger a StrictModeViolation. The first time you access SharedPreferences there is a disk read. There's not much we can really do since our logic is on the critical path, but we may want to protect ourselves against having errors thrown.

**Comment by comp615** [comment]
This would not be a blocker for us at the moment (although it would be if we were direct porting our WebView version, but we're simplifying things to ease migration). I think the referrer is a nice to have if possible, but the alternatives and barriers you mention are also valid considerations. One thing that comes to mind (although wouldn't be available for a bit) is the launch event (https://github.com/WICG/sw-launch), where maybe that could be fired async a second time, or the first-launch data could be appended to it so it didn't block loading the URL. In concept this sounds similar to your postMessage option.

**Comment by andreban** [comment]
@PEConn re: StrictMode, this protect from a `StrictModeViolation`. Is this right?

```
    private boolean checkAndMarkFirstOpen() {
        StrictMode.ThreadPolicy originalPolicy = StrictMode.allowThreadDiskReads();
        try {
            SharedPreferences preferences = getPreferences(MODE_PRIVATE);
            if (!preferences.getBoolean(KEY_FIRST_OPEN, true)) {
                return false;
            }
            preferences.edit().putBoolean(KEY_FIRST_OPEN, false).apply();
            return true;
        } finally {
            StrictMode.setThreadPolicy(originalPolicy);
        }
    }
```

**Comment by PEConn** [comment]
Yeah, that should protect against violations.

Do this think this reads better (for the part inside the try block)?

```
SharedPreferences preferences = getPreferences(MODE_PRIVATE);
boolean isFirstRun = preferences.getBoolean(KEY_FIRST_OPEN, true);
preferences.edit().putBoolean(KEY_FIRST_OPEN, false).apply();
return isFirstRun;
```
