### ISSUE TITLE
`doctor` reports AndroidSDK path as invalid before build-tools installation

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/bubblewrap#302]
The command reports an error when the Android Sdk path is configured and correct, but build-tools hasn't been installed yet.

**Steps to reproduce the behavior:**
- Install Bubblewrap and download / unzip the Android SDK
- Configure twa-manifest.json with the correct Android SDK
- Run Bubblewrap

**Expected behavior:**
doctor reports the Android SDK as correctly configured.

**Actual behavior:**
It reports the  Android SDK path is invalid.

**OS:**  MacOS

**Additional context**
`doctor` is checking for the `build-tools` directory, but that's only created / installed after running sdkmanager, which Bubblewrap does automatically. See https://github.com/GoogleChromeLabs/bubblewrap/blob/master/packages/core/src/lib/androidSdk/AndroidSdkTools.ts#L62-L90

@chenlevy24

**Comment by Antoinebr** [comment]
same issue here :/

**Comment by BhautikChudasama** [comment]
Same issue ```cli ERROR The given androidSdk isn't correct.```

**Comment by andreban** [comment]
@Antoinebr @BhautikChudasama could you run `bubblewrap version` and paste the output here?

**Comment by Antoinebr** [comment]
@andreban ```version 1.6.1``` 

##  ~/.bubblewrap/config.json

```
{
    "jdkPath": "/Users/abrossault/Documents/utils/jdk",
    "androidSdkPath": "/Users/abrossault/Documents/utils/android-cli-tool"
}
``` 

## Android SDK 

```ls  /Users/abrossault/Documents/utils/android-cli-tool```

In my android SDK folder I have : 
```NOTICE.txt        bin/               lib/              source.properties/ ```

**Comment by chenlevy24** [comment]
Hi @Antoinebr, your folder might not be the correct sdk folder. Please extract the sdk into a folder and set the path of the sdk to that folder (before build tools installation it should contain only one folder named `tools`). After that run `bubblewrap doctor`again and let me know if there were any problems.

**Comment by andreban** [comment]
@chenlevy24, I think the original issue was already fixed in one of your pull-requests? Could you link it here please?

**Comment by chenlevy24** [comment]
Sure, this is the pull-request which solved the bug:
https://github.com/GoogleChromeLabs/bubblewrap/pull/312

**Comment by BhautikChudasama** [comment]
Here is config.json
```json
{
  "jdkPath":"~/app/jdk8u265-b01/",
  "androidSdkPath":"~/app/android-cli/"
 }
```
Directory structure:
```
| - app
    | - android-cli
        | - tools
    | - jdk8u265-b01
        | ----
```
My Operrating System information
```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
When I run ```bubblewrap doctor```
```
,-----.        ,--.  ,--.  ,--.
|  |) /_,--.,--|  |-.|  |-.|  |,---.,--.   ,--,--.--.,--,--.,---.
|  .-.  |  ||  | .-. | .-. |  | .-. |  |.'.|  |  .--' ,-.  | .-. |
|  '--' '  ''  | `-' | `-' |  \   --|   .'.   |  |  \ '-'  | '-' '
`------' `----' `---' `---'`--'`----'--'   '--`--'   `--`--|  |-'
                                                           `--'    
(node:1065) ExperimentalWarning: The fs.promises API is experimental


doctor ERROR The path given isn't exist.

doctor ERROR The androidSdkPath isn't correct, please run the following command to update it:
bubblewrap updateConfig --androidSdkPath <path-to-sdk>, such that the folder of the path contains the folder "build-tools". Then run bubblewrap doctor again.
```
My ```NodeJS version``` is ```v10.14.2```

**Comment by chenlevy24** [comment]
@BhautikChudasama can you please tell me in which `bubblewrap` version did you run it?

**Comment by andreban** [comment]
@chenlevy24 `validatePath()` [is checking for "tools"](https://github.com/GoogleChromeLabs/bubblewrap/blob/2c7b441d680d900025426d5415eef2441fec0169/packages/core/src/lib/androidSdk/AndroidSdkTools.ts#L214), but the [error message still says "build-tools"](https://github.com/GoogleChromeLabs/bubblewrap/blob/5897ea85c17de49b8a1e22b074598ce0d4dcbe14/packages/cli/src/lib/strings.ts#L266-L268).

There are two errors in @BhautikChudasama's log. The first seems to come from [this code](https://github.com/GoogleChromeLabs/bubblewrap/blob/5897ea85c17de49b8a1e22b074598ce0d4dcbe14/packages/core/src/lib/jdk/JdkHelper.ts#L95-L98), when validating the JDK path.

@BhautikChudasama if you change the JDK path and Android SDK path to an absolute path, instead of relative to the user home, does it change anything?

Eg:
```json
{
  "jdkPath":"/home/BhautikChudasama/app/jdk8u265-b01/",
  "androidSdkPath":"/home/BhautikChudasama//app/android-cli/"
 }
```
