### ISSUE TITLE
build fails with "could not find sdkmanager at Android Studio application path

### ISSUE THREAD

**Issue by rohitattaluri** [GoogleChromeLabs/bubblewrap#304]
**Describe the bug**
I'm trying to build a TWA apk for angular project using BubbleWrap. In the process I'm getting error as shown below.

**Screenshots**
![91197776-5b4a0e00-e719-11ea-8754-738536515af8](https://user-images.githubusercontent.com/59006955/91199391-7453be80-e71b-11ea-9463-1dae25e15441.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser [chrome, Chromium: 85.0.4183.69]
 - Version [10 OS Version 1903 (Build 18362.1016)]

**Additional context**
This is the error I'm getting while running bubblewrap build
I've downloaded and unzipped commandlinetools for android but still its pointing to Android Studio application.

[Reference link](https://developers.google.com/web/android/trusted-web-activity/quick-start#adding-more-keys)

need some help to solve this asap.

**Comment by andreban** [comment]
Hi @rohitattaluri,

It seems you have added the folder to **Android Studio** instead of the **Android command-line tools**. There's more information on where to download the right version [here](https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli#get-the-android-command-line-tools). Then, follow the instructions to update the configuration available [here](https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli#updating-the-location-of-the-jdk-and--or-the-android-command-line-tools).

**Comment by amanintech** [comment]
Looks like Dupe of #147

**Comment by amanintech** [comment]
Fixed as mentioned in #147

**Comment by rohitattaluri** [comment]
Hey, @amanintech, @andreban, 

Apk was built successful. But I can see the url bar for some of the device I installed it.

Can you help me out with this actually?

If possible reach me out at **rohitattaluri@gmail.com**

hope soon I find a solution for this.

**Comment by amanintech** [comment]
@rohitattaluri during the PWA configuration you need to choose the display as standalone

Here is a sample manifest.json used by PWA
```
{
  "short_name": "Twimbit",
  "name": "Twimbit",
  "icons": [
    {
      "src": "twimbit512.png",
      "type": "image/png",
      "sizes": "512x512"
    },
    {
      "src": "twimbit256.png",
      "type": "image/png",
      "sizes": "256x256"
    },
    {
      "src": "twimbit192.png",
      "type": "image/png",
      "sizes": "192x192"
    },
    {
      "src": "twimbit128.png",
      "type": "image/png",
      "sizes": "128x128"
    }
   ],
  "start_url": "https://m.twimbit.com",
  "display": "standalone",
  "scope": "/",
  "theme_color": "#ffffff",
  "background_color": "#ffffff",
  "orientation": "portrait"

}
```

**Comment by rohitattaluri** [comment]
PWA was like the same as you mentioned @amanintech. 

{
  "name": "Andhra Greens",
  "short_name": "Andhra Greens",
  "theme_color": "#eb6b26",
  "background_color": "#eb6b26",
  "display": "standalone",
  "scope": "/",
  "start_url": "/index.html",
  "icons": [
    {
      "src": "assets/icons/icon-72x72.png",
      "sizes": "72x72",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-96x96.png",
      "sizes": "96x96",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-128x128.png",
      "sizes": "128x128",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-144x144.png",
      "sizes": "144x144",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-152x152.png",
      "sizes": "152x152",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-384x384.png",
      "sizes": "384x384",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}

but still idk what exactly failing me to hide url bar in twa apk

**Comment by amanintech** [comment]
needs `triage`

**Comment by andreban** [comment]
This indicates that the Digital Asset Links validation is failing. Taking a look at https://m.twimbit.com/.well-known/assetlinks.json, the content is:

```json
[]
```

Bubblewrap outputs the correct content to an `assetlinks.json`.

**Comment by rohitattaluri** [comment]
@andreban 
![image](https://user-images.githubusercontent.com/59006955/91300283-a8cd8600-e7c0-11ea-8810-94f12d0de9cb.png)
this is the file structure I found after build apk with bubblewrap. I've searched even in app folder for `assetlins.json` didn't find trace of it.

BTW, I've content in the `assetlinks.json` which was hosted along with my website.

Thanks for helping @andreban  @amanintech

**Comment by andreban** [comment]
Can you run `bubblewrap --version` and tell us the output?

**Comment by rohitattaluri** [comment]
![image](https://user-images.githubusercontent.com/59006955/91302266-d23be100-e7c3-11ea-85a9-202dbe8df705.png)

**Comment by andreban** [comment]
Do you remember where you invoked the `build` command from? I think the file is being generated in the local folder instead of inside the project.

**Comment by rohitattaluri** [comment]
I've invoked `build` in the same path where I ran `bubblewrap --version`.

Not only for this project, since morning I've built 3 projects but for no project I find `assetlinks.json` in the project folder.

**Comment by andreban** [comment]
Can you try running `find . -name "assetlinks.json" -print` from `~`? Btw, we have a Slack Channel that can help with debugging this quicker: https://github.com/GoogleChromeLabs/bubblewrap#community

**Comment by rohitattaluri** [comment]
I got the below result @andreban 
![image](https://user-images.githubusercontent.com/59006955/91345987-d97fe080-e7fd-11ea-8266-07ad823d27b2.png)

but none of the resulted paths are generated using **bubblewrap** up to my knowledge

as you suggested I've to the slack community.

**Comment by rohitattaluri** [comment]
In gitBash I'm not able to get **assetlinks.json** as @andreban  suggested tried unning `bubblewrap build` in windows power shell and it got added.

cheers to @andreban  @amanintech
