### ISSUE TITLE
Playstore Rejects my PWA. Please Help

### ISSUE THREAD

**Issue by mcmultimedia** [GoogleChromeLabs/bubblewrap#307]
Thanks bubble Wrap for you doing for the world. I got here through Gabriel from PWA Builder. I need help fixing issues why Playstore rejects my PWA and he suggested I talk to if you can take a look at my link to see if I have done something wrong. Please this is what he sent me.

 Judah Gabriel Himango <notifications@github.com>

Here's my feedback:

It looks like you have a real progressive web app, you use responsive design and have a generally good mobile experience. You have a service worker and your app works offline.

You could likely improve your app manifest ...........You should not likely have your contact information in the top-most UI of the page.

I'd recommend fixing those issues and trying again to submit to the store. You may also wish to talk to the Google Bubblewrap guys - they may have additional feedback on whether your web app is a fit for the Google Play Store.

Hope this helps.

please my link is www.dkidzafrica.com. I really will appreciate this support

**Comment by andreban** [comment]
Applications [need to comply](https://web.dev/using-a-pwa-in-your-android-app/#quality-criteria) with the Play Store [policies](https://play.google.com/about/developer-content-policy/). Is there a change your app is targeting kids? In this case, [additional policies](https://support.google.com/googleplay/android-developer/topic/9877766) apply, and PWA are incompatible. There's more information on this thread: https://github.com/GoogleChromeLabs/svgomg-twa/issues/67

**Comment by mcmultimedia** [comment]
Okay here is the thing. My application is designed to target ages 13 and above. is that okay for PWA's. if yes. then I think playstore must pass my app. please help me.

**Comment by andreban** [comment]
What does the Play Store rejection message say?

**Comment by mcmultimedia** [comment]
After review, your app has been rejected and wasn't published due to a policy violation. If you submitted an update, the previous version of your app is still available on Google Play. However, the previous version of your app may be subject to removal if you do not resolve the issue outlined below.


Issue: Violation of Families Policy Requirements
--
Apps that contain elements that appeal to children must comply with all Families Policy Requirements. We found the following issue(s) with your app:


Version(s)  APK:1

| Eligibility Issue:  Webviews

We don’t allow apps whose primary purpose is to provide a Webview of a website, regardless of ownership. To resolve this issue, please remove violating content and resubmit your app.

**Comment by andreban** [comment]
On the Play Store dashboard, check "App Content" > "Target audience and content". Make sure you are not including children.

**Comment by mcmultimedia** [comment]
ok Will try again please and revert with any feedback they might send me.

**Comment by mcmultimedia** [comment]
BubbleWrap I'm feeling like Oh My God! Playstore passed the app. Special mention to  Gabriel for the help you guys Rock! And thanks for powering our dreams. Now Am going for customizations for the next update.
