### ISSUE TITLE
How to Configure PWA device Permission

### ISSUE THREAD

**Issue by mcmultimedia** [GoogleChromeLabs/bubblewrap#308]
Dear BubbleWrap, Please how do I configure my PWA to inform users about the permissions they need to grant access to before installing my apk on their device. currently my generated apk just installs without any of such. How do I include it?

**Comment by andreban** [comment]
Is there any specific permission you are looking for?

**Comment by mcmultimedia** [comment]
yes. like this device will have access to send you push notifications, Access to connect to accounts, find accounts on the device, use accounts on the device, full netwoprk access, view network connections, run at startup,

**Comment by rafaeldev** [comment]
I think so which device permission is needed only on native apps.
For PWA, you will need to get user permission using browser-skills.

Look at this example for notification using "web push notification": https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission

**Comment by andreban** [comment]
With the latest Bubblewrap version, notification delegation should be enabled by default. The permission is requested using regular web APIs, as @rafaeldev pointed out.
