### ISSUE TITLE
Creating with config

### ISSUE THREAD

**Issue by konstantin-lysenko** [GoogleChromeLabs/bubblewrap#340]
Dear Bubblewrap, it would be really nice if we could pass the flow with a config (.json for example) to avoid manual work. Thank you!

**Comment by andreban** [comment]
Can you expand on this - do you mean the `init` flow?

**Comment by konstantin-lysenko** [comment]
> Can you expand on this - do you mean the `init` flow?

Yes! 
1. Avoid answering "yes" to confirm the data from web-manifest.
2. Avoid manually entering info for a key.

So, It would be great to create some flag, like "init --config ./config.json". And config.json contains configuration like that:
`
{
    manifest: "https://example.com/manifest.json",
    key: {
        password: "111111",
        path: "./"   
    },
    companyName: "Co",
}
`

**Comment by andreban** [comment]
Can you tell me more about the use-case? 

One thing that's already possible is generating a `twa-manifest.json` and invoking `bubblewrap update`. I wonder if this is something that could help with your use-case.

**Comment by konstantin-lysenko** [comment]
The use-case is to replace the flow on UI with some form and server that will create all files automatically based on data from the form. The result is that a user able to enter data, send the form and download generated, signed, and prepared for uploading to Google Play files, the key also.

**Comment by andreban** [comment]
For this use-case, it sounds like using `@bubblewrap/core` directly might be better. This is what [CloudAPK](https://github.com/pwa-builder/CloudAPK/), which powers [PWA Builder](https://pwabuilder.com/) does.

**Comment by konstantin-lysenko** [comment]
> For this use-case, it sounds like using `@bubblewrap/core` directly might be better. This is what [CloudAPK](https://github.com/pwa-builder/CloudAPK/), which powers [PWA Builder](https://pwabuilder.com/) does.

Thank you very much! Seems like CloudAPK is that I need. I tried to use @bubblewrap\core but I didn't find any documentation or a tutorial on how to use it.

Have a nice day!

**Comment by andreban** [comment]
@konstantin-lysenko thanks for the feedback. You are right, we've been focusing on the CLI side and don't have docs for the core module at the moment. Happy to help with any questions you may have though.

@JudahGabriel @jgw96 @davrous FYI (re: CloudAPK)
