### ISSUE TITLE
Issues with push notifications when using Firefox as the default browser

### ISSUE THREAD

**Issue by FLKWSKI** [GoogleChromeLabs/bubblewrap#353]
**Describe the bug**
When Firefox is used as the default browser on a device, the TWA will be opened in Firefox. This leads to multiple issues related to push notifications. 

**To Reproduce**
1. Install Firefox from the Play Store
2. Set Firefox as your default browser in your settings (`Apps and notifications` > `Firefox` > `Browser App`  > `Choose Firefox`)
3. Create and install a bubblewrap TWA that accesses a PWA that utilizes web push notifications.
4. Open the app, make sure that digital asset linking was successful.
5. Subscribe to web push notifications.
6. Receive a notification with a click handler that opens the URL of your PWA.

**Expected behavior**

1. When I subscribe to web push notification, I do not get asked if I want to allow notifications. It should be allowed by default.
2. When I receive a notification, it will have the monochrome app icon and will open the TWA when I click on it.

**Actual behavior**

1. Firefox asks me for confirmation if I want to give the site permissions to send me notifications.
2. The notification has the firefox icon and does not open the TWA. It only opens firefox.

**Smartphone**
 - Device: Google Pixel 3a
 - OS: Android 10 & Android 11
 - Browser: Firefox for Android, 81.1.1

**Additional context**
If necessary, I can supply more information, an example application or screenshots. It should be not hard to reproduce though.

The main issue here is that firefox is used instead of chrome. I suspect that FF has a different / incomplete API that leads to issues with advanced features like push notifications. 
If it would be possible to force the TWA to use chrome, no matter what browser is set as default on the system, it would solve this and other issues. I have not tested it with other browsers or other features than push notifications. 

To be honest, I am not sure if it is possible to fix this problem, or if I have to wait for the other browser vendors to catch up with chrome.

**Comment by andreban** [comment]
Hey @FLKWSKI,

This does look indeed related to the Firefox implementation. @NotWoods might know the best place to file an issue.

Generally, we want to avoid applications hard-coding as specific browser and ensure we're respecting the user's choice of engine. 

@PEConn do you know if have Feature Discoverability enabled for Notification Delegation? It might make sense filter/sort TWA providers by this when picking a provider.

**Comment by FLKWSKI** [comment]
Thank you for your response @andreban.
I totally understand that you don't want to make such changes to your library.

But would it be theoretically possible to manually lock the browser engine in the generated bubblewrap application? If yes, could you give me a hint how to achieve that? I would like to try to do it myself, unfortunately I am not very experienced with android app development.

**Comment by PEConn** [comment]
Unfortunately there's no easy way to do that at the moment. I have a [PR out](https://github.com/GoogleChrome/android-browser-helper/pull/196) to make it customizable, but we need to give some more care to what happens if the specified browser isn't installed.

**Comment by NotWoods** [comment]
I'd also recommend you file an issue in the https://github.com/mozilla-mobile/fenix repo.

**Comment by andreban** [comment]
Closing this, as this is outside the scope of Bubblewrap.
