### ISSUE TITLE
How to add more than one website?

### ISSUE THREAD

**Issue by suyashmohan** [GoogleChromeLabs/bubblewrap#380]
I have successfully created project with a domain for e.g. `example1.com`. Everything works fine. But the moment app refers to `example2.com`, navigation bar appears for it. `example2.com` already has `.well-know/assetlinks.json` setup just like example1.com.

example1.com was already provided while created the project with bubblewrap cli. 
So, how can I add multiple domains/websites so that navigation bar doesn't appear for them, provided assetlinks.json is setup for those domains/websites. 

I also tried updating build.gradle, but didn't helped
```
         resValue "string", "assetStatements",
                 '[{ \\"relation\\": [\\"delegate_permission/common.handle_all_urls\\"],' +
                         '\\"target\\": {\\"namespace\\": \\"web\\", \\"site\\": \\"https://' +
                        twaManifest.hostName + '\\"}},' +
                '{ \\"relation\\": [\\"delegate_permission/common.handle_all_urls\\"],' +
                        '\\"target\\": {\\"namespace\\": \\"web\\", \\"site\\": \\"https://' +
                        'www.example2.com' + '\\"}}]'
```

**Comment by andreban** [comment]
This is not directly supported by Bubblewrap. You'll need to setup `build.gradle` and `LauncherActivity`. Check the guide here: https://developers.google.com/web/android/trusted-web-activity/multi-origin
