### ISSUE TITLE
Push notification open chrome instead of app

### ISSUE THREAD

**Issue by BenDuh** [GoogleChromeLabs/bubblewrap#386]
Hi, 

I'm working on a TWA push notification integration and my click event from service worker open Chrome instead of twa. is my code correct ? 

```self.addEventListener("notificationclick", function (event) {
event.notification.close();
    event.waitUntil(
      clients
        .matchAll({
          type: "window",
        })
        .then(function (clientList) {
          for (var i = 0; i < clientList.length; i++) {
            var client = clientList[i];
            if (client.url == "/" && "focus" in client) return client.focus();
          }
          if (clients.openWindow) {
            return clients.openWindow("/");
          }
        })
    );
  });
```

I didn't setup the digital links for the moment, is the reason of that or i have to change my service worker ?

**Comment by FLKWSKI** [comment]
I think your code probably should be fine, but I believe you need to set up digital asset links so the TWA will be the preferred activity.

**Comment by BenDuh** [comment]
That means asset links allows redirect push notification to the TWA ? If its the case, is not mentionned on the documentation.

**Comment by andreban** [comment]
Content in a Trusted Web activity is trusted - the app and the site it opens are expected to come from the same developer and this is verified using Digital Asset Links. So, if you don't have a valid Digital Asset Links, the app is not a proper TWA and Notification Delegation won't work.

**Comment by FLKWSKI** [comment]
I believe that a successfull digital asset link verification allows the app to handle supported URLs ( = your app URL ) without asking. There is no redirects. Your app will just be opened by default when you open the supported URL.

This is described [here](https://developer.android.com/training/app-links/verify-site-associations).

But as I already said, I am not 100% sure about this. I am not an android developer.
That is just how I fixed this problem in my application.
