### ISSUE TITLE
Does "Let Google manage my app signing key" invalidate the asset links generated by Bubblewrap?

### ISSUE THREAD

**Issue by JudahGabriel** [GoogleChromeLabs/bubblewrap#389]
Hey guys,

Based on [this question from a PWABuilder user](https://github.com/pwa-builder/PWABuilder/issues/1197), I'd like some clarity on how Bubblewrap's asset links interact with the Play Store.

When I upload an app to the Play store, I'm asked the following:

![Play Store signing prompt](https://raw.githubusercontent.com/pwa-builder/CloudAPK/master/static/opt-out-google-play.png)

I assumed we should "opt out" here because otherwise the asset links generated by Bubblewrap would become invalid; the Store would re-sign your app.

However, if we opt out, we get an error, "You won't be able to use Android App Bundles to publish your app. App bundles reduce app size, and automatically optimize your app for each device." 😟

Can you clarify: **if we choose the recommended "Let Google create and manage my app signing key", will the asset links generated by Bubblewrap become invalid?**

**Comment by andreban** [comment]
Hi Judah, 

Yes, the `assetlinks.json` generated by Bubblewrap becomes invalid. This is documented [here](https://developers.google.com/web/android/trusted-web-activity/quick-start#play-store-signing). I'd recommend to opt-in into Play Signing.

Andre

**Comment by JudahGabriel** [comment]
Bummer. I wish opting out of Play Signing didn't block app bundles, as this present another hurdle for devs.

Thanks for the clarification.
