### ISSUE TITLE
Decide on Quality Criteria for Trusted Web Activities

### ISSUE THREAD

**Issue by PEConn** [GoogleChromeLabs/bubblewrap#393]
At the moment bubblewrap gives a warning if the given website falls below a Lighthouse score of 80.

This issue can be used as a place to discuss that criteria and help decide if it is useful/sufficient or whether we should do something more/else.

**Comment by andreban** [comment]
CC @b1tr0t
Also CC @davrous @JudahGabriel @jgw96, for PWA Builder's team perspective.

**Comment by b1tr0t** [comment]
I think I'd prefer to drop the LH criteria in favour of triggering an ANR crash when the main thread is blocked for some duration (probably 5 seconds).  I think this will better align to the behaviour of other Android apps.

**Comment by JudahGabriel** [comment]
Crashing on 404 feels extreme to me. 

However, it would certainly weed out a lot of low-quality PWAs and encourage devs to build a good service worker (or use an existing one from Workbox). FWIW, the trend we're seeing on major sites is good adoption of manifest, but very small adoption of service worker. They're hard to get right. So, having a quality criteria on service worker offline support is indeed a bar many aren't reaching today.

I like b1tr0t's idea of long thread block block = crash.

**Comment by JudahGabriel** [comment]
FYI, we're investigating integrating Lighthouse into PWABuilder to encourage higher quality PWAs.

**Comment by andreban** [comment]
Regarding the performance score, it sounds to me we should try aligning the performance requirement with Core Web Vitals as well.

**Comment by andreban** [comment]
Closing as stale, as the quality criteria no longer applies
