### ISSUE TITLE
failed to setup JDK on the first run without config folder

### ISSUE THREAD

**Issue by dkocich** [GoogleChromeLabs/bubblewrap#400]
**Describe the bug**
I used `bubblewrap --init <URL>` but the project was not able to install JDK. It says
`cli ERROR ENOENT: no such file or directory, mkdir '/home/david/.bubblewrap/jdk'` 
After I created `.bubblewrap` directory manually, it was able to create JDK folder itself and download JDK.  

**Expected behavior**
It should not be required to create a `home/<user>/.bubblewrap` folder manually.

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04

**Comment by andreban** [comment]
This should have already been fixed via #375. Can you check if this is reproducible with [1.8.0-alpha.1](https://www.npmjs.com/package/@bubblewrap/cli/v/1.8.0-alpha.1)?

**Comment by AlexDev404** [comment]
@andreban This has happened to me too on the latest version of the Bubblewrap cli. I had to go and create the `.bubblewrap` folder myself for it to work.

**Comment by andreban** [comment]
This should be fixed. Please, re-open if still reproducible in a recent Bubblewrap version.
