### ISSUE TITLE
Play Billing requires enableNotifications to be true.

### ISSUE THREAD

**Issue by PEConn** [GoogleChromeLabs/bubblewrap#411]
The Play Billing plugin requires enableNotifications to be true to work. This is because enableNotifications is required for the DelegationService to be enabled.

We have a few options:

1. Make playbilling=true imply enableNotifications=true.
2. Make playbilling=true not build if enableNotifications=false.
3. Make playbilling=true include DelegationService as well.

The confusing thing with option 3 is that the presence DelegationService implies enableNotifications=true, so it's essentially the same as option 1.

We also have option...

4. Always include the DelegationService (essentially setting enableNotifications=true for everyone), and remove enableNotifications.

Related is PR #409 .

**Comment by rwolski** [comment]
Should this flag also be added to the init billing prompt introduced in https://github.com/GoogleChromeLabs/bubblewrap/pull/438? I've recently spent a while troubleshooting a clientAppUnavailable error until discovering that alphaDependencies and enableNotifications is required.

**Comment by andreban** [comment]
#409 changed the default to `enableNotifications=true` for all cases. #438 introduced the billing prompt and enables `alphaDependencies`. `init` should have everything set correctly when billing is enabled.

**Comment by joycetoh8** [comment]
#511 added some more checks in `update` to ensure that when Play Billing is enabled, `enableNotifications` and `alphaDependencies` are also enabled/true. Do we think this issue can be closed now?

**Comment by andreban** [comment]
Yes, SGTM

**Comment by andreban** [comment]
Closed via #511
