### ISSUE TITLE
Can't build apk in standalone or fullscreen mode

### ISSUE THREAD

**Issue by dersar00** [GoogleChromeLabs/bubblewrap#423]
Hi there!
Decided add PWA support to my current app, started with investigation how to generate an apk from pwa. After some research I realized that `bubblewrap` is the most often used tool for this. I wrote a simple pwa application and tried to convert it to apk, but for some reason my app displaying in `minimal-ui` display mode. In my `manifest.json` file and during `bubblewrap init` I set display mode to `standalone`. If I'm trying to add the app to my device home screen from web browser, everything works as expected.

I thought that maybe I did something wrong, then found a [video](https://www.youtube.com/watch?v=QJlbMfW3jPc) on official google chrome dev youtube channel, pulled the app source code and tried to convert to apk the same way as in the video, but got the same result again.

**Expected behavior**
After installation the app looks in a way I set up.

**Screenshots**
![image](https://user-images.githubusercontent.com/17855733/101466486-df7f7480-3949-11eb-9247-af773d19cd02.png)

**Bubblewrap CLI**
- Version: 6.14.5

**Desktop**
 - OS: MacOS Mojave v. 10.14.6
 - Browser: Chrome
 - Version 86.0.4240.198

**Smartphone**
 - Device: Pixel 3a
 - OS: android 11
 - Browser: Chrome 
 - Version 83.0.41.03.106

**Comment by andreban** [comment]
It seems Digital Asset Links is configured correctly. Have you gone through the instructions [here ](https://developers.google.com/web/android/trusted-web-activity/quick-start#creating-your-asset-link-file). This [video](https://www.youtube.com/watch?v=3bAQPnxLd4c&feature=youtu.be) may help too.

If after going over those, this is still a problem, would you be able to share the APK so I can check out what is wrong?

**Comment by dersar00** [comment]
@andreban Still having the issue, here is my apk.
[app-release-signed.apk.zip](https://github.com/GoogleChromeLabs/bubblewrap/files/5660389/app-release-signed.apk.zip)

**Comment by andreban** [comment]
Your app tries to open https://56e59913affe.ngrok.io/. When I try opening assetlinks.json at https://56e59913affe.ngrok.io/.well-known/assetlinks.json, the application renders the login screen instead of the assetlinks file, so the browser is unable to verify.

**Comment by dersar00** [comment]
You are right, but even after the `assetlinks.json` is available from `.well-known` directory it works the same way in minimal-ui display mode.
When you're trying to help me with this problem keep in mind that if I'm adding the app to the home screen on any device(ios, android) directly it's displaying correctly, so probably the pwa work well and the problem appears only when I'm trying to install it using apk. 
[app-release-signed.apk.zip](https://github.com/GoogleChromeLabs/bubblewrap/files/5666333/app-release-signed.apk.zip)

**Comment by andreban** [comment]
@dersar00 have you managed to get the app working? I still can't see the contents of assetlinks.json.

**Comment by jahvi** [comment]
I'm having the same problem, I can also confirm I have set display `fullscreen` in both `manifest.json` and `twa-manifest.json` and my app looks like the screenshot in the issue but only when installed as an apk.

Same issue using `pwabuilder.com`.

When adding to the home screen directly it works as expected.

**Comment by andreban** [comment]
The issue seems to be that the OP doesn't have an assetlinks file configured properly at https://56e59913affe.ngrok.io/.well-known/assetlinks.json. This video shows the steps to configure it: https://www.youtube.com/watch?v=3bAQPnxLd4c

Closing the issue as it's not related to Bubblewrap.
