### ISSUE TITLE
Setting up loop

### ISSUE THREAD

**Issue by cxspxr** [GoogleChromeLabs/bubblewrap#428]
**Describe the bug**
bubblewrap-cli is trying to set up things forever, sometimes suggesting to install sdk, sometimes not

**To Reproduce**
1. `$ npm i -g @bubblewrap/cli`
2. `$ bubblewrap`
3. Accept installing jdk 8 prompt
4. Decline installing sdk 29 prompt
5. Try to choose existing sdk 30 from Android Studio, see the error, hit `ctrl + c`
6. `$ bubblewrap` 
7. Accept installing jdk 8 prompt again
8. Accept installing sdk 29 prompt
9. `$ bubblewrap`
10. See the jdk prompt or both prompts again (from time to time)
11. `$ bubblewrap init`
12. See the jdk prompt or both prompts again (from time to time), and nothing being initialized

**Expected behavior**
If the choosing existing sdk prompt fails it should let you accept installing it next time without failures and endless loop of prompts.

**How I managed to make it work**
`$ npm un -g @bubblewrap/cli`
`$ rm -r ~/.bubblewrap`
`$ npm i -g @bubblewrap/cli`
Accept both install prompts

**Desktop (please complete the following information):**
 - OS: Linux 5.8.13-arch1-1, ArchLinux

**Comment by PEConn** [comment]
Andre, do you mind having a look at this?
