### ISSUE TITLE
Run Lighthouse in Desktop mode for Chrome OS Only

### ISSUE THREAD

**Issue by Snugug** [GoogleChromeLabs/bubblewrap#437]
Currently working with a partner, their builds appear to be failing due to PWA Quality Criteria checks failing. Testing out their site, it looks like they do `m.` redirection, but their mobile site isn't a PWA, only their desktop site is. Because we know that Chrome OS Only will build a TWA that only is meant to work on desktops, when Lighthouse runs, it should do so in Desktop mode, not Mobile mode, to better reflect the actual experience users will have and prevent issues like this.

**Comment by andreban** [comment]
Closing as stale, Quality Criterial no longer applies.
