### ISSUE TITLE
Webauthn biometrics background colour

### ISSUE THREAD

**Issue by JohnRSim** [GoogleChromeLabs/bubblewrap#442]
**Is your feature request related to a problem? Please describe.**
Samsung devices use Knox security and overide default Android behaviour with Auth and biometrics. As part of this when the displays appears the background is black so you can no longer see the app behind the biometrics overlay.  I've seen in Cordova apps and native apps that they can change this default behaviour and have a semi transparent background overlay on the app. I don't believe this is achievable with web/pwa and so may be out of scope to be supported.

**Describe the solution you'd like**
Webauthn configuration within the manifest to allow users to enable support for semi transparent background overlay. The reason for the ask is that when users taps the app they get the login screen and then black background with biometrics would be nice to see context of the app.

**Describe alternatives you've considered**
N/A

**Additional context**
Cordova app
 ![Screenshot_20210120-084343_Smartr.jpg](https://user-images.githubusercontent.com/364208/105149670-b2eb7a80-5afb-11eb-83c8-bbffb46c65c1.jpg)

TWA/PWA/WEB
![Screenshot_20210120-084321_Settings.jpg](https://user-images.githubusercontent.com/364208/105149696-bb43b580-5afb-11eb-9c5f-08d09097a33a.jpg)

**Comment by JohnRSim** [comment]
Also wanted to clarify the Cordova version uses a plugin not webauthn

**Comment by andreban** [comment]
@JohnRSim thanks for filing this.

A few follow-up questions that might help routing the issue to the right people:
- Can you confirm which browser is being used to handle the TWA (eg: Chrome, Samsung Internet, etc). 
- What is the behaviour when the application is used in the standalone mode? Is the background black as well?
- What is the behaviour when the application is installed using add-to-homescreen? Is the background black as well?

**Comment by JohnRSim** [comment]
Chrome Android - 88.0.4324.93
Standalone - black BG
PWA add-to-homescreen - black BG

**Comment by andreban** [comment]
It sounds like we should create a bug on https://crbug.com/ for this. Can you confirm if this is an issue with Samsung + Knox only?

**Comment by JohnRSim** [comment]
Sure let me test with my other devices tomorrow and will feed back.

**Comment by andreban** [comment]
Closing this issue here, as it's related to the browser side implementation and there's nothing that can be done in Bubblewrap to fix.
