### ISSUE TITLE
Offline mode access

### ISSUE THREAD

**Issue by JohnRSim** [GoogleChromeLabs/bubblewrap#444]
**Describe the bug**
When offline and accessing the TWA app after the splash screen it shows app is offline and then redirects to a white screen.. when I connect to the internet a message below appears asking to reload page and then the site is shown in the TWA. If I access a PWA or website in chrome offline mode appears to work fine. Using workbox 5 library behind the scenes. 

**To Reproduce**
1. Setup workbox with svelte test behaviour as pwa and web confirm offline mode works.
2 build TWA
3 open TWA preview page
4 close TWA
5 go into offline mode disable connection
6 launch TWA

**Expected behavior**
Offline mode in app does not appear to work as expected.
I'll look into this closer as it may be an issue with my setup and not a bug - but appears fine for web and pwa.

**Screenshots**
https://user-images.githubusercontent.com/364208/105190118-99632680-5b2d-11eb-9650-7978a68b494b.mp4

 - 

**Smartphone (please complete the following information):**
 - android 10 s9 chrome

**Additional context**
Running on @bubblewrap/cli@1.8.1

**Comment by JohnRSim** [comment]
Hmm might be my issue - noticed 
start_url does not respond with a 200 when offline. I'll check this.

**Comment by JohnRSim** [comment]
For future ref and anyone else who comes across this and having a similar issue.
In my manifest I had updated 
```
"startUrl": "/?source=twa",
```

but in my service worker code I had not added the path to allowlist although '/' was there.. 
So when it was offline and trying to access `/?source=twa` workbox would not redirect and let me access the path.

![image](https://user-images.githubusercontent.com/364208/105389356-a7897380-5c0f-11eb-89eb-4d6411f9ccac.png)

**Comment by andreban** [comment]
Thanks for checking this out @JohnRSim. It seems you are using Workbox - is this feedback that would be useful to them?

**Comment by JohnRSim** [comment]
On investigation it's more Svelte/Sapper issue - I will report to them as the pattern for the / route is not correctly defined.
Workbox 5.x side of things everything is working as it should - haven't upgraded to 6.x yet.
