### ISSUE TITLE
Extra colon and space in assetlinks.json

### ISSUE THREAD

**Issue by cdreydemy-vp** [GoogleChromeLabs/bubblewrap#446]
Hi everyone
First of all, I would like to thank you for this great tool!

**Describe the bug**
When I run `bubblewrap build --skipPwaValidation`, it generates the `assetlinks.json` file well, but it adds a colon followed by a space at the beginning of the `sha256_cert_fingerprints`.
I have to remove it manually, otherwise the correspondence between the application and assetlinks is not ok.

**Output example:**
`"sha256_cert_fingerprints": [": 85:A0...`

**Expected output example:**
`"sha256_cert_fingerprints": ["85:A0...`

**Steps to reproduce:**
- `bubblewrap init --manifest=https://thewebsite`
- `bubblewrap build --skipPwaValidation`

**Environment**
- macOS Mojave version 10.14.5.
- @bubblewrap/cli@1.8.2
- node v10.20.0
- `"jdkPath":"/Users/username/.bubblewrap/jdk/jdk8u265-b01"`
- `"androidSdkPath":"/Users/username/.bubblewrap/android_sdk"`

**Comment by andreban** [comment]
I can't repro this, with or without `--skipPwaValidation`. Does this happen every time build is invoked?

**Comment by cdreydemy-vp** [comment]
Yes, every time. I fixed it manually, and Bubblewrap overwrite it at every build.

**Comment by andreban** [comment]
Sounds like something is going wrong when [parsing the output from `keytool`](https://github.com/GoogleChromeLabs/bubblewrap/blob/9ea331ce5e5257985d6af6eed55a7972d2241c19/packages/core/src/lib/jdk/KeyTool.ts#L138-L157). I'd need to see the raw output to understand what's going on. Could you run the following command on your computer and let me know what the output looks like (replace the values with info from your keystore):

```
keytool -list -v -keystore "<path-to-keystore>" -alias "<your-alias>" -storepass "<storepassword>" -keypass "<keypassword>"
```

**Comment by cdreydemy-vp** [comment]
`bubblewrap init --manifest=https://github.com/manifest.json (with new key store)`
`bubblewrap build --skipPwaValidation`

**Output:**
```
[{
      "relation": ["delegate_permission/common.handle_all_urls"],
      "target" : { "namespace": "android_app", "package_name": "com.github.twa",
                   "sha256_cert_fingerprints": [": 9D:BE:B0:8F:32:49:BC:71:EA:52:29:E2:41:29:20:23:51:99:97:D4:5B:72:04:B8:F5:24:CC:F0:AC:35:80:D8"] }
    }]
```

`keytool -list -v -keystore android.keystore -alias "android" -storepass "github" -keypass "github"`

**Output:**
```
Nom d'alias : android
Date de création : 25 janv. 2021
Type d'entrée : PrivateKeyEntry
Longueur de chaîne du certificat : 1
Certificat[1]:
Propriétaire : CN=Chris D, OU=CDR, O=CDR, C=FR
Emetteur : CN=Chris D, OU=CDR, O=CDR, C=FR
Numéro de série : 763b586e
Valide du : Mon Jan 25 15:55:35 CET 2021 au : Tue Oct 29 15:55:35 CET 2075
Empreintes du certificat :
	 MD5 : 8B:71:C2:D7:68:B0:E1:E3:C5:A9:13:A0:D0:C5:F7:B2
	 SHA1 : 18:C6:12:F5:43:34:B4:E7:BF:31:11:ED:99:11:14:9E:56:1E:ED:F7
	 SHA256 : 9D:BE:B0:8F:32:49:BC:71:EA:52:29:E2:41:29:20:23:51:99:97:D4:5B:72:04:B8:F5:24:CC:F0:AC:35:80:D8
Nom de l'algorithme de signature : SHA256withRSA
Algorithme de clé publique du sujet : Clé RSA 2048 bits
Version : 3

Extensions :

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: EA 7B 9E DE AF 67 9C D8   CC 6B A9 AD D9 19 BE 7E  .....g...k......
0010: 3E DD 17 7F                                        >...
]
]


Warning:
Le fichier de clés JKS utilise un format propriétaire. Il est recommandé de migrer vers PKCS12, qui est un format standard de l'industrie en utilisant "keytool -importkeystore -srckeystore android.keystore -destkeystore android.keystore -deststoretype pkcs12".
```

**Comment by andreban** [comment]
Thanks for this information. It seems the keys are formatted in a slightly different way depending on the locale:

Here's how we expect it to look like:
```
Certificate fingerprints:
   SHA1: 18:C6:12:F5:43:34:B4:E7:BF:31:11:ED:99:11:14:9E:56:1E:ED:F7
   SHA256: 9D:BE:B0:8F:32:49:BC:71:EA:52:29:E2:41:29:20:23:51:99:97:D4:5B:72:04:B8:F5:24:CC:F0:AC:35:80:D8
```

But there's an extra space before the colon: 
```
Empreintes du certificat :
	 MD5 : 8B:71:C2:D7:68:B0:E1:E3:C5:A9:13:A0:D0:C5:F7:B2
	 SHA1 : 18:C6:12:F5:43:34:B4:E7:BF:31:11:ED:99:11:14:9E:56:1E:ED:F7
	 SHA256 : 9D:BE:B0:8F:32:49:BC:71:EA:52:29:E2:41:29:20:23:51:99:97:D4:5B:72:04:B8:F5:24:CC:F0:AC:35:80:D8
```

Since this is internal (and other locales may be formatted differently), I'm thinking a good solution may be to force the locale to `en_US` when invoking the command.

**Comment by cdreydemy-vp** [comment]
Indeed, in French a space is required before the colon, unlike in English / German.
So yes I agree, forcing the locale is a good idea 👍

**Comment by cdreydemy-vp** [comment]
Or a regex instead of the [substring](https://github.com/GoogleChromeLabs/bubblewrap/blob/9ea331ce5e5257985d6af6eed55a7972d2241c19/packages/core/src/lib/jdk/KeyTool.ts#L149).
Something like `line.match(/:\s?(.*)/)[1]`

**Comment by andreban** [comment]
A regex would work for French, but I'm wondering if we can get quirks from other locales that we don't know about.

This would do the trick:
```
keytool -J-Duser.language=en -list -v -keystore android.keystore -alias "android" -storepass "github" -keypass "github"
```

**Comment by cdreydemy-vp** [comment]
Yes it would

**New output:**
```
Certificate fingerprints:
	 MD5:  8B:71:C2:D7:68:B0:E1:E3:C5:A9:13:A0:D0:C5:F7:B2
	 SHA1: 18:C6:12:F5:43:34:B4:E7:BF:31:11:ED:99:11:14:9E:56:1E:ED:F7
	 SHA256: 9D:BE:B0:8F:32:49:BC:71:EA:52:29:E2:41:29:20:23:51:99:97:D4:5B:72:04:B8:F5:24:CC:F0:AC:35:80:D8
```

**Comment by andreban** [comment]
Bubblewrap CLI 1.9.0 has been release with this fix.
