### ISSUE TITLE
Adding share target results in Gradle exception

### ISSUE THREAD

**Issue by JudahGabriel** [GoogleChromeLabs/bubblewrap#448]
On Bubblewrap 1.8.2, is share target really supported? I see it in `TwaManifest.shareTarget`, but if I try to use it, it breaks.

Specifically, if I create a `TwaManifest` with the following `shareTarget`, Bubblewrap will fail to generate the package.

```typescript
const manifest: TwaManifest = {
   "host": "mathbymiles.com",
   "shareTarget": {
         "action":"/new-topic",
         "method":"GET",
         "enctype":"application/x-www-form-urlencoded",
         "params": {
              "title":"title",
              "text":"body"
          }
   },
   ...omitted for brevity
}
```

If I try to build the package, I receive the following error:

> Details: Error generating app package: Error: Command failed: ./gradlew assembleRelease --stacktrace
> FAILURE: Build failed with an exception.
>
> What went wrong:
> Execution failed for task ':app:generateReleaseBuildConfig'.
> Manifest file does not exist: /tmp/pwabuilder-cloudapk--36-B2nqEkzP1ZR3/app/src/main/AndroidManifest.xml

This error was originally reported to PWABuilder [here](https://github.com/pwa-builder/PWABuilder/issues/1386). Others are experiencing the same issue with different URLs, e.g. https://github.com/pwa-builder/PWABuilder/issues/1215#issuecomment-758593296.

**Comment by andreban** [comment]
I'm working on #445 that should fix this.

**Comment by anuragvohraec** [comment]
> I'm working on #445 that should fix this.
No its not working yet.
I have my pwa here : [https://yeio.app/](https://yeio.app/)
And if user install it via chrome add to home screen, all works fine.

However after publishing it to playstore using bubble wrap (PWABuilder), the share to target option is not working.
