### ISSUE TITLE
setAppBadge does not show notification badge

### ISSUE THREAD

**Issue by adarshmadrecha** [GoogleChromeLabs/bubblewrap#450]
**Describe the bug**
`navigator.setAppBadge` does not show Notification Badge

**To Reproduce**
1. call `navigator.setAppBadge(1)`
2. Check the app icon in the home screen

**Expected behavior**
Show the notification badge

**Screenshots**
NA

**Smartphone (please complete the following information):**
 - Device: One Plus Nord
 - OS: Andriod M
 - Browser: Chrome
 - Version: 87

**Additional context**
Ref:  https://web.dev/badging-api/

**Comment by JohnRSim** [comment]
I tried this a month or so ago and read into it - appears it's only for desktop ATM.

Badging for app should only appear on Android with push messages.

Also tried local messages but no badge indicator.

I think I read you should see a dot to indicate setbadge on Android but no numbers as this is reserved for message indicator currently.

Wasn't able to get any indicator - I'd be interesred if you find a solution. But I think support is only for desktop currently.. only tested with TWA chrome.

**Comment by getify** [comment]
[Caniuse reports that `setAppBadge` should work on Chrome Android](https://caniuse.com/?search=setAppBadge), so I am curious if that data is incorrect?

I came here also wondering if it the badging works only while the PWA is open, or if it also works when the app is closed (but is called via SW from like a periodic sync)? The reason I ask is, for desktop-installed PWAs (windows), I see that if the PWA is open, the badging works, but if you close the PWA, the badge goes away. That's a major disadvantage that drastically limits the badge's usefulness.

Native apps can of course have badges on icons even if the app is closed. So, if I package a PWA with bubblewrap into an Android native app, 1) will the `setAppBadge(..)` work on the Android app? 2) will it work even while the Android app is closed, or only while it's open (as installed PWAs do)?

**Comment by getify** [comment]
Actually, I just read up more on this, and it appears Android cannot do individual app badges, there's no API for it. The OS automatically manages the badge when notifications are sent/dismissed. So, it seems clear there's nothing for bubblewrap to do, since there's no Android API it could hook up to anyway.

**Comment by andreban** [comment]
Thanks for all the comments. I'll close this as unfeasible.
