### ISSUE TITLE
How can we exit TWA App in android on multiple back click?

### ISSUE THREAD

**Issue by sudheerkr** [GoogleChromeLabs/bubblewrap#453]
I have tried https://stackoverflow.com/questions/43329654/android-back-button-on-a-progressive-web-application-closes-de-app

**Comment by andreban** [comment]
The application will exit once the back stack (or the `window.history`) is empty - this seems to be the case in my test apps. Can you provide more details on what you are looking for? Also, please, add browser version / bubblewrap version, etc.

**Comment by andreban** [comment]
Closing this as inactive.

**Comment by jykdesigns** [comment]
Have tried in my emulator. However seems to be just in background.
