### ISSUE TITLE
Lost my bubblewrap associated passwords. Now I cannot build. How to solve?

### ISSUE THREAD

**Issue by MiltonAkash** [GoogleChromeLabs/bubblewrap#454]
Google play customer service asked me to upload a PEM file and they can reset it. How to achieve this with bubblewrap.

**Comment by andreban** [comment]
Bubblewrap doesn't store the passwords, so it won't be able to recover them for you.

The Google Play customer service seems to be referring to [this documentation](https://support.google.com/googleplay/android-developer/answer/9842756). From the docs, the command to export the key file is: 

```shell
keytool -export -rfc -keystore upload-keystore.jks -alias upload -file upload_certificate.pem
```

You will need Java on our system PATH to run the command.

**Comment by MiltonAkash** [comment]
No my question is how to associate this new key and the bubblewrap build.

**Comment by andreban** [comment]
OK, I'm not sure I understand the question. If you lost your key and are using App Signing, you'll need to:

1. Generate a new upload key
2. Export the .pem file and upload to the Play Store
3. Update `twa-manifest.json` with the new key information (path and alias).
