### ISSUE TITLE
oAuth log out leaves browser tabs header display when returning to app? 

### ISSUE THREAD

**Issue by JohnRSim** [GoogleChromeLabs/bubblewrap#459]
**Describe the bug**
When logging out of azure and returning to the app the browser tabs header appears in the app?
If I sign back in with the header display then it returns to the standard app view?

**To Reproduce**
1. Singin to Azure.
2. Logout
3. close browser
3. header appears in app..
4. sign back in to azure
5. header disappears
 
Also if I close and open the app header disappears

**Expected behavior**
When logging out and returning to app dont want to see the browser tabs header bar

**Screenshots**
Attaching video

**Desktop (please complete the following information):**
 - OS: win
 - Browser chrome
 - Version 10

**Smartphone (please complete the following information):**
 - Device: samsung s9
 - OS: android 10

https://user-images.githubusercontent.com/364208/107317045-d0c05580-6a91-11eb-8786-a8e4161a2280.mp4

 - Browser chrome
 - Version 88.x

**Additional context**

**Comment by andreban** [comment]
This seems like a bug in the browser implementation (Bubblewrap or the host app don't have control over this). I filed a bug at http://crbug.com/1176206 to track.

@PEConn FYI

**Comment by JohnRSim** [comment]
It appears to be an intermittent issue but happens more frequently than not.

Open and closing external links seem to work fine can't replicate.

Only happens with the azure logout.

J

**Comment by younesaassila** [comment]
I have the same problem except I can replicate it reliably with **any** external link that opens in the browser when closing its associated tab using the `X` button. This bug doesn't occur when using a PWA installed from the browser so it must be a Bubblewrap issue I'm guessing?

**Comment by andreban** [comment]
@younesaassila would you mind adding those details to the Chromium bug (http://crbug.com/1176206 )? I'll lock and close this issue, as this isn't something under control of this project.
