### ISSUE TITLE
Update Bubblewrap to use the latest Android Build Tools version 30.0.3

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/bubblewrap#467]
The Build Tools version is specified at https://github.com/GoogleChromeLabs/bubblewrap/blob/master/packages/core/src/lib/androidSdk/AndroidSdkTools.ts#L26.

Updating this should be easy enough, but we should ensure everything works correctly on Linux, MacOS, Windows and ChromeOS.

**Comment by toastal** [comment]
Can you export this `const` as well as other versions that are used in internal version checks? If someone wants to make a derivation of the project you could then `require("AndroidSdkTools").BUILD_TOOLS_VERSION`

**Comment by andreban** [comment]
Yes, this shouldn't be a problem.
