### ISSUE TITLE
App Reloading

### ISSUE THREAD

**Issue by kartikcool15** [GoogleChromeLabs/bubblewrap#469]
**App Reloading Whenever I click on app icon from homescreen**
My app is installed successfully, When I opened the app and minimize it, all seems fine, I reopened the app from recent apps, its opening fine, but when app is minimized, and i open it from app icon from homescreen, it get refreshed each time.

**Expected behavior**
It should be refresh if it already opened and minimized, If it opens for the first time then only reload should happen

**Comment by andreban** [comment]
I can't reproduce this behaviour in any of my test apps. We need more details (eg: which browser version, bubblewrap version, etc) to be able to reproduce. Videos and screenshots can also help.

**Comment by comp615** [comment]
@andreban I'm also experiencing this on a build of Twitter. Pixel 5, chrome 90, Android 11. It's strange because @jdecked does not see it on the same build.

Let me know if I can debug something on my phone to help track down why, but I think this could be very disruptive to users

**Comment by andreban** [comment]
@comp615 to confirm, this happens when re-launching immediately after minimising, but doesn't happen when loading from the "Recents" tab? I'm wondering if any app or setting may be killing the app when in background. 

CC @PEConn in case he has any ideas.

**Comment by comp615** [comment]
Updates here for public record (as a note I also sent a logcat to Andre via DM).

It only happens sporadically for me, and I can't figure out why or when. I haven't tried the recents tab yet, but next time I see it I will!

For now:
Launch Twitter Lite
Go back to home screen
Launch Twitter Lite from icon
Splash screen shows / website hard reloads

The splash it's showing is not the Android generated icon splash, it's the web/twitter-side JS splash. This to me indicates that the Android activity is not fully relaunching, but something in the system is causing the web location to be changed / reloaded / reset (these hard reloads are when we show the shell splash screen again).

**Comment by andreban** [comment]
Updating the thread with @PEConn findings:

**Working flow:**
1. Kill Twitter TWA (hit X or swipe up from Recents).
2. Launch Twitter TWA from the home screen.
3. Background it.
4. Click on the home screen icon again.

Result: There should be no reload.

**Broken flow:**
1. Kill Twitter TWA.
2. From a computer connected with adb, run:
  adb shell am start -a android.intent.action.VIEW -d https://mobile.twitter.com/\?normal_launch_url\=nope
3. This should launch Twitter TWA on your phone.
4. Background it.
5. Click on the home screen icon.

Result: The page reloads. You can then repeat steps 4 & 5 as many times as you like and it still reloads.
