### ISSUE TITLE
Mediasession App Launching

### ISSUE THREAD

**Issue by kartikcool15** [GoogleChromeLabs/bubblewrap#470]
**Is your feature request related to a problem? Please describe.**
I have a media control mediasession in pwa, Upon clicking the mediasession the pwa launches, but its not happening on twa

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andreban** [comment]
Is there an application I can use to try and reproduce the issue?

**Comment by andreban** [comment]
Closing the issue, as it doesn't have many reproduction details and has been inactive for a while.

**Comment by kartikcool15** [comment]
https://play.google.com/store/apps/details?id=in.awesong.twa

You can play any song, You will see a MediaSession Notification in The Notification Bar, If You will click on the notification, its not returning to the twa. While its working fine on the Chromes Browser
