### ISSUE TITLE
[Windows] Bubblewrap Build failing at gradlew.bat

### ISSUE THREAD

**Issue by iamsid** [GoogleChromeLabs/bubblewrap#481]
**Describe the bug**
Started experimenting with Bubblewrap today. Ran into [this](https://github.com/GoogleChromeLabs/bubblewrap/issues/479) issue. It was coincidently reported and fixed within 10 minutes.
Now, at the last build step I am getting the below error:

cli ERROR Command failed: gradlew.bat assembleRelease --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.1.1/userguide/gradle_daemon.html
Process command line: C:\Users\xxx\.bubblewrap\jdk\jdk8u265-b01\bin\java.exe -Xmx1536m -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\xxx\.gradle\wrapper\dists\gradle-6.1.1-bin\4i3ntwqiazourd86epxcz427c\gradle-6.1.1\lib\gradle-launcher-6.1.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.1.1
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleException: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.1.1/userguide/gradle_daemon.html
Process command line: C:\Users\xxx\.bubblewrap\jdk\jdk8u265-b01\bin\java.exe -Xmx1536m -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\xxx\.gradle\wrapper\dists\gradle-6.1.1-bin\4i3ntwqiazourd86epxcz427c\gradle-6.1.1\lib\gradle-launcher-6.1.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.1.1
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap

        at org.gradle.launcher.daemon.client.DaemonGreeter.parseDaemonOutput(DaemonGreeter.java:38)
        at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startProcess(DefaultDaemonStarter.java:175)
        at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startDaemon(DefaultDaemonStarter.java:137)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.doStartDaemon(DefaultDaemonConnector.java:217)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startDaemon(DefaultDaemonConnector.java:211)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:133)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:140)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:94)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:56)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:212)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:404)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:376)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:38)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:23)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:369)
        at org.gradle.launcher.Main.doAction(Main.java:35)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

* Get more help at https://help.gradle.org 

**To Reproduce**
I ran the command `bubblewrap init --manifest https://my-twa.com/manifest.json` which worked fine.
Then I ran `bubblewrap build` which produced the above error.
I see that the error is similar to [this](https://github.com/GoogleChromeLabs/bubblewrap/issues/235) report, but its specific to MacOS I think, and mine is on Windows.

I installed JDK & Android SDK using Bubblewrap's prompt itself. So not using any manual configuration either.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by andreban** [comment]
I've seen this issue before and surprisingly (or not), it was solved by restarting the computer. Can you check if this works?

**Comment by iamsid** [comment]
I thought so too while posting this. Tried it, but no luck. Getting the same error after restarting the system too.
I also ran an elevated CMD, but no luck.

**Comment by andreban** [comment]
Thanks. Does this help: https://stackoverflow.com/questions/30045417/android-gradle-could-not-reserve-enough-space-for-object-heap

Can you try editing the `gradle.properties` file in the generated project and comment out the line with `org.gradle.jvmargs=-Xmx1536m` and try running build again (PS: running `bubblewrap update` will revert this change).

**Comment by iamsid** [comment]
I commented out the link as instructed and it seems to have worked.

![image](https://user-images.githubusercontent.com/17705415/109986222-8e560580-7d2b-11eb-8a00-54f954667320.png)

**Comment by joycetoh8** [comment]
@andreban It looks like this has been resolved and the issue can be closed?

**Comment by andreban** [comment]
Sgtm

**Comment by SphaeroX** [comment]
I had the problem too, can't you fix it automatically so Windows users can use Bubblewrap without problems?

**Comment by joepb** [comment]
Same here, running on Windows 11.

```ver
cli ERROR Command failed: gradlew.bat assembleRelease --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.5/userguide/gradle_daemon.html
Process command line: C:\Users\joep\.bubblewrap\jdk\jdk-11.0.9.1+1\bin\java.exe --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED -Xmx1536m -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\joep\.gradle\wrapper\dists\gradle-6.5-bin\6nifqtx7604sqp1q6g8wikw7p\gradle-6.5\lib\gradle-launcher-6.5.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.5
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap
```

**Comment by SphaeroX** [comment]
> Same here, running on Windows 11.
> 
> ```
> cli ERROR Command failed: gradlew.bat assembleRelease --stacktrace
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Unable to start the daemon process.
> This problem might be caused by incorrect configuration of the daemon.
> For example, an unrecognized jvm option is used.
> Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.5/userguide/gradle_daemon.html
> Process command line: C:\Users\joep\.bubblewrap\jdk\jdk-11.0.9.1+1\bin\java.exe --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED -Xmx1536m -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\joep\.gradle\wrapper\dists\gradle-6.5-bin\6nifqtx7604sqp1q6g8wikw7p\gradle-6.5\lib\gradle-launcher-6.5.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.5
> Please read the following process output to find out more:
> -----------------------
> Error occurred during initialization of VM
> Could not reserve enough space for 1572864KB object heap
> ```

use https://www.pwabuilder.com, they are using Bubblewrap too :)

**Comment by miguelmba2000** [comment]
> Merci. Est-ce que cela aide : https://stackoverflow.com/questions/30045417/android-gradle-could-not-reserve-enough-space-for-object-heap
> 
> Pouvez-vous essayer de modifier le `gradle.properties`fichier dans le projet généré, commenter la ligne avec `org.gradle.jvmargs=-Xmx1536m`et réessayer d'exécuter build (PS : l'exécution `bubblewrap update`annulera cette modification).

oui oui j'

**Comment by miguelmba2000** [comment]
oui oui j'ai fais la même chose et ca marche

**Comment by Ariska138** [comment]
When using babblewrap, I also experienced many problems. Several important points to be successful. that is:
- install jdk and android sdk from default/recommended bubblewrap (even if you already have it before)
- in env, JAVA_HOME and PATH use jdk 8
- in the gradle.properties file, change org.gradle.jvmargs=-Xmx1536m to org.gradle.jvmargs=-Xmx1024m

good luck. happy to share. :)

**Comment by Ariska138** [comment]
when I experience problems, I know the headache. but when you find the source of the problem and know the solution. That is very fun. I have summarized several important points when using bubblewrap here https://stackoverflow.com/a/77465377/6346135

**Comment by 0-harshit-0** [comment]
What's happening is (as mentioned in the error message), it is running out of memory.
As mentioned above if you comment out the org...=Xmx.. line it will work because this is the memory allocation configuration, and removing it means, it is free to use as much memory as possible (I think).
I'm not a Java/gradle expert, so I'm not sure how much memory should be allocated to make it work without error, so currently the only quickest way out is to comment that line 😄.

**Comment by VrainsieTech** [comment]
I actually encountered the same. 
SOLUTION.
Error claims the 15***** was not found to start daemon VM server.
So,  
In your project folder, find gradle.properties file.
Open it with either notepad or your favorito editor.
Edit the line that has 15**m tp have 1024m.

This trick simply gives the VM 1GB space of memory to work with.
In case you are running on less than 4GB RAM total on your windows machine. 
Comment the whole line so you be safe.

Optionally, after edit, close other programs so you only have your terminal open.
It will take a few minutes before creating the builds.

Good luck.

**Comment by BrennanTanner** [comment]
Tried all these fixes with no avail, same memory error on build.  Oddly enough, running `bubblewrap update` fixed the issue.
