### ISSUE TITLE
Missing documentation for fingerprint command

### ISSUE THREAD

**Issue by KurtGokhan** [GoogleChromeLabs/bubblewrap#483]
The `bubblewrap fingerprint` command was added with #478. But there is no information on how to use it.

Specifically, I want to know how to generate `assetlinks.json` file automatically as in the previous versions.

**Comment by andreban** [comment]
Sorry for this, that's on my plate to document.

We removed automatic generation from the signing key, as developers will ideally use [Play App Signing](https://developer.android.com/studio/publish/app-signing#app-signing-google-play) and this will cause `assetlinks.json` to be just wrong. 

[This video](https://www.youtube.com/watch?v=3bAQPnxLd4c) by @nohe427 explains how to get the correct fingerprint from the Play Store. 

With that information, you can run `bubblewrap fingerprint add <fingerprint>` and it will store that information in `twa-manifest.json` and generate the `assetlinks.json` file. You can run `bubblewrap generateAssetLinks` at any time to regenerate the `assetlinks.json` file from the details stored in the configuration.

**Comment by KurtGokhan** [comment]
Thank you. This is clear enough for me. 

I also found that running `bubblewrap help fingerprint` shows this info. (Although it says `bubblewrap generateAssetLinks`) 

You can close the issue when you want.
