### ISSUE TITLE
[ChromeOS] Changing "name" and "launcherName" in "twa-manifest.json" do not update the app label in the app shelf

### ISSUE THREAD

**Issue by kinyat** [GoogleChromeLabs/bubblewrap#485]
**Describe the bug**
We want to show a different name for different environments by changing the `name` and `launcherName` in `twa-manifest.json` but it only works during the installation. After the installation, it will show some other name and our guess is that it is using the `name` and `short_name` in `manifest.webmanifest`. We are building it for ChromeOS only so not sure if this is another reason why it fails.

The following is the related parts of the files.

In `twa-manifest.json`
```json
{
  "name": "Example (Beta)",
  "launcherName": "Example (Beta)",
}
```

In `manifest.webmanifest`
```json
{
    "name": "Example",
    "short_name": "Example",
}
```

In `app/build.gradle` after bubblewrap update/build
```gradle
def twaManifest = [
    name: 'Example (Beta)', // The application name.
    launcherName: 'Example (Beta)', // The name shown on the Android Launcher.
]

android {
    defaultConfig {
            // The name for the application
        resValue "string", "appName", twaManifest.name

        // The name for the application on the Android Launcher
        resValue "string", "launcherName", twaManifest.launcherName
    }
}
```

**To Reproduce**
1. Update "name" and "launcherName" in "twa-manifest.json" to be different than the "name" and "short_name" in "manifest.webmanifest"
2. `bubblewrap update` and `build`
3. Install the apk, you can see the updated name is showing during the installation.
4. open the app shelf, you can see that it is NOT showing the updated name

**Expected behavior**
It should honour the settings in `twa-manifest.json` for the `name` and `launcherName`

**Desktop (please complete the following information):**
- OS: ChromeOS
- Browser: Built-in browser
- Version: 89

**Comment by andreban** [comment]
Did you run `bubblewrap update` after updating `twa-manifest.json`?

**Comment by andreban** [comment]
To confirm: the content in `build.gradle` matches the one from `twa-manifest.json` **after** the update.

A possible workaround: Have you tried uninstalling the app before installing the new package?

@ibrahimkarahan @joycetoh8 @nohe427 can you take a look into this? I'm wondering if this is related to how TWAs work on Chrome OS.

**Comment by kinyat** [comment]
> To confirm: the content in `build.gradle` matches the one from `twa-manifest.json` **after** the update.
> 
> A possible workaround: Have you tried uninstalling the app before installing the new package?
> 
> @ibrahimkarahan @joycetoh8 @nohe427 can you take a look into this? I'm wondering if this is related to how TWAs work on Chrome OS.

Yeah we tried to uninstalling the app even tried to flush everything but no luck :(

**Comment by nohe427** [comment]
I saw this behavior as well with our potato app. I'm going to see if I can track this down today or at least start searching.

**Comment by andreban** [comment]
This is a feature request for how Chrome OS handles updates to the Trusted Web Activity package. Unfortunately, outside the scope of Bubblewrap to fix. I'm closing the issue here for this reason. @nohe427 is there an open bug on the Chrome OS bug tracker for this? Would you mind dropping here as a comment, if that's the case?
