### ISSUE TITLE
v1.11.0 assetlinks.json not generated by`bubblewrap build` and `bubblewrap fingerprint generateAssetLinks` is empty

### ISSUE THREAD

**Issue by elgreg** [GoogleChromeLabs/bubblewrap#486]
**Describe the bug**

Per the [Quick Start Guide](https://developer.chrome.com/docs/android/trusted-web-activity/quick-start/), an assetlinks.json should be generated when I run `bubblewrap build` but this seems to only be the case in v1.10.0 AND when I use the new fingerprint command, the file is empty (I think because it imports and maps over the empty `fingerprints` key in the generated twa-manifest.json).

**To Reproduce**

1. npm install @bubblewrap/cli@v1.11.1
2. `npx bubblewrap init --manifest=https://slate.com/media/sites/slate-com/web-app-manifest.json`
3. press enter at all prompts
4. `npx bubblewrap build --skipPwaValidation`
5. Note that there is not assetlinks.json file generated nor a message about it
6. `npx bubblewrap fingerprint generateAssetLinks`
7. Note that assetlinks.json is empty

**Expected behavior**
`npx bubblewrap fingerprint generateAssetLinks` should generate an assetlinks.json file with content similar to v1.10.0 e.g.

```
[{
        "relation": ["delegate_permission/common.handle_all_urls"],
        "target" : { "namespace": "android_app", "package_name": "com.slate.twa",
                     "sha256_cert_fingerprints": ["B8:C8:22:AF:6C:D2:5B:7A:68:F4:2D:F8:BB:D8:F5:10:21:21:E4:69:E2:5A:FA:79:0C:EA:2D:C2:69:4D:FF:19"] }
      }
]
```

**Additional context**
When I install v1.10.0, its `bubblewrap build` generates the assetlinks.json file, so this error seems likely related to addition of the fingerprint command in #478. Note also that #478 assume that there will be something in the fingerprints array of the twa-manifest.json file, but that when I do a `bubblewrap init` for my manifest that array is empty in twa-manifest.json. Both v1.10.0 and v1.11.1 generate the empty fingerprints array `"fingerprints": [],` - but only v1.11.1 seems to rely on it being populated with the fingerprint command. Did I miss something?

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser n/a
 - Version v.1.11.1

**Comment by andreban** [comment]
Thanks for filing this, @elgreg. 

Generating fingerprint from the key generated by Bubblewrap was removed. The reason for the change is that most developers use (and they should be using) Play App Signing when upload the app to the Play Store and the default assetlinks.json generated by Bubblewrap was incorrect in most cases.

We may want to reinstate that, since that key can be used for debugging locally.

**Comment by elgreg** [comment]
Thanks @andreban - I'm using an existing keystore during the --init and trying to debug in our local, dev, and stage environments before going to production. What would you recommend for correctly generating an assetlinks.json file? Just using v1.10.0 for now...

**Comment by andreban** [comment]
This [video](https://www.youtube.com/watch?v=3bAQPnxLd4c) has information around this.

**Comment by elgreg** [comment]
Thanks! The video refers to a section of the portal called "App signing"
which I didn't see. I was able to find the sha-256 under "App integrity"
and I will look into that now. I should have found it but definitely
watched the video the first time and searched for it in the cmd-F and
didn't see it and assumed it was something to do with the app being removed.

[image: Image 2021-03-22 21-45-28.png]

**Comment by devalexqt** [comment]
`bubblewrap build` not generated `assetlinks.json` for me too! And WTF?

**Comment by elgreg** [comment]
@devalexqt Yup. Per comment from @andreban  "Generating fingerprint from the key generated by Bubblewrap was removed."

You can figure out the sha256 by yourself for a keystore using `keytool -list -v`. Here's an example or the default android debug keystore that's probably in your home directory:

`keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android`

Then you can copy and paste the sha256 out of that into an assetlinks.json file tha thas the right package_name:

```
        "relation": ["delegate_permission/common.handle_all_urls"],
        "target" : { "namespace": "android_app", "package_name": "[your pacakage name e.g. com.stuff.app]",
                     "sha256_cert_fingerprints": ["the sha256"] }
      }
```

**Comment by andreban** [comment]
@devalexqt please, read this [comment](https://github.com/GoogleChromeLabs/bubblewrap/issues/486#issuecomment-800980947) which explains why it was removed. Also, please do observe our [code of conduct](https://github.com/GoogleChromeLabs/bubblewrap/blob/main/CODE_OF_CONDUCT.md).

**Comment by devalexqt** [comment]
Thanks for reply, I make TWA for first time and was little bit confused. But now I understand this situation. PS: Thanks for bundler, it's fast and really easy to use!

**Comment by hhimanshu** [comment]
> Thanks for filing this, @elgreg.
> 
> Generating fingerprint from the key generated by Bubblewrap was removed. The reason for the change is that most developers use (and they should be using) Play App Signing when upload the app to the Play Store and the default assetlinks.json generated by Bubblewrap was incorrect in most cases.
> 
> We may want to reinstate that, since that key can be used for debugging locally.

@andreban, based on what I read, we should reconsider updating https://developer.chrome.com/docs/android/trusted-web-activity/quick-start/#creating-your-asset-link-file. Since I am new and looking for first hand information, I relied on this web page and did not see `assetlinks.json` being created.
It's only when I hunted down I came to this GitHub issue. As I understand now, I must use https://developer.chrome.com/docs/android/trusted-web-activity/quick-start/#play-store-signing for generating `assetlinks.json`. Please correct me if I am wrong here. Thanks

**Comment by JoshuaKGoldberg** [comment]
@andreban do you think someone could update https://developer.chrome.com/docs/android/trusted-web-activity/quick-start/#creating-your-asset-link-file then? Very confusing that the guide says to use a feature that was removed.
