### ISSUE TITLE
Issues with "splash screen" on android app built by PWABuilder (using bubblewrap)

### ISSUE THREAD

**Issue by getify** [GoogleChromeLabs/bubblewrap#488]
I've built my android app using [PWA Builder](https://pwabuilder.com), which as I understand uses bubblewrap to produce its Android app exports. I successfully deployed my app to the play store. I originally filed this bug there, but they redirected me to file here.

When I launch the app from my phone, I see a few weird visual issues during the splash screen and loading. These same issues aren't really as pronounced when launching the installed-PWA on the same phone, so I think these are specifically related to how the Android app is generated.

----

The first issue I have is there's inconsistency (a sort of super quick flashing) of the colorization applied to the top status bar during load. See these 2 screenshots, which go in order.

In this one, the top status bar is green per my configuration:

<img width="300" src="https://user-images.githubusercontent.com/150330/112035892-0420e600-8b0e-11eb-986a-9e08081bef16.jpg">

In this one, which happens a split second later, but still while loading and showing my splash screen, the top bar is now black (my phone's dark mode setting overriding, maybe?):

<img width="300" src="https://user-images.githubusercontent.com/150330/112035893-04b97c80-8b0e-11eb-8772-2b0188ee0f64.jpg">

Any idea why this happens? Any way to fix it? I would *prefer* my status bar not be overridden and to stay the same green color I configured, and as it starts out with. Is this likely something specific with my phone/settings, or is this something that would affect most or all other Android phones?

----

Relatedly, the "splash" color being a single flat color is something I wish I could override. Is there anyway to specify a gradient instead of a single color?

As you can see in this screenshot, once my app fully loads, it's using a gradient background, which is intentionally designed so as to match up to the same "green" color on top (if the status bar stayed the intended color) and the same "gray" color I'm specifying for my bottom navigation bar:

<img width="300" src="https://user-images.githubusercontent.com/150330/112035894-04b97c80-8b0e-11eb-8363-8b7a95ce2162.jpg">

In the first two screenshots, that bottom navigation bar sticks out more like a sore thumb because of lack of ability to use my gradient in my splash screen.

I guess this is a little more of a feature request than bug report, but is it possible for bubblewrap to support gradient background on the splash screen? If so, that would eliminate one of the bugs/quirks I'm experiencing. I feel like other native Android apps I've seen (not PWAs) do have more customized splash/loading screens.

----

The third issue is with the splash image used. Per the PWABuilder settings, I'm specifying both an "Icon" and a "Maskable Icon". The "Icon" one is circular, with PNG transparency. The "Maskable Icon" one is square, with the same green theme/splash full out to the edges.

My "Icon" image is circular because it's the same image (in different sizes, of course) used for the favicon or other smaller icon representations for the app (like in older phones where the PWA is just added to the home screen). This provides a sort of consistency to the icon from the PWA vs the Android app (in case anyone had them installed side-by-side).

But if you look closely at the following cutout image from first/second splash screenshots above , you can see a faint "ring" around the icon. If you zoom in, it seems to be some sort of transparency artifacts or something like that?

<img width="550" src="https://user-images.githubusercontent.com/150330/112038643-19e3da80-8b11-11eb-9585-dfed795ba985.jpg">

Clearly the generated app uses the my circular "Icon" for the splash screen instead of my square "Maskable Icon". Of course, that *should* be fine, I would think, since the circular "Icon" image itself has perfectly fine PNG transparency on its edges. However, clearly something is wrong with the compositing of the transparency.

Here's that original PNG icon by itself:

<img width="512" src="https://user-images.githubusercontent.com/150330/112038751-3da72080-8b11-11eb-9a89-17e2fe293876.png">

But here's that same PNG layered over the same flat green background in an image editor:

<img width="550" src="https://user-images.githubusercontent.com/150330/112039566-2caadf00-8b12-11eb-90bb-95053e3bed94.png">

As you can see, no ring, the transparency layers perfectly fine. So I'm not sure why the ring is appearing in the splash screen of the android app. Can you help me clarify and fix?

**Comment by andreban** [comment]
# Regarding issue 1

- This is what I'm seeing on my test device, which seems different from what's been described? In my case, it seems the splash is being launched with the correct colours, but then they are changed.

https://user-images.githubusercontent.com/1733592/112188023-88509780-8bfa-11eb-842c-ce34e0badc1b.mp4

# Regarding issue 2

- Not via a Web Manifest / Bubblewrap. However, I **think** this may be possible using Trusted Web Activity directly by providing several images that match different screen sizes (or at least each DPI). This is outside the scope of Bubblewrap.

# Regarding issue 3

- Can you provide the Web Manifest Url? I want to run the Bubblewrap CLI and try to repro the artefact.

**Comment by getify** [comment]
## Issue 1

Here's what it does on my phone (oneplus 8pro with android 11)... you can see brief flashes as you watch it, but if you drag the video thumb "frame by frame" through, you can see that as the app animates its opening, the status bar and navbar are solid black, then once it's maximized, it the status bar briefly flashes to green (while the navbar goes to its proper medium gray), then the status bar goes back to the dark gray "dark mode" status bar. It doesn't stay the green that it should.

https://user-images.githubusercontent.com/150330/112199530-4284d680-8bdc-11eb-8f36-40334f946ec3.mp4

## Issue 2

I already have full-screen splash images specified in the HTML (via `<link rel="apple-touch-startup-image" ...`) for when the PWA is "installed" on iOS devices. I don't currently have the gradient in those images, but I could of course easily add it to those images.

However, I'm not aware of any way to force Android to use those images, since there's no manifest key (AFAIK) that gives it a background image instead of a theme color.

If you could guide me on what I do (via my manifest, or if there's something that PWAB could be sending differently?) to specify full-screen splash images? That would actually solve my whole "Issue 3" of the transparency being messed up on my logo.

## Issue 3

Here's the manifest file: https://flashmath.cards/flashmathcards.webmanifest

**Comment by andreban** [comment]
## on issue 3:

Bubblewrap is indeed using https://flashmath.cards/images/app-icon-512.png as the source for the splash screen, which is working as intended.

This is what is generated by Bubblewrap:
![splash](https://user-images.githubusercontent.com/1733592/112214554-3e29df00-8c17-11eb-9989-771cfa4b13ad.png)

When rendering this image on top of a background with `#51A6A5` it is possible to see the black ring. 

**Possible workaround:**

The original image does have a transition on the transparency between the opaque colour and the transparent areas. This can be seen by editing the image and using a fill tool on the corner of the image.
![app-icon-512](https://user-images.githubusercontent.com/1733592/112215324-2acb4380-8c18-11eb-9b68-3372036d4002.png)

Removing this transparency transition should get rid or the black ring (again, this is a bug in Bubblewrap and should be fixed).

**Comment by getify** [comment]
> Removing this transparency transition should get rid or the black ring

I am generating these various PNG images by simply rendering out from the SVG... so the image editor is the one doing any of the pixel transparency stuff on the edges, not me -- in my SVG, of course, it's a perfectly crisp vector circle. But AFAIK whenever you rasterize a vector with smooth rounded edges, it's pretty much always going to fade out the edges to make it look smooth, right?

I don't know how to tell my graphics program to not do that. And moreover, if that icon image is used elsewhere, such as by the Android OS in some other menu or screen, I don't want the circular image by itself to look jaggedy.

> again, this is a bug in Bubblewrap and should be fixed

Thanks for confirming... any idea how long that fix might take, or an ETA?

**Comment by andreban** [comment]
The code in Bubblewrap to resize images is [pretty straightforward](https://github.com/GoogleChromeLabs/bubblewrap/blob/main/packages/core/src/lib/ImageHelper.ts#L39-L43), but the issue seems to be in the underlying library, [Jimp](https://www.npmjs.com/package/jimp). See https://github.com/oliver-moran/jimp/issues/442 and https://github.com/oliver-moran/jimp/issues/848. Those issues seem to be open for a while there, but I'll try seeing if there's a workaround we can try. (no ETA)

**Comment by getify** [comment]
Curious... am I the only one who's ever tried to use a semi-transparent splash image in a PWA-as-Android-app before? I'm wondering what it is I'm doing uniquely wrong for this issue to just now come up, or (rather) for it to be so low priority for that other tool you mentioned?

**Comment by andreban** [comment]
It does seem like this is hitting some kind of edge case - interestingly, we used [sharp](https://www.npmjs.com/package/sharp) in the past, which was causing #240, which is a very similar issue and moved to Jimp in #262. IIRC, #240 wasn't reproducible with jimp.

**Comment by andreban** [comment]
An interesting observation is that the issue only seems to happen when the output image is larger than the input image.

**Comment by andreban** [comment]
Switching Jimp's resize algorithm to `Jimp.RESIZE_NEAREST_NEIGHBOR` gets rid of the black ring. However, the output image quality is different.

Here's a comparison of the default resize and nearest neighbor when scaling up:
Using default resize algorithm:
![result](https://user-images.githubusercontent.com/1733592/112462525-0d51c300-8d59-11eb-83a9-73982db6d874.png)

Using `Jimp.RESIZE_NEAREST_NEIGHBOR`:
![result](https://user-images.githubusercontent.com/1733592/112462566-1cd10c00-8d59-11eb-8287-45a3a7a94ffa.png)

While the default resize makes the image a bit blurry, nearest neighbor makes it look more jagged. It does look acceptable to me though.

However, when scaling down, there's a big different in outcomes and nearest neighbor has a clear loss in overall quality:
Using default resize algorithm:
![result](https://user-images.githubusercontent.com/1733592/112462754-543fb880-8d59-11eb-95c9-efde3511cbac.png)
Using `Jimp.RESIZE_NEAREST_NEIGHBOR`:
![result](https://user-images.githubusercontent.com/1733592/112462807-628dd480-8d59-11eb-8943-cee0f5012e0c.png)

What I would propose as a workaround is to only use the nearest neighbour when the output image is larger than the input image. Otherwise, use the default resize algorithm.

**Comment by getify** [comment]
That's interesting. I am specifying a 512x512 image icon for "Icon" (and "Masked") settings. It sure seems from my eyes that the icon used in the splash screen is much smaller than that, but I could be wrong. Do you think I should use the 1024x1024 source icon for the "Icon" setting instead?

**Comment by andreban** [comment]
The reason it looks smaller on the splash may be due to pixel density on the phone. The largest image generated by Bubblewrap is [1200x1200, for xxxhdpi screens](https://github.com/GoogleChromeLabs/bubblewrap/blob/main/packages/core/src/lib/TwaGenerator.ts#L82).

**Comment by getify** [comment]
So I guess the tradeoff here is, if I specify a large icon like 1024x1024 for this "Icon" setting, so that it's used in the splash screen, older Android devices (< v8) will use that same icon to make their normal homescreen/drawer icons, and that will be downscaling from a 1024x1024 image to a much smaller image, which will likely lead to a blurrier icon there. :/

Here's another approach: is there any way that bubblewrap exposes where you could just specify a single full image for the splash screen?

My HTML already has seven or so tags like this in it:

```html
<link rel="apple-touch-startup-image" href="/images/app-splash-640x1136.png" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
```

These tags are telling iOS devices (when you "add to homescreen" install the PWA) which image to pick for the full-screen splash.

It would be awesome if I had the option to do something similar for Android/etc apps. Either bubblewrap could just pick up on those tags, or they could be listed in the manifest, or... there could just be some manual setting that's provided a list of image(s) for a splash screen.

If that were possible, then I wouldn't need bubblewrap to "make" a splash screen for me, and we'd get around the bugs this image processing tool has.

**Comment by andreban** [comment]
With my proposal on [this comment](https://github.com/GoogleChromeLabs/bubblewrap/issues/488#issuecomment-806540325), we shouldn't have issues with downscaling images - the blurriness only happens when upscaling too. We'd also only use nearest neighbour for larger images.

I thought I had mentioned this in another comment, but it seems I didn't. There's an issue to allow a separate splash screen image on #226, but we haven't prioritised as it's not part of the Web Manifest spec.

**Comment by getify** [comment]
> There's an issue to allow a separate splash screen image on #226, but we haven't prioritised as it's not part of the Web Manifest spec.

I *think* I'm suggesting/asking for something different. I'm not talking about specifying a different icon to use in the building of a splash screen, which is what I think that issue is about.

I'm asking to be able to provide a single full image that *is* the splash screen, just the way iOS currently does it with installed PWAs.

**Comment by andreban** [comment]
Allowing a separate image for the splash screen would allow that, since the input image could have any size.

**Comment by getify** [comment]
Does the current logic that bubblewrap uses for building a splash screen handle detecting the screen size and then looking for an image that's big enough to cover the whole screen?

I was under the impression that the behavior was to select an image that fits nicely centered in the screen, which seems like different logic than "try to find the image that fits the whole screen".

**Comment by andreban** [comment]
> Does the current logic that bubblewrap uses for building a splash screen handle detecting the screen size and then looking for an image that's big enough to cover the whole screen?
> 
> I was under the impression that the behavior was to select an image that fits nicely centered in the screen, which seems like different logic than "try to find the image that fits the whole screen".

The current logic from Bubblewrap was created to use an image available in the [Web Manifest](https://www.w3.org/TR/appmanifest/). Since the Web Manifest doesn't provide a "splashscreen" purpose, we use the largest image and use it centered on the screen. We also use that image as the launcher icon. 

So, in practices, we don't have a logic for splash screens and If we provided a special field for the splash screen in Bubblewrap, we would probably use a different logic from what's there today.

> I may be misunderstanding here, so please forgive me, but this answer seem like conflicting with what you're saying.
>
>I'm trying to nail down if there's some way for bubblewrap (or something else?) to select a full-screen image (based on screen dimensions) as the splash screen, instead of it trying to paint some flat background color and center an image inside it? If that is possible, of course the full-screen image could have the gradient in it.
>

>Clearly, the overriding question is, how to get any full-screen image used, and then the second question (Issue 2 above, about a gradient) is suitably resolved by that answer.

>But "outside the scope of Bubblewrap" confuses me. How would I accomplish this providing of multiple images, and selecting the correct one based on screen size (similar to how iOS does it), if it's not Bubblewrap doing that work?

>I would be happy to write my own code for my splash screen, but I'm just not aware of how to go about that.

This is possible by manually modifying the Android application generated by Bubblewrap. The underlying Android library,  `android-browser-helper`, provides a [flag](https://github.com/GoogleChrome/android-browser-helper/blob/main/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/splashscreens/PwaWrapperSplashScreenStrategy.java#L104) that can customise how the splash screen is rendered. Setting that to [FIT_XY](https://developer.android.com/reference/android/widget/ImageView.ScaleType#FIT_XY) would scale the image to use the whole screen instead of centering it.

Since Android has different [screen densities](https://developer.android.com/training/multiscreen/screendensities) and width/height ratios, you would have to provide several images to have a good coverage of ratios and dpis.

An important bit: Bubblewrap can generate application packages that work on both Android and on Chrome OS. The way the underlying tech works on both platforms is different. This means that, even though some things are possible on one platform, they won't work in the other. This is one of those cases.

**Comment by getify** [comment]
> This is possible by manually modifying the Android application generated by Bubblewrap. The underlying Android library, android-browser-helper, provides a flag that can customise how the splash screen is rendered. Setting that to FIT_XY would scale the image to use the whole screen instead of centering it.

Ah, OK. That makes sense. I don't have Android Studio installed and don't really know Java -- that's part of why I was using PWABuilder! But it is good to know that I could, in theory, take the built app from here and modify it in the future, if that need arises. I don't think customizing the splash screen is important enough to me to jump to that level of complexity, though.

BTW, I assume in this case, I have to re-sign the app bundle before submitting to the store, right? Is that something Android Studio handles, or would that require other tooling?

> Since Android has different screen densities and width/height ratios, you would have to provide several images to have a good coverage of ratios and dpis.

Yeah, I already have seven different splash images (specified in the HTML markup, not in the manifest) for the various iOS devices (following some "best practices" I found on various sites)... I was imagining doing the same thing for Android. I don't know what the various screen sizes/ratios are, so I guess that would take a bunch of manual testing/research to figure out.

But assuming I did, I guess if Bubblewrap did eventually support this at a direct feature, it would be nice if it could set the `FITXY` setting for me, and to just be able to read those images from the markup the way iOS does. If not, then perhaps there could be a `"purpose": "splash"` addition to support icon entries in the manifest that Bubblewrap could read out and use as needed.

----

In any case, I suspect we can just file the "splash screen" requests I'm making mostly under feature requests. It'd be great if that image sizing bug could be fixed, but that's not your tool's direct fault.

Perhaps we can just focus the rest of this thread on addressing what may still be happening with overriding the status bar/nav bar colors during initial load?

**Comment by andreban** [comment]
> BTW, I assume in this case, I have to re-sign the app bundle before submitting to the store, right? Is that something Android Studio handles, or would that require other tooling?

Android Studio can do that - make sure the key used to generate the app and passwords are stored safely!

> It'd be great if that image sizing bug could be fixed, but that's not your tool's direct fault.

I'm still digging into that - I'm avoiding a native library and it doesn't seem there are many pure JS/TS alternatives. Maybe something that compile to WASM, like [this library ](https://crates.io/crates/photon-rs) would be an option. 

> Perhaps we can just focus the rest of this thread on addressing what may still be happening with overriding the status bar/nav bar colors during initial load?

You made a point about Dark Mode - we do have support for dark mode in Bubblewrap [here](https://github.com/GoogleChromeLabs/bubblewrap/blob/main/packages/core/src/lib/TwaManifest.ts#L132-L135). I think PWA Builder gave you a `twa-manifest.json` file? Would you be able to share it? (Do ping me on Twitter if you don't want to share directly in the issue)

**Comment by getify** [comment]
> I think PWA Builder gave you a twa-manifest.json file?

Not sure, where would that be? Are you talking about inside the download I get from exporting my Android app? In that zip file they give me, these are the files I get:

```cmd
assetlinks.json
Flash Math Cards.aab
Flash Math Cards.apk
Readme.html
signing.keystore
signing-key-info.txt
```

Is this `twa-manifest.json` file included inside the `.aab` or `.apk` file?

**Comment by andreban** [comment]
Oh, gotcha. I **thought** it was included, but it seems that's not the case. I wanted to check the variables for dark mode in their app.

**Comment by getify** [comment]
I have noticed that some apps on my android phone are able to take over the status bar with their own colors, and other apps don't (and the status bar stays black). Specifically, any installed PWAs (Chrome), even big ones like Twitter, are always the black status bar, though Chrome itself colors the status bar.

**Comment by andreban** [comment]
> I have noticed that some apps on my android phone are able to take over the status bar with their own colors, and other apps don't (and the status bar stays black). Specifically, any installed PWAs (Chrome), even big ones like Twitter, are always the black status bar, though Chrome itself colors the status bar.

I'm wondering if that's a device-specific issue. That's still the Oneplus 8 Pro / Android 11, right? Would you mind adding the Chrome version as well (from chrome://version)? For installed PWAs, filing a bug report at https://crbug.com/ is ideal.

**Comment by getify** [comment]
I have since upgraded to the Oneplus 9 Pro / Android 11, but yeah, same behavior. It was also present in Android 10 last year before I upgraded to v11.

My current Chrome version on my phone is 89.0.4389.105.

I filed this bug for the PWAs specifically... https://bugs.chromium.org/p/chromium/issues/detail?id=1196277 Not sure if whatever is affecting the PWAs is also affecting the native apps built by Bubblewrap, but it seems possible they're related? The difference is, with the PWAs, the status-bar and nav-bar go completely black, whereas with the Bubblewrap packaged app, the nav-bar and status-bar end up the same color (not black, but also not the differently specified colors in my settings).

Here's the screen recording showing both Twitter's PWA and my PWA being affected by this color bug:

https://user-images.githubusercontent.com/150330/113726799-2728c980-96ba-11eb-969b-9ab0c63f6703.mp4

Again, as stated, other native apps on my phone seem to have no trouble coloring both the status-bar and nav-bar. It's only PWAs and the packaged PWAs built by bubblewrap that seem to be affected (though slightly differently as noted).

**Comment by andreban** [comment]
Thanks for filing that. I CC'd myself in the issue and will follow-up with the teams internally.

**Comment by getify** [comment]
Do you suspect that the observed Android (TWA) bug (status-bar color) is actually just the same PWA bug (even though it presents slightly differently)? Or do you think it's a separate bug?

**Comment by andreban** [comment]
I'm guessing the same bug, since installed PWAs (also called WebAPKs) share a lot of code with TWAs in the Chrome side. I may, be wrong.

**Comment by andreban** [comment]
@getify found a better workaround for issue 3. Check #494

**Comment by getify** [comment]
@andreban that's awesome, makes perfect sense! :)

**Comment by andreban** [comment]
https://github.com/GoogleChromeLabs/bubblewrap/releases/tag/v1.12.0 has been released with this fix.

**Comment by andreban** [comment]
@getify Am I correct that the remaining issues are in the scope of the browser implementations, not Bubblewrap and we can close this now?

**Comment by getify** [comment]
I think that's true. Thanks.
