### ISSUE TITLE
Create a `llama-pack debug` command

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/bubblewrap#49]
The debug command would correctly setup the device to debug the TWA and launch it. 

- Create the debug configuration, as described [here](https://developers.google.com/web/updates/2019/02/using-twa#debugging). 
- Run `./gradlew installDebug`
- We may also want to add a command (or an option) to clean the debug config, by wiping out `/data/local/tmp/chrome-command-line` on the device.
- Caveat: Developers still need to enable the relevant flag on `chrome://flags`

**Comment by andreban** [comment]
@PEConn, WDYT?

**Comment by PEConn** [comment]
Yeah, I like this idea - I probably wouldn't call it debug though, maybe spoof verification or something.

It does open up the potential for developers to shoot themselves in the foot as they may enable this feature, forget about it then wonder why verification works on their device but for no-one else.
