### ISSUE TITLE
Support for providing signing key path & alias via command line flag in build command

### ISSUE THREAD

**Issue by jdecked** [GoogleChromeLabs/bubblewrap#490]
**Is your feature request related to a problem? Please describe.**
I'm generating a non-production keystore to sign the APK with for testing purposes only. I don't want to put the non-production path and alias of this signing key into my TWA manifest because it isn't actually what's used to sign the production release of the APK, so it might confuse future developers. It would be great if Bubblewrap could use a keystore path and alias that aren't supplied in the TWA manifest to sign the APK during the build command.

**Describe the solution you'd like**
Accept `--signingKeyPath` and `--signingKeyAlias` command line flags for the build command, which take precedence during the build command over what's specified in the TWA manifest.

**Describe alternatives you've considered**
**Key path and alias provided via environment variables:** Neither of these are particularly sensitive data, so environment variables don't seem necessary, but they could work, too.
**Putting the keystore path and alias into the TWA manifest:** Given that this keystore is generated on the fly for testing purposes, it may confuse future developers to put it in the TWA manifest when the actual (production) signing process involves working with another team to get the APK signed & released to prod.

**Additional context**
Happy to implement this myself if that'd be helpful!

**Comment by andreban** [comment]
Sounds good to me
