### ISSUE TITLE
Sound won't autoplay at launch of Android app, but does with same code in installed PWA

### ISSUE THREAD

**Issue by getify** [GoogleChromeLabs/bubblewrap#493]
My PWA (https://flashmath.cards) has now added sounds, including a little intro jingle on loop on the main welcome screen. I know that browser settings prevent autoplay of audio on normal sites (until a user event occurs), but apparently if you install the site as a PWA, you can autoplay audio. **NOTE:** I only play sounds when the code is launched "standalone" as an app, not when the site is just accessed in the browser.

Reference: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

I've found that to be true... in my PWA install on my phone, when I launch it, the sound starts playing correctly.

However, for the same code loaded into the Android app (created via Bubblewrap), it won't autostart playing the music, until I actually perform some user event. Any idea why the Android app is not able to get around this autoplay limitation, whereas the installed PWA is able to? That's pretty frustrating... if anything, I would have expected the other way around.

I should note: I have explicit logic in my code to detect user events and to resume an initially suspended audio context, which is why my welcome music starts playing when you simply tap anywhere on the welcome card in the Android app. So that definitely confirms that the audio context starts out initially suspended when launching my app from the Android app, but NOT suspended when the PWA is just launched itself.

Any idea how to fix this?

**Comment by andreban** [comment]
Unfortunately, there's nothing Bubblewrap can do about this one and this seems like a bug on the browser side. I have filed http://crbug.com/1196644 and copied the details from this issue. Please, do feel free to add more details there.
