### ISSUE TITLE
Output application crashes when `orientation !== 'default'` and device is Android 8.0 / API Level 26 / Oreo or lower

### ISSUE THREAD

**Issue by larsmars** [GoogleChromeLabs/bubblewrap#496]
**Describe the bug**
After running bubblewrap build TWA is generated but app will not run after **apk** install on android device or AVD emulator.
**apk** installs fine but **app** will not start:
"APP_NAME keeps stopping, Close app"

**To Reproduce**
1. bubblewrap init --manifest https://my-twa.com/manifest.json
2. bubblewrap build
3. "Generated Android APK at ./app-release-signed.apg"
4. "Generated Android app Bundle at ./app-release-bundle.aab"
5. "Overall result: PASS"
3. Copy apk to android device
4. Install apk (success)
5. Start APP (fail)

**Expected behavior**
App running on android device

**Screenshots**
**PWA Lighthouse test:**
![pwa_light](https://user-images.githubusercontent.com/5154589/114348253-92fdad00-9b66-11eb-882a-9adb6586dcba.png)
**Bubblewrap doctor:**
![doctor_valid](https://user-images.githubusercontent.com/5154589/114347433-39e14980-9b65-11eb-8f54-35029b1fb4b8.PNG)
**Bubblewrap build:**
![build](https://user-images.githubusercontent.com/5154589/114347522-5aa99f00-9b65-11eb-9efd-d20693973663.png)
**App failed to start:**
![172434354_887175795348325_1582872131228340967_n](https://user-images.githubusercontent.com/5154589/114348798-51213680-9b67-11eb-904b-4d5f2f5404db.jpg)

**Desktop (please complete the following information):**
 - Windows 10 Enterprise
 - Chrome 89.0.4389.114 (64-bit)

**Smartphone (please complete the following information):**
 - Device: Xperia ZX
 - OS: Oreo 8.0
 - Browser: Chrome 89.0.4389.105

Bubblewrap version: 1.11.1

**Additional context**
config.json:
`{"jdkPath":"C:\\Users\\MY_USER\\.bubblewrap\\jdk\\jdk8u282-b08","androidSdkPath":"C:\\Users\\MY_USER\\AppData\\Local\\Android\\Sdk"}`

bubblewrap doctor: `Your jdkpath and androidSdkPath are valid.
`

**Comment by andreban** [comment]
I created an Android 8.0 emulator, generated and installed an app generated by Bubblewrap and it all worked as expected. I'm wondering if there's something about your config causing the issue. Would you be able to share the resulting APK and / or `twa-manifest.json`?

**Comment by larsmars** [comment]
The PWA manifest.json on web server?

The App is starting fine (same .apk) on Emulator with Android 11.0
(Pixel 3)

![apk_test](https://user-images.githubusercontent.com/5154589/114383097-70cb5580-9b8d-11eb-9721-c530775cbd84.PNG)

```

{
  "name": "AppName",
  "app_name": "AppName",
  "short_name": "AN",
  "orientation": "portrait",
  "display": "fullscreen",
  "start_url": "./index.html",
  "background_color": "#055471",
  "theme_color": "#055471",
  "categories": ["lifestyle", "travel"],
  "shortcuts": [],
  "icons": [
    {
      "src": "img/icons/icon-20.png",
      "sizes": "20x20",
      "type": "image/png"
    },
    {
      "src": "img/icons/icon-72.png",
      "sizes": "72x72",
      "type": "image/png"
    },
    {
      "src": "img/icons/icon-76.png",
      "sizes": "76x76",
      "type": "image/png"
    },
    {
      "src": "img/icons/icon-96.png",
      "sizes": "96x96",
      "type": "image/png"
    },
    {
      "src": "img/icons/icon-120.png",
      "sizes": "120x120",
      "type": "image/png"
    },
    {
      "src": "img/icons/icon-128.png",
      "sizes": "128x128",
      "type": "image/png"
    },
    {
      "src": "img/icons/icon-144.png",
      "sizes": "144x144",
      "type": "image/png"
    },
    {
      "src": "img/icons/icon-152.png",
      "sizes": "152x152",
      "type": "image/png"
    },
    {
      "src": "img/icons/icon-180.png",
      "sizes": "180x180",
      "type": "image/png"
    },
    {
      "src": "img/icons/icon-192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "img/icons/icon-384.png",
      "sizes": "384x384",
      "type": "image/png"
    },
    {
      "src": "img/icons/icon-512.png",
      "sizes": "512x512",
      "type": "image/png"
    },
    {
      "src": "img/icons/icon-1024.png",
      "sizes": "1024x1024",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/640x960.png",
      "sizes": "640x960",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/768x1024.png",
      "sizes": "768x1024",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/828x1792.png",
      "sizes": "828x1792",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/1024x768.png",
      "sizes": "1024x768",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/1024x1024.png",
      "sizes": "1024x1024",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/Default-2436h.png",
      "sizes": "1125x2436",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/1242x2688.png",
      "sizes": "1242x2688",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/1536x2008.png",
      "sizes": "1536x2008",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/2048x1496.png",
      "sizes": "2048x1496",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/2048x1536.png",
      "sizes": "2048x1536",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/Default-Landscape-2436h.png",
      "sizes": "2436x1125",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/iphone6_splash.png",
      "sizes": "750x1334",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/iphoneplus_splash.png",
      "sizes": "1242x2208",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/2208x1242.png",
      "sizes": "2208x1242",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/iphone5_splash.png",
      "sizes": "640x1136",
      "type": "image/png"
    },
    {
      "src": "img/splashscreens/ipad_splash.png",
      "sizes": "1536x2048",
      "type": "image/png"
    },
    {
      "src": "img/icons/maskable_icon_192.png",
      "sizes": "196x196",
      "type": "image/png",
      "purpose": "maskable"
    },
    {
      "src": "img/icons/maskable_icon_384.png",
      "sizes": "384x384",
      "type": "image/png",
      "purpose": "maskable"
    }
  ],
  "screenshots" : [
    {
      "src": "AppName1.png",
      "sizes": "1280x720",
      "type": "image/png"
    },
    {
      "src": "AppName2.png",
      "sizes": "1280x720",
      "type": "image/png"
    }
  ]
}
```

**Comment by andreban** [comment]
In the directory with the project generated by Bubblewrap, you will see a `twa-manifest.json` file. Also feel free to DM details via on Twitter ([@andreban](https://twitter.com/andreban)), so you don't share publicly.

**Comment by andreban** [comment]
I was able to reproduce this on Android 8.0 (API Level 26). It doesn't happen on API Level 27 and above. The error looks like the following:

```
`04-12 14:46:51.166  6593  6593 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{no.vestfoldsskatter.twa/no.vestfoldsskatter.twa.LauncherActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
```

A workaround for now it to set the `orientation` field in `twa-manifest.json` to `default`, then run `bubblewrap update` and `bubblewrap build` to generate a new APK.

For a more permanent fix, one possible solution is only setting the screen orientation on API 27 and above. Something like:

```java
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.O) {
            setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_USER_LANDSCAPE);
        } else {
            setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);
        }
    }
```

**Comment by larsmars** [comment]
Update here, default is not a valid value for orientation pr: https://developer.mozilla.org/en-US/docs/Web/Manifest/orientation

`"orientation": "default",`

And will show a warning in your console: `Manifest: unknown 'orientation' value ignored.`

**Comment by andreban** [comment]
`twa-manifest.json` will be fine with `default`. To use the same value on both the Web Manifest and `twa-manifest`, you can just use `any`.
