### ISSUE TITLE
App freezes on splash screen if 'AndroidManifest.xml' theme is set to any other than `Theme.Translucent.NoTitleBar`

### ISSUE THREAD

**Issue by dreamunlim** [GoogleChromeLabs/bubblewrap#500]
**Description**
When the 'AndroidManifest.xml' default `Theme.Translucent.NoTitleBar` theme is set to either `Theme.NoTitleBar` or `Theme.Black.NoTitleBar` or `Theme.Light.NoTitleBar` or their `.Fullscreen` variations, my app keeps freezing on splash screen and gets unfrozen only after performing app minimize-restore or device lock-unlock interrupts.

**Steps to reproduce**
1. `bubblewrap init --manifest https://dreamunlim.github.io/manifest.json`
2. Set 'AndroidManifest.xml' default theme to either `Theme.NoTitleBar` or `Theme.Black.NoTitleBar` or `Theme.Light.NoTitleBar` or their `.Fullscreen` variations
3. `bubblewrap build`
4. Launch app and observe it frozen on splash screen

**Expected behavior**
The app does not freeze on splash screen.

**Note**
- The app freezes 9 times out of 10 launches.
- The app does not freeze when the theme is set to `Theme.Translucent.NoTitleBar`

**Desktop**
 - OS: Windows 10 Pro 64-bit
 - Browser Chrome
 - Version 90.0.4430.72 (Official Build) (64-bit)
 - Bubblewrap 1.11.1

**Smartphone**
 - Device: Redmi Note 9 Pro
 - OS: Android 10
 - Browser Chrome
 - Version 90.0.4430.66

**Additional context**
From my observation, the app does not freeze on emulator virtual Android 10 device, but solely on my physical one. I have attached two videos to help with the issue:
1) Shows the actual issue when the theme is set to `Theme.Light.NoTitleBar`:
https://user-images.githubusercontent.com/58615397/114952649-6051fe00-9e5f-11eb-8741-378871afcd97.mp4
2) Shows the issue does not occur with the theme set to `Theme.Translucent.NoTitleBar`:
https://user-images.githubusercontent.com/58615397/114952812-c3439500-9e5f-11eb-894f-7a139b0b34ea.mp4
Also notice on video the device notch stays temporarily transparent on app startup – should I file a separate feature request to paint a device notch in solid black when theme is set to a transparent one?

Thank you!

**Comment by andreban** [comment]
The application generated by Bubblewrap is working as intended and supporting manual modifications to the Android project Bubblewrap outputs is outside the scope of Bubblewrap. The best place to file this issue is http://github.com/GoogleChrome/android-browser-helper.
