### ISSUE TITLE
[Windows] Error on installing buublewrap when using "npm install -g @bubblewrap/cli"

### ISSUE THREAD

**Issue by Abhishek150190** [GoogleChromeLabs/bubblewrap#506]
<img width="948" alt="Capture1" src="https://user-images.githubusercontent.com/38033939/115462534-61f93880-a248-11eb-892a-a8eb298c1993.PNG">
<img width="948" alt="Capture2" src="https://user-images.githubusercontent.com/38033939/115462544-645b9280-a248-11eb-966f-0c262e8f3d34.PNG">
<img width="948" alt="Capture3" src="https://user-images.githubusercontent.com/38033939/115462553-658cbf80-a248-11eb-911c-4486a15fc927.PNG">

**Comment by andreban** [comment]
Can you confirm the operating system and NodeJs version? It looks like Windows, but which version? Node seems to be 12.16.2. Is that correct?

Overall, this is an issue installing the [canvas](https://www.npmjs.com/package/canvas) dependency. It's behaviour is to download a pre-compiled package and, if that fails, build it locally.

For some reason, It seems to be failing to download the pre-compiled package - I don't see any errors explaining why that is the case though.

It is also unable to build locally.

**Comment by Abhishek150190** [comment]
Windows 10 and Nodejs version is 12.16.2

**Comment by andreban** [comment]
Just checked on Windows 10 / Node v14.16.0 - Wondering if that's specific to Node 12. Would you mind checking if 14 works?
![Capture](https://user-images.githubusercontent.com/1733592/115776894-8ec66080-a3ac-11eb-8421-7106e599b8c0.PNG)

**Comment by andreban** [comment]
Installed Node 12.16.2 via [`nvm-windows`](https://github.com/coreybutler/nvm-windows/). It's working as intended there as well.
![Capture](https://user-images.githubusercontent.com/1733592/115778381-7d7e5380-a3ae-11eb-99d2-2dbc520f4ee5.PNG)

@Abhishek150190 any idea of what could be different on your system that could be causing this?

**Comment by Abhishek150190** [comment]
@andreban Its not working with 12.6.2 but when I checked with node 14.6.1 its working
Moreover I couldn't find any different specs in my system that are blocking node 12.16.2 to install bubblewrap.
<img width="675" alt="bubblewrap" src="https://user-images.githubusercontent.com/38033939/115832030-05587200-a430-11eb-86e2-2e4f7c90bf8e.PNG">

**Comment by Abhishek150190** [comment]
I think we can close this issue as when I updated node to 14.16.2 its working absolutely fine , if you are ok with it
