### ISSUE TITLE
The app icon is stretched 

### ISSUE THREAD

**Issue by Abhishek150190** [GoogleChromeLabs/bubblewrap#509]
![Screenshot_20210424-204755__01](https://user-images.githubusercontent.com/38033939/115963834-c6651200-a53e-11eb-9f07-b6a48bb75bb3.jpg)

Here you can see their is no padding though I have used and generated the sized 36x36 and 48x48 for smaller sizes and 192x92 and 512x512 .
Can you please suggest what might be the issue here or how I can resolve it @andreban , as it will be really helpful

**Comment by andreban** [comment]
@Abhishek150190 there's enough information to understand what's happening. Could you provide:

- What's the expected behaviour (a screenshot would be great)
- URL to the web manifest

**Comment by Abhishek150190** [comment]
@andreban The issue is resolved , thanks !!!

**Comment by ttimot24** [comment]
@Abhishek150190 what was the problem? I have the same issue
