### ISSUE TITLE
Dark (night) mode with TWA/PWA

### ISSUE THREAD

**Issue by juho-hanhimaki** [GoogleChromeLabs/bubblewrap#51]
Is there a way to achieve light/dark (day/night) theming with TWA?

My TWA/PWA uses the prefers-color-scheme media query to adjust the CSS theming as requested by the OS/user. However the llama-pack and TWA samples I have seen accept only single color/colorPrimary and color/navigationColor which makes status bar and navigation bar ignore any OS light/dark theme.

**Comment by andreban** [comment]
I don't see a reason why [`setColorSchemeParams`][1] and [`setColorScheme`][2] wouldn't work as expected on TWAs. We'd need to add support for it in [`android-browser-helper`][3] before adding this to `llama-pack`.

On the llama-pack side, I don't think there are fields dark-theme that can be extracted from the Web Manifest, but we can either generate the values from the light themes or ask users to provide colors for the dar theme (defaulting to using the same as the light theme).


[1]: https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsIntent.Builder.html#setColorSchemeParams(int,%20androidx.browser.customtabs.CustomTabColorSchemeParams)

[2]: https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsIntent.Builder.html#setColorScheme(int)

[3]: https://github.com/GoogleChrome/android-browser-helper

**Comment by andreban** [comment]
Created an issue for android-browser-helper: https://github.com/GoogleChrome/android-browser-helper/issues/50

**Comment by andreban** [comment]
Changed from `bug` to `enhancement`, as this is not currently supported in the Web Manifest specification.

**Comment by Stevie-Ray** [comment]
Hi @andreban in [1.2.0](https://developer.android.com/jetpack/androidx/releases/browser#1.2.0)  `CustomTabColorSchemeParams` is supported how can i enable this for my TWA/PWA?

**Comment by andreban** [comment]
Closed via #287

**Comment by Benfordy** [comment]
Hi All,
In Samsung devices the Samsung WebView is used with an auto-dark mode that invert everything is a strange way, it is not using the regulars angular material light/dark theme in the same way that chrome does it. What can be done about that?
