### ISSUE TITLE
The splash screen does not appear when Samsung Internet is the default browser app.

### ISSUE THREAD

**Issue by yahao87** [GoogleChromeLabs/bubblewrap#512]
**Describe the bug**
The splash screen does not appear when Samsung Internet is the default browser app.
When playing A2HS on Samsung Internet, the splash screen works. But it doesn't work in bubblewrap.

**To Reproduce**
1. Go to setting > application > default application > browser
2. Browser app > Samsung internet

**Expected behavior**
Splash screen works.

**Screenshots**
Nope

**Smartphone (please complete the following information):**
 - Device: Android phones including Galaxy 10
 - OS: Android
 - Browser Samsung Internet
 - Version 14.0.1.62

**Additional context**
The following message is displayed in logcat.
`W/SplashScreenStrategy: Provider com.sec.android.app.sbrowser doesn't support splash screens`

**Comment by andreban** [comment]
The splash screen generated via A2HS and the one used by Trusted Web Activity are unrelated.

This seems to be a feature request for Samsung Internet to add support for Splash Screens in the Trusted Web Activity implementation. 

I'd recommend starting a conversation on their Developer Forum at https://forum.developer.samsung.com/c/samsung-internet/25.

**Comment by andreban** [comment]
Closing this,  as not feasible from a Bubblewrap perspective.
