### ISSUE TITLE
Project generation should fail if `iconUrl` is not available

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/bubblewrap#534]
It's not possible to generate a valid project if `iconUrl` is not a valid URL.

**Comment by nohe427** [comment]
Do you want a regex validating that `iconUrl` is a url or do you want to run the icon check like you have done in a [previous CL](https://github.com/GoogleChromeLabs/bubblewrap/commit/e54a67ead0615720c7a900e1aa1651489ee76105) at project generation time?

**Comment by andreban** [comment]
We can probably just [create a new URL](https://nodejs.org/api/url.html#url_new_url_input_base) and catch the error.

**Comment by nohe427** [comment]
@andreban - This looks to already be implemented with the code that exists today:
![image](https://user-images.githubusercontent.com/3211589/126014225-d5e49456-f787-4734-aea8-fa9968fbdf02.png)

This is running from the init step. Is there another place or issue that you were thinking?

**Comment by andreban** [comment]
Yes, init does the proper check. However, the developer can manually update twa-manifest.json and then run update. I'm not sure we do a proper check there.

**Comment by andreban** [comment]
Closed via #565
