### ISSUE TITLE
How to create Splash Screen

### ISSUE THREAD

**Issue by mghatiya** [GoogleChromeLabs/bubblewrap#535]
Hi,

I created my TWA powered App using the https://github.com/GoogleChromeLabs/svgomg-twa . I understand that it is now called Bubblewrap. I didn't realise it earlier, otherwise I would have used this directly.

I have somehow now managed to get my app running and live on the play store.

However, I don't know how to add splash screen. I couldn't find any in the svgomg or ilama or bubblewrap documentation, but I see people have managed to add splash screens.

I tried to add an activity for splash screen as that's what internet told me, but I ran into several build errors.

I am not really a techie, so please go easy.

Thanks,
Mukesh

**Comment by andreban** [comment]
I'd recommend rebuilding your application with Bubblewrap - Make sure you use the **same package name and signing keys** and you'll be able to upload the version on Play with that one. The splash screen is added by default in this case.
