### ISSUE TITLE
TWA forces reload of base URL on every open

### ISSUE THREAD

**Issue by david-buck** [GoogleChromeLabs/bubblewrap#537]
I don't think this is a bug in Bubblewrap, because I've seen other TWAs handle this fine:

If I navigate away from the base URL of my app, switch apps, then switch back to my TWA, the view briefly shows the previous state, then reloads back to the base URL.

This differs from what happens with the installed PWA version of my app. 

Is there something to look out for in the way the wrapped browser behaves when focussed? 

Thanks

**Comment by andreban** [comment]
Hi David,

If you enable alphaDependencies in `twa-manifest.json`, then run `bubblewrap update` followed by `bubblewrap build`, does it still happen? 

```json
  "alphaDependencies": {
    "enabled": true
  },
```

This will enable the alpha version of https://github.com/GoogleChrome/android-browser-helper/, which is used by Bubblewrap and has a fix for what I believe is the same issue.

**Comment by david-buck** [comment]
Thank you, this fixed it perfectly.
