### ISSUE TITLE
Add a warning for the Play Family policy when building the application

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/bubblewrap#545]
A Trusted Web Activity application may be incompatible with the [Play Family policy](https://web.dev/using-a-pwa-in-your-android-app/#quality-criteria). Let's add this warning to the `build` command, so developers get this information even if missed on the docs.

**Comment by nohe427** [comment]
@andreban - I am thinking about adding this. Can you explain more about what this should look like? The way I am thinking about implementing this is as follows:

When the `bubblewrap build` command is called, show a prompt that asks the user to confirm that they have read the Play Family Policy and maybe inline the policy, and then hit yes or no on accepting that their TWA may be in violation if they target children under the age of 13. Then if they hit yes, run build and write to twa-manifest.json so its only a one time prompt. Thoughts?

**Comment by PEConn** [comment]
I'm not sure there should be something blocking on user input in `build`. If we want to block on user input, I think `init` is the best place for it.

**Comment by andreban** [comment]
I don't think we need to block the build. We can just output a warning. Something in the lines of:

`WARNING: Trusted Web Activities are currently incompatible with applications targeting children under the age of 13. Check out the Play for Families policies to learn more`

I agree that `init` may be a better place for this, since we warn the developer earlier.
