### ISSUE TITLE
is it possible to access sd card ?

### ISSUE THREAD

**Issue by rabinhod** [GoogleChromeLabs/bubblewrap#551]
i want to download some file and save them in storage and prevent download in next time
is it possible with pwa and twa ?

**Comment by andreban** [comment]
Bubblewrap or Trusted Web Activity won't give the app control over the filesystem.

There are, however, options you could explore in the web application:

- You could cache the file using the [cache API](https://web.dev/cache-api-quick-guide/). Even though it won't preventing saving a new version of the file, it will avoid re-downloading the entire file.
- On Desktop, you can explore the [File System access API](https://web.dev/file-system-access/). It's not available on mobile though.
