### ISSUE TITLE
PWA Builder CloudAPK (Bubblewrap) zipalign issue "Failed. Status code 500, Error: Internal Server Error, Details: Error generating app package"

### ISSUE THREAD

**Issue by bryantvu** [GoogleChromeLabs/bubblewrap#552]
Hello,

I'm trying to get PWA Builder CloudAPK running.
https://github.com/pwa-builder/CloudAPK

I'm getting an error generating an Android package with just the default settings. PWA Builder team did note that I was using the correction SDK version (30.0.3) and suggested that I seek help from the Bubblewrap team instead. Any ideas on what's going on here?
``
Failed. Status code 500, Error: Internal Server Error, Details: Error generating app package: Error: Command failed: "/home/ubuntu/api/CloudAPK/android-sdk/build-tools/30.0.3/zipalign" -v -f -p 4 /tmp/pwabuilder-cloudapk--24177-thSWAhVabhJC/app/build/outputs/apk/release/app-release-unsigned.apk /tmp/pwabuilder-cloudapk--24177-thSWAhVabhJC/app-release-unsigned-aligned.apk
``

**Comment by andreban** [comment]
Recent versions of the Gradle plugin will automatically zipalign the APK, and calling zipalign in those cases is redundant. See [this issue](https://b.corp.google.com/issues/162117652#comment12). To reflect this, the Bubblewrap CLI only [verifies the APK is zipaligned](https://github.com/GoogleChromeLabs/bubblewrap/blob/d8019d0aef42d64b0590bf223d22b4ad0f5e0575/packages/cli/src/lib/cmds/build.ts#L117-L123). ClouldAPK seems to be still calling `zipalign` [here](https://github.com/pwa-builder/CloudAPK/blob/dbe52dda058e808b9f6f694095ffd0c4b05ebf12/build/bubbleWrapper.ts#L136-L145)

**Comment by bryantvu** [comment]
Thanks for getting back so quickly Andre, I've informed the PWAB team of this change.

**Comment by JudahGabriel** [comment]
FYI, we've updated our side of this as well. I believe you can close this.
