### ISSUE TITLE
Google Play Billing

### ISSUE THREAD

**Issue by rastarr** [GoogleChromeLabs/bubblewrap#554]
Very confusing this.

We've published a number of TWAs into the PlayStore already.
The major thing missing for us is the inclusion of Google Play Billing since we also need to monetise our business. Sadly, we've needed to tell our customers that they are unable to process any membership upgrades in the PlayStore app since we can't use current payment methods.

When is Play Billing coming to TWAs?

**Comment by andreban** [comment]
The Digital Goods API is currently in Origin Trial and enables using Play Billing with Trusted Web Activity. You can learn more about it in [this article](https://developer.chrome.com/docs/android/trusted-web-activity/receive-payments-play-billing/). The team wants to hear feedback from developers on the API and the Origin Trial is a great way to do it.
