### ISSUE TITLE
Unable to change launcherName from Android Studio

### ISSUE THREAD

**Issue by mghatiya** [GoogleChromeLabs/bubblewrap#603]
**Describe the bug**
I used Bubblewrap to create my TWA. I want to change the launcherName or the "Short Name" of the app now, but unable to do so.

**To Reproduce**
1. Init a TWA using Bubblewrap and give certain name in for "Short Name".
2. Once app has been prepared, open Android studio, open build.gradle of the module (app) and modify "launcherName" in "twaManifest"
3. Build the app and install on the phone
4. App will show the Short Name that was given at the time of "init" and not the modified one.

**Expected behavior**
I was hoping that modifying launcherName in twaManifest will update the Short Name, but it is not doing so.

Am I right in my approach on how I am trying to do so or is there a more correct way of doing it?

**Comment by andreban** [comment]
Closing this, as supporting editing projects in Android Studio is outside the scope of Bubblewrap.

**Comment by mghatiya** [comment]
Well, I tried reinstalling multiple times and also fresh install on a new phone and it is still showing the old value.

I understand that it might be out of scope of Bubblewrap to look at edits made via Android Studio.

But how will a person make a change? If it is not working on editing twaManifest, then probably the project is being made incorrectly. Or maybe Bubblewrap puts the "launcher name" at some other place or Android builder picks it up not from twaManifest but some other place which is not obvious or known to people like me.

Maybe a documentation should be there as to where to make the change for twa to be updated? It is not so much about Android studio, but the project in itself as to where does the 'launcher name' property really gets picked up from.
