### ISSUE TITLE
bubblewrap is not generating assetlinks automatically

### ISSUE THREAD

**Issue by ImBIOS** [GoogleChromeLabs/bubblewrap#604]
**Describe the bug**
As in tutorial or demo on youtube by Google Developer, the bubblewrap-cli is generating assetlinks.json automatically with its correct fingerprint signed by bubblewrap. It makes my TWA is not verified correctly because I use the fingerprint from the play store due to bubblewrap not generating it. Then, I need to find a workaround to solve this, then I find this Google Developer Demo useful app called "Asset Links Tool Android app".

The bubblewrap should be generating the assetlinks.json automatically, right? But why is my bubblewrap didn't?

**To Reproduce**
1. Init a bubblewrap project
2. Build it
3. Voila! assetlinks.json is not generated automatically.

**Expected behavior**
Bubblewrap should be generating assetlinks.json with its signed sha256 fingerprint of bubblewrap.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 (OS Build 19043.1237)
 - Chrome Browser
 - Version 94.0.4606.71 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Vivo Y71
 - OS: Android 8.1
 - Google Chrome
 - Version 94.0.4606.71

**Comment by andreban** [comment]
The Play Store requires apps to use Play Signing nowadays. The app is now signed by the store, and the key used is different from the one used to upload the app. As a consequence, Bubblewrap is now unable to auto-generate the assetlinks file, as it would use the wrong signature.

We have added a `fingerprint` command that helps managing the keys and generating the assetlinks file: https://github.com/GoogleChromeLabs/bubblewrap/tree/main/packages/cli#fingerprint
