### ISSUE TITLE
JDK version not supported. JDK version 1.8 is required

### ISSUE THREAD

**Issue by mishrasatyam** [GoogleChromeLabs/bubblewrap#607]
**Describe the bug**
JDK version not supported. JDK version 1.8 is required.
java -version output:
`openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2, mixed mode)
`
**To Reproduce**
1. bubblewrap init
2. Entering Path to your existing JDK
3. Error : `JDK version not supported. JDK version 1.8 is required`
**Expected behavior**
Support jdk version 11.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by andreban** [comment]
This is working as intended, as JDK 1.8 is a requirement from the Android command-line tools (see https://github.com/GoogleChromeLabs/bubblewrap/tree/main/packages/cli#get-the-java-development-kit-jdk-8).  There's nothing Bubblewrap can do to change support, unless the Android SDK changes it.
