### ISSUE TITLE
Navigation bar does not disappear on Huawei Browser

### ISSUE THREAD

**Issue by bryantvu** [GoogleChromeLabs/bubblewrap#608]
After setting everything up for the assetlinks.json on my test website and APK signing, I was able to get the navigation bar to disappear when the TWA was using Chrome Browser. However, the navigation bar does not disappear when the Huawei Browser was used instead.

Is this supposed to happen? Is the behavior of the navigation bar due to a feature with TWA or Chrome Browser?

**Comment by andreban** [comment]
Trusted Web Activity needs the target browser to support removing the navigation bar. I haven't tested it, but It sounds like the Huawei Browser doesn't support the protocol and removing the URL bar. Is the browser available on the Play Store or only on Huawei devices?

**Comment by bryantvu** [comment]
That might be the case. The browser is only available on Huawei devices through AppGallery. Here's the APK I retrieved from my device using ADB. 
https://drive.google.com/file/d/1R9MLeqcPuT0FWfhd49_8Mkv2gCco8vIT/view?usp=sharing

**Comment by andreban** [comment]
Closing this issue, as this is a feature request for the Huawei Browser to support Trusted Web Activity, outside the scope of Bubblewrap.
