### ISSUE TITLE
Google Play Integration

### ISSUE THREAD

**Issue by nohe427** [GoogleChromeLabs/bubblewrap#618]
**Is your feature request related to a problem? Please describe.**
An easier path for a completed Bubblewrap project to be uploaded to an existing Google Play Store listing.

**Describe the solution you'd like**
`bubblewrap play ${cmd}`

**Describe alternatives you've considered**
none

**Additional context**
already inflight on the `playExperiment` branch.

Current Work to be completed:

- [x] #619
- [x] #622
- [x] #623
- [ ] Fix retain command to ensure no duplicates exist within the manifest.

Once these are completed, the Google Play Integration could be considered for merging into the main branch.

**Comment by andreban** [comment]
@nohe427 it seems the PR for this has been merged. Can this issue be resolved?
