### ISSUE TITLE
Unable to fetch/read manifests on Win 11

### ISSUE THREAD

**Issue by aashutoshrathi** [GoogleChromeLabs/bubblewrap#625]
**Describe the bug**
Unable to read the manifests.

**To Reproduce**
1. Install bubblewrap/core and bubblewrap/cli globally.
2. Do `bubblewrap init --manifest=https://doom-fire.com/manifest.json` 
3. Let Bubblewrap install the SDK
4. Give the path to your Android SDK (Windows: `C:\Users\{USERNAME}\AppData\Local\Android\sdk`)
5. It exits after printing 
```  
Initializing application from Web Manifest:
        -  https://doom-fire.com/manifest.json
```

**Expected behavior**
It should initiate a Bubblewrap app from manifest

**Screenshots**

![image](https://user-images.githubusercontent.com/21199234/142221751-3d94832e-14eb-422e-82a6-7909c0e1d011.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave

**Additional context**
None

**Comment by andreban** [comment]
Can you check if using `bubblewrap init --manifest="https://invoicify.netlify.app/manifest.json" --fetchEngine="node-fetch"` on your PWA change anything? This should change from using the `fetch-h2` to `node-fetch`.

**Comment by aashutoshrathi** [comment]
@andreban changing `fetchEngine` worked!
What might be the issue at my end?

**Comment by andreban** [comment]
I'm not sure exactly what the issue is - any chance there's a proxy or a VPN that could be interfering with the connection?

**Comment by aashutoshrathi** [comment]
No! there was no VPN or connection interference, the manifest was accessible at the same time in the browser, as I described on the call also.
