### ISSUE TITLE
Do not prompt a question to a user about JDK installation if he tries to update the config using updateConfig command

### ISSUE THREAD

**Issue by SJShip** [GoogleChromeLabs/bubblewrap#629]
**Describe the bug**
I'm trying to use the bubblewrap CLI in the CI\CD pipeline where I plan to install it on the agent as a separate step. In order to reduce the number of user inputs, I'd like to update the config and specify the path for JDK and Android SDK on the machine using **updateConfig** command. But instead of writing new values to the config.json file the bubblewrap CLI starts asking the question about whether I need to install JDK.

**To Reproduce**
1. npm install -g @bubblewrap/cli
2. bubblewrap updateConfig  --jdkPath="/path-to-jdk" --androidSdkPath="/path-to-androidSdk"

**Expected behavior**
It should update the config without asking a user about the JDK installation

**Comment by nohe427** [comment]
If you write the file yourself at `~/.bubblewrap/config.json` you won't get prompted for installing the JDK and Android SDK. The file looks something like : 
```
{"jdkPath":"/path", "androidSdkPath":"/path"}
```
Hope this helps!

**Comment by SJShip** [comment]
Thank you @nohe427!
