### ISSUE TITLE
Share_Target is not correctly recognized / processed

### ISSUE THREAD

**Issue by mmffo** [GoogleChromeLabs/bubblewrap#633]
Hello.

After several weeks of analysis and testing, I give up :(

I created my app with https://www.pwabuilder.com and come from https://github.com/pwa-builder/PWABuilder/issues/2291

Problem: My App shows as an share-option on the mobile-share-menu, the TWA is started, but the data is not shared. (Neither images nor text-data).

When sharing: **The app always starts with the "start_url" instead of the "share_target" > "action": "/lists/" URL and Shared data will not be received. No incoming POST-Request.**

Everything works fine via PWA "Add to Home Screen". I can process the incoming POST request via PHP.

PWA:
https://de.fridalist.com/
https://de.fridalist.com/manifest.json
https://de.fridalist.com/.well-known/assetlinks.json

On Google: https://play.google.com/store/apps/details?id=com.fridalist.de.twa

My tests with the package from pwabuilder.com:
Installation of the downloaded Android package on my smartphone -> sharing not possible.
Source code compiled with Android Studio and started on emulator -> sharing not possible.
AAB file uploaded to Google Play and the app installed on the smartphone -> sharing not possible.

Can you please help me fix it?

**Comment by mmffo** [comment]
**// Ensure action is an absolute URL.**

That was the solution! :-)

**Comment by anuragvohraec** [comment]
> **// Ensure action is an absolute URL.**
> 
> That was the solution! :-)

Not working yet! It doesnot work for me this way.

**Comment by SaKrAt91** [comment]
Also doesn't work. Redirects to the main url. Absolute path specified, no difference.
Are there any other solutions or at least an example of a working setup?

**Comment by Sudeep040** [comment]
Any update

**Comment by Sudeep040** [comment]
@SaKrAt91 @anuragvohraec  any solution on this

**Comment by anuragvohraec** [comment]
> [@SaKrAt91](https://github.com/SaKrAt91) [@anuragvohraec](https://github.com/anuragvohraec) any solution on this

There seems to be no solution for this. The work around for this is that if its hitting your root url.
In the post message body itself you need to have some feild to distinguish between a regular POST request and a Shared_target POST request.

**Comment by Sudeep040** [comment]
@anuragvohraec can you send me example how did you do that. It will be very helpful

**Comment by Sudeep040** [comment]
I tried adding manifest file and sevice worker. Still it's not working to recive share_target post url is not getting on root url could give example for same
