### ISSUE TITLE
Bubblewrap init producing cryptic characters

### ISSUE THREAD

**Issue by jamesmart77** [GoogleChromeLabs/bubblewrap#635]
**Describe the bug**
I am running the following command to stage my app for building and deployment with bubblewrap and am now receiving these very strange cryptic errors. This was not a problem a few days ago. See screenshot for errors.

```bubblewrap init --manifest https://jamesmart77.github.io/justScripture/manifest.json```

**To Reproduce**
1. Nvm use 14.15.1
2. Install globally -- `npm i -g @bubblewrap/cli`
3. Bubblewrap init...

**Expected behavior**
When initalizing a project, Bubblewrap will download the Web Manifest and ask you to confirm the values that should be used when building the Android project.

**Screenshots**
![image](https://user-images.githubusercontent.com/29242164/148666282-e6cb81c9-cd9a-4ae4-9ef6-4baa1e504e4e.png)

**Additional Notes**
Notice the strange LIBERTY LIBERTY LIBERTY lines in the screenshot after executing the `bubblewrap init` command...

**Comment by floscher** [comment]
See https://github.com/Marak/colors.js/issues/285 and https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/

Somewhere the NPM package `colors` is used in a version > `1.4.0`, which is printing stuff in an infinite loop. You need to pin that package to version `1.4.0`.

**Comment by andreban** [comment]
Thanks for flagging the issue, @amesmart77 and thanks for the solution, @floscher. The version has been pinned and this should be fixed in 1.15.0

**Comment by PEConn** [comment]
Andre, does this mean that bubblewrap init is calling `npm install` somewhere where potentially we could be calling `npm ci` instead?
