### ISSUE TITLE
White screen after ending session in TWA 

### ISSUE THREAD

**Issue by Junn3r** [GoogleChromeLabs/bubblewrap#652]
My PWA is already in PLAYSTORE and it's working well, but when i download it, sign in and then end my session, the screen goes white, and i'd like to know if the issue its on the bubblwrap deployment or if it's on my pwa side? or maybe the new google necessity to upload apps in .aab format?
I'll attach a video showing you what's happening...

https://user-images.githubusercontent.com/45378130/154337455-c1b35c17-e4c8-4b7d-b84b-9d534272cf5f.mp4

**Comment by andreban** [comment]
I'm not completely sure about what's happening on the video.  A couple of things to keep in mind:

- Bubblewrap is just a generator for the Android application. So, unlikely that behaviour is related to Bubblewrap at all.
- Mostly, the Trusted Web Activity is a setup on how the site is loaded. There may be some awkward interaction between the TWA and the site.
- But my guess is that something is happening inside the PWA, that is rendering an empty HTML. I'd first try using Chrome DevTools connected to the Android device to understand what's happening.

Closing this as it's unrelated to Bubblewrap.
