### ISSUE TITLE
Can't use CLI - Trying to install JDK or specifying the path manually both fail

### ISSUE THREAD

**Issue by matronator** [GoogleChromeLabs/bubblewrap#655]
**Describe the bug**
When I run `bubblewrap init --manifest <URL>` it asks if I want to install JDK or specify path.

If I choose to install, it throws the following error:

```
Downloading JDK 8 to /Users/matronator/.bubblewrap/jdk
Downloading the JDK 8 Sources...
 >> [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | 0k of 132940k

cli ERROR Server responded illegally with a redirect code but missing 'location' header
```

And when I choose to specify the path myself, now it throws this error:

```
? Path to your existing JDK: /Applications/Android Studio.app/Contents/jre/Contents/Home
>> Error reading the "release" file for the JDK at "/Applications/Android Studio.app/Contents/jre/Contents/Home", with error: Error: ENOENT: no such file or
 directory, open '/Applications/Android Studio.app/Contents/jre/Contents/Home/Contents/Home/release' 
```

But when I check in the folder, the file `release` is there and I can open it without issues. So basically I just can't use this tool at all since both options for the JDK throw errors. I tried copying the JDK to the `.bubblewrap` folder manually, but it still asks whether to install or locate...

**To Reproduce**
1. Run `bubblewrap init --manifest <URL>`
2. `? Do you want Bubblewrap to install JDK? (Y/n)`
2a. Type `y`
2b. Type in path to the JDK
3. See error

**Expected behavior**
Install or locate the JDK successfully and proceed to the next step (download `manifest.json` and generate the app).

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version macOS 12.2.1

**Additional context**
Also, why is it trying to install JDK 8? Why not the latest (11 I think)?

**Comment by NicoHood** [comment]
I am running into the exact same issue. It does not want to use my jdk8. Any ideas why?

**Comment by NicoHood** [comment]
I think it is an issue of Arch Linux: https://bugs.archlinux.org/task/74073
