### ISSUE TITLE
Improve consistency between WebAPK (PWA) and TWA Splash Screens

### ISSUE THREAD

**Issue by abdonrd** [GoogleChromeLabs/bubblewrap#66]
The generated splash screen is not very faithful to the original PWA splash screen.

Also, I see that the splash use the normal icon. I think it would be nice to use the maskable icon.

| PWA splash | Llama Pack splash |
|-------------|--------------------|
| ![Screenshot_20200115-114932](https://user-images.githubusercontent.com/1007051/72428160-6acda580-378d-11ea-907b-33fcf2e0382c.png) | ![Screenshot_20200115-115016](https://user-images.githubusercontent.com/1007051/72428165-6dc89600-378d-11ea-870d-6a47c3be2f16.png) |

**Comment by abdonrd** [comment]
Probably another issue, but also note that the bottom bar color is different.

**Comment by andreban** [comment]
I think the issue is about making the TWA Splash Screen and the PWA (powered by WebAPKs) more consistent by default (developers can tweak it).

A non-exhaustive list of differences:
- Image sizes
- Navigation Bar Colors
- Text with App Name at the bottom (not currently supported in TWAS)

CC'ing @b1tr0t for thoughts on consistency

**Comment by PEConn** [comment]
Are the differences in the way that llama-pack interprets the web app manifest or in the way that Chrome/AndroidX construct the splash screens?

**Comment by PEConn** [comment]
(also, I've got to admit that I personally prefer the Llama pack splash screen)

**Comment by andreban** [comment]
- Navigation Bar color can definitely be changed in llama-pack (default the color to #000000).
- I think the same is true for icon size, but need to confirm.

**Comment by andreban** [comment]
For completeness, there's also a difference on the Navigation Bar divider, when comparing WebAPKs to TWA. This is being tracked on the Chrome side, on this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1021436
