### ISSUE TITLE
Multi-origin TWA opens page in a custom tab with URL bar after navigating to another domain.

### ISSUE THREAD

**Issue by SJShip** [GoogleChromeLabs/bubblewrap#661]
**Describe the bug**
I'm apologies in advance because it might be a not a bug but just a wrong configuration. 

Given a web application with multiple sub-domains. The user is able to navigate from one subdomain to another. The number of subdomains is not fixed (a new subdomain can be created during the user registration). I'm trying to implement TWA with using of wildcards in the host name of the intent filter (e.g. *.example.com). For that purpose I've adjusted app\build.gradle file with the line below:

` resValue "string", "hostName", "*.example.com"`

And also I've created the correct /.well-known/assetlinks.json endpoint for each subdomain and root domain.

It was enought to make it workable on my personal device, and even on android emulator. I could easily switch between subdomains without having url bar. But it's not the case for other people. It seems the solution does not provide deterministic result. 

Could you please suggest how to correctly implement wildcard approach for TWA subdomains?

**To Reproduce**
1. bubblewrap init --manifest https://app.example.com/twa/manifest
2. adjust app\build.gradle file and specify hostName as  "*.example.com"
3. bubblewrap build
4. install signed apk on the device
5. the user observes the URL bar after navigating from the first subdomain to another.

**Expected behavior**
A user does not see custom tabs with URL bar.

**Comment by andreban** [comment]
I don't think a wildcard approach is currently supported. @PEConn may be able to confirm.

**Comment by PEConn** [comment]
Yeah, we don't currently support wildcard subdomains - when you launch the browser, you need to provide a list of all the subdomains you want verification with.

**Comment by SJShip** [comment]
@PEConn , thanks for sharing this.
