### ISSUE TITLE
Error on init project

### ISSUE THREAD

**Issue by ofirrabi99** [GoogleChromeLabs/bubblewrap#662]
I trying to initialize new project with web manifest and get an error.

This is the command:
bubblewrap init --manifest=https://zuzu.prat.idf.il/manifest.json
Do you want Bubblewrap to install JDK?  Y

This is the error: 
cli ERROR Server responded illegally with a redirect code but missing 'location' header

Thank you

**Comment by BigTimbo** [comment]
Same issue for me

**Comment by andreban** [comment]
Can you provide details on the version? Is that on the version installed from NPM or from `master` on the repo?

**Comment by andreban** [comment]
Duplicate to #653

**Comment by andreban** [comment]
This should be fixed in v1.16.0. Please, re-open if the issue persists.
