### ISSUE TITLE
Add utm query parameters to internal pwa links

### ISSUE THREAD

**Issue by NicoHood** [GoogleChromeLabs/bubblewrap#667]
**Is your feature request related to a problem? Please describe.**
I'd like to track which links are clicked by the app and which not. It would be nice to add utm query parameters for that.

**Describe the solution you'd like**
Here is a possible solution described:
https://stackoverflow.com/questions/54580414/how-can-i-detect-if-my-website-is-opened-inside-a-trusted-web-actvity

**Describe alternatives you've considered**
If there is any other option to track if the site is running via app instead of a browser, that'd be nice. Maybe a special user agent or so.

**Additional context**
https://ga-dev-tools.web.app/campaign-url-builder/
(This can be used with matomo as well)

**Comment by andreban** [comment]
Modifying links in the web app is outside the scope of this project, as it focuses on  building / launching the app. The link posted would be the best way to do it, indeed.

**Comment by NicoHood** [comment]
I will use the new start url:

```
"startUrl": "/?utm_medium=app&utm_source=android&utm_campaign=app-launch-count",
```
