### ISSUE TITLE
App opens like a link with url bar at the top, rather than like an android app

### ISSUE THREAD

**Issue by Pika-Pool** [GoogleChromeLabs/bubblewrap#668]
**Describe the bug**
After installing the generated apk, the app opens like a normal link in the Google app rather than an android app. It has a url bar at the top

**To Reproduce**
use bubblewrap cli to generate apk using the following manifest:

Note: The links are fake
```
// twa-manifest.json

{
  "packageId": "app.web.facpro.twa",
  "host": "facpro.web.app",
  "name": "FACPRO - Faculty Research Progress",
  "launcherName": "FACPRO",
  "display": "fullscreen",
  "themeColor": "#FFFFFF",
  "navigationColor": "#000000",
  "navigationColorDark": "#000000",
  "navigationDividerColor": "#000000",
  "navigationDividerColorDark": "#000000",
  "backgroundColor": "#FFFFFF",
  "enableNotifications": true,
  "startUrl": "/",
  "iconUrl": "https://facpro.web.app/logo512.png",
  "maskableIconUrl": "https://facpro.web.app/maskable_icon_x512.png",
  "splashScreenFadeOutDuration": 300,
  "signingKey": {
    "path": "/path/to/android.keystore",
    "alias": "android"
  },
  "appVersionName": "1",
  "appVersionCode": 1,
  "shortcuts": [],
  "generatorApp": "bubblewrap-cli",
  "webManifestUrl": "https://facpro.web.app/manifest.json",
  "fallbackType": "customtabs",
  "features": {},
  "alphaDependencies": {
    "enabled": false
  },
  "enableSiteSettingsShortcut": true,
  "isChromeOSOnly": false,
  "orientation": "default",
  "fingerprints": [],
  "additionalTrustedOrigins": [],
  "retainedBundles": [],
  "appVersion": "1"
}
```

```
//manifest.json of website

{
  "short_name": "FACPRO",
  "name": "FACPRO - Faculty Research Progress",
  "icons": [
    {
      "src": "favicon.ico",
      "sizes": "64x64 32x32 24x24 16x16",
      "type": "image/x-icon"
    },
    {
      "src": "logo192.png",
      "type": "image/png",
      "sizes": "192x192"
    },
    {
      "src": "logo512.png",
      "type": "image/png",
      "sizes": "512x512"
    },
    {
      "src": "maskable_icon_x512.png",
      "type": "image/png",
      "sizes": "512x512",
      "purpose": "any maskable"
    }
  ],
  "start_url": ".",
  "display": "standalone",
  "theme_color": "#ffffff",
  "background_color": "#ffffff"
}
```

**Expected behavior**
The app should open like an normal android app, without the url bar

**Screenshots**
Screenshot of app with url bar (in android emulator)
![Screenshot of app with url bar (in android emulator)](https://i.stack.imgur.com/apz3h.png)

Screenshot of app with url bar (in physical device OnePlus 7)
![Screenshot of app with url bar(in physical device OnePlus 7)](https://user-images.githubusercontent.com/33688622/162757245-2cf34b74-bc73-4721-87d8-f8b70693e993.jpg)

**Desktop**
 - OS: Fedora 35 workstation
 - Browser: Chrome
 - Version: 100

**Smartphone (please complete the following information):**
 - Device: OnePlus 7
 - OS: Android 11
 - Browser: chrome
 - Version: Android Chrome 100.0.4896.79

**Additional context**
Additionally, the PWA works great when installing from the browser using the install app option from the website. It opens like a usual android app, without the url bar

**Comment by Pika-Pool** [comment]
Yes, the screenshot is on an emulator, but the same thing happens on my OnePlus 7 too. I'll add a screenshot for that too

**Comment by SJShip** [comment]
@Pika-Pool , A Trusted Web Activity needs the origins being opened to be validated using [Digital Asset Links](https://developers.google.com/digital-asset-links), in order to show the content in full-screen (without URL bar). Did you provide the /.well-known/assetlinks.json endpoint for your root domain and subdomain with correct assetlinks?

**Comment by Pika-Pool** [comment]
@SJShip, I just checked it, and I had names the assetlinks.json file as assetslinks.json. I've wasted so much time on this because of a small spelling mistake. Unbelievable.🤦🤦

Thanks a lot for pointing it out.
