### ISSUE TITLE
Package ID with "new" keyword throws an error

### ISSUE THREAD

**Issue by amrutha95** [GoogleChromeLabs/bubblewrap#672]
**Describe the bug**
The [issue](https://github.com/pwa-builder/PWABuilder/issues/2805) was raised on the [PWABuilder](https://pwabuilder.com) repo. We use bubblewrap to package TWAs. It seems to throw the following error every time we try to create a package, and it's due to the "new" keyword being part of the name: 

Execution failed for task ':app:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > **Package 'at.homeschooling4kids.new.twa' from AndroidManifest.xml is not a valid Java package name as 'new' is a Java keyword.**

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processReleaseResources'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:207)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:186)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at ......

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 58s

**To Reproduce**
1. bubblewrap init --manifest=https://new.homeschooling4kids.at/_nuxt/manifest.ca354309.json
2. bubblewrap build

**Expected behavior**
Package generated with no error.

**Comment by PEConn** [comment]
We should add some checks in the `bubblewrap init` flow to catch this type of thing.

You can work around it by overriding the default `Application ID` in the `bubblewrap init` flow to be something that doesn't contain "new" (or any other Java keyword).

**Comment by andreban** [comment]
This is due to the Java package naming conventions, which are used and extended by Android's application ID. From https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html:

> In some cases, the internet domain name may not be a valid package name. This can occur if the domain name contains a hyphen or other special character, if the package name begins with a digit or other character that is illegal to use as the beginning of a Java name, or if the package name contains a reserved Java keyword, such as "int". In this event, the suggested convention is to add an underscore. 

So, the recommendation would be for the package to become: `at.homeschooling4kids._new`. I don't think Bubblewrap is checking or Java keywords right now, but it should.

@amrutha95 IIRC, PWABuilder [generates the application Id](https://github.com/pwa-builder/PWABuilder/blob/main/src/script/utils/android-validation.ts#L93-L104) and passes it along o CloudAPK, which uses Bubblewrap to build. So, I'm thinking a separate fix to how PWABuilder generates application ids may be needed

**Comment by andreban** [comment]
This is the list of keywords for Java 11: https://docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-3.9

**Comment by andreban** [comment]
Fixed via #676

**Comment by amrutha95** [comment]
I'm still running into this on the cli v1.17.0. Which version should I be on?
