### ISSUE TITLE
Share Target with single quote throws an error

### ISSUE THREAD

**Issue by Jaylyn-Barbee** [GoogleChromeLabs/bubblewrap#673]
The [issue](https://github.com/pwa-builder/PWABuilder/issues/2812) was raised on the [PWABuilder](https://pwabuilder.com/) repo. We use bubblewrap to package TWAs. It seems to throw the following error every time we try to create a package, and it's due to the french characters being used in the apps manifest, specifically in the description:

> "description": "La Chorale de Cocody Philadelphie est une chorale l'Eglise Adventiste du 7ième jour de Cocody Philadelphie. Elle chante pour la gloire de DIEU et pour gagner des âmes à Christ.",

cli ERROR Command failed: gradlew.bat assembleRelease --stacktrace

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\jaylynbarbee\OneDrive - Microsoft\Desktop\bbwrap-test\app\build.gradle' line: 80

* What went wrong:
Could not compile build file 'C:\Users\jaylynbarbee\OneDrive - Microsoft\Desktop\bbwrap-test\app\build.gradle'.
> startup failed:
build file 'C:\Users\jaylynbarbee\OneDrive - Microsoft\Desktop\bbwrap-test\app\build.gradle': 80: unexpected char: '\' @ line 80, column 430.
pour gagner des �mes � Christ.\\",\\"url

**To Reproduce**
1. bubblewrap init --manifest https://adventiste-ccp.web.app/manifest.webmanifest
2. bubblewrap build

**Expected behavior**
Package generated with no error.

**Comment by andreban** [comment]
This looks like an issue while escaping the Web Share Target bit:

```gradle
            // The data for the app to support web share target.
            resValue "string", "shareTarget", '{\\"action\\":\\"https://adventiste-ccp.web.app/share-target/\\",\\"method\\":\\"POST\\",\\"enctype\\":\\"multipart/form-data\\",\\"params\\":{\\"title\\":\\"Chorale de Cocody Philadelphie\\",\\"text\\":\\"La Chorale de Cocody Philadelphie est une chorale l'Eglise Adventiste du 7ième jour de Cocody Philadelphie. Elle chante pour la gloire de DIEU et pour gagner des âmes à Christ.\\",\\"url\\":\\"https://adventiste-ccp.web.app/\\"}}'
```

**Comment by andreban** [comment]
```diff
            // The data for the app to support web share target.
-            resValue "string", "shareTarget", '{\\"action\\":\\"https://adventiste-ccp.web.app/share-target/\\",\\"method\\":\\"POST\\",\\"enctype\\":\\"multipart/form-data\\",\\"params\\":{\\"title\\":\\"Chorale de Cocody Philadelphie\\",\\"text\\":\\"La Chorale de Cocody Philadelphie est une chorale l'Eglise Adventiste du 7ième jour de Cocody Philadelphie. Elle chante pour la gloire de DIEU et pour gagner des âmes à Christ.\\",\\"url\\":\\"https://adventiste-ccp.web.app/\\"}}'
+            resValue "string", "shareTarget", '{\\"action\\":\\"https://adventiste-ccp.web.app/share-target/\\",\\"method\\":\\"POST\\",\\"enctype\\":\\"multipart/form-data\\",\\"params\\":{\\"title\\":\\"Chorale de Cocody Philadelphie\\",\\"text\\":\\"La Chorale de Cocody Philadelphie est une chorale l\\\'Eglise Adventiste du 7ième jour de Cocody Philadelphie. Elle chante pour la gloire de DIEU et pour gagner des âmes à Christ.\\",\\"url\\":\\"https://adventiste-ccp.web.app/\\"}}'```

**Comment by LouisDSC** [comment]
Thank you @andreban @Jaylyn-Barbee @dandv @zachleat @elgreg.
My package is now available.
But it doesn't work offline.
Can you help me please ?
