### ISSUE TITLE
Gradle Error

### ISSUE THREAD

**Issue by Jaylyn-Barbee** [GoogleChromeLabs/bubblewrap#686]
**Describe the bug**
We originally got this as an issue in the [PWABuilder](https://github.com/pwa-builder/PWABuilder/issues/2845) repo but I am unsure that it is a problem on our side. I was able to test this and get a similar error as the user in the CLI myself.

cli ERROR Command failed: gradlew.bat assembleRelease --stacktrace
C:\Users\jaylynbarbee\OneDrive - Microsoft\Desktop\bbwrap-test\app\src\main\java\app\web\adventiste_ccp\twa\DelegationService.java:4: error: package com.google.androidbrowserhelper.locationdelegation does not exist
import com.google.androidbrowserhelper.locationdelegation.LocationDelegationExtraCommandHandler;

**To Reproduce**
1. test bubblewrap init --manifest https://mottrees.herokuapp.com/manifest.json
2. accept default options
3. run bubblewrap build

**Expected behavior**
Build

**Screenshots**
![image](https://user-images.githubusercontent.com/51131738/165818402-9c95e4b2-3434-47ce-8417-8dc133364730.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: Latest

**Additional context**
N/A

**Comment by hooman-mirghasemi** [comment]
I have same problem. what should i do?
