### ISSUE TITLE
"Maximum length is 12 but input is 14."

### ISSUE THREAD

**Issue by nunoperalta** [GoogleChromeLabs/bubblewrap#692]
My app name is something like:

Xxxxxxx Xxxxxx (14 chars)

I can remove the space, but that still makes it 13 chars.
I can't really remove any other character, unless I make it look like there's a typo on the name.
There's also no way I can make an "abbreviated version" of the name, as it still looks odd or doesn't make sense.

PWABuilder doesn't seem to have this restriction,
and when I install the PWA directly from Chrome, the name "Xxxxxxx Xxxxxx" appears just fine on my homescreen.

So, I don't understand why does bubblewrap restrict the short name to 12 characters.

There's also no mention of that in the documentation:

https://w3c.github.io/manifest/#short_name-member

https://developer.mozilla.org/en-US/docs/Web/Manifest/short_name

Thanks

**Comment by nunoperalta** [comment]
It seems it's possible to change it after the initial setup, though. (in the configuration files)

**Comment by andreban** [comment]
You may want to check here: https://web.dev/learn/pwa/web-app-manifest/#basic-fields

This is not a hard requirement from the spect but, in most cases, Android supports up to 12 characters on screen when displaying the application on the home screen / launcher. Larger names will be truncated.
