### ISSUE TITLE
Cannot override 175408749 for com.mysite.www.twa because the app's targetSdk (31) is above the change's targetSdk threshold (30)

### ISSUE THREAD

**Issue by pimvanderheijden** [GoogleChromeLabs/bubblewrap#718]
**Describe the bug**
Running manual verification for asset links 
```
Cannot override 175408749 for com.mysite.www.twa because the app's targetSdk (31) is above the change's targetSdk threshold (30)
```

**To Reproduce**
I'm running verification for asset links like this:
```
~/Android/Sdk/platform-tools/adb shell am compat enable 175408749 com.mysite.www.twa
```

**Expected behavior**
I expect the `adb` command to not fail. 

**Additional context**
It has something to do with "compat framework changes", `RESTRICT_DOMAINS` and change id 175408749. See: https://developer.android.com/about/versions/12/reference/compat-framework-changes

Any idea how to move forward?

**Comment by PEConn** [comment]
What is it you're trying to do?

From my understanding, `adb shell am compat enable 175408749` will enable Android 12 `RESTRICT_DOMAINS` for APKs that do not target Android 12. It's so a developer can take their Android 11 app, turn on specific Android 12 features and test that it works.

Your TWA already targets Android 12, so there's no need to turn this feature on for it.

**Comment by pimvanderheijden** [comment]
Hi PEConn, I was trying to find a way to manually verify asset links. I'm looking for an alternative method because my hosting provider does not support hosting anything on `/.well-known/*`, because they reserve this to do stuff with Let's Encrypt. 
I guess "manual verification" as described [here in the docs](https://developer.android.com/training/app-links/verify-site-associations#manual-verification) is not what I was looking for and I most likely have to migrate to another hosting provider... :/

**Comment by PEConn** [comment]
Yeah, unfortunately being able to add .well-known/assetlinks.json is pretty
essential for Android apps on Android 12+ to be able to receive browsable
Intents.

Sorry there aren't any workarounds.

**Comment by pimvanderheijden** [comment]
Too bad. Thanks for explaining though!!
