### ISSUE TITLE
Reloading a fullscreen or fullscreen-sticky app breaks safe-area-inset?

### ISSUE THREAD

**Issue by thequailman** [GoogleChromeLabs/bubblewrap#722]
**Describe the bug**
When using a bubblewrap TWA on Android with display set to `fullscreen` or `fullscreen-sticky`, a pull down refresh of the page breaks the CSS variable `safe-area-inset` (commonly used to set padding and margins around device cameras), it resets the value to 0.  This causes problems with the app being covered by a camera lens or something else.  Oddly enough, pulling down the drawer fixes it?

**To Reproduce**
1.  Deploy a TWA with fullscreen or fullscreen-sticky and use the CSS safe-area-inset property
2.  Pull down refresh the app (or have the app do a hard reload)
3.  Marvel as the device camera covers your hamburger menu

**Expected behavior**
The safe-area-inset property shouldn't change

**Screenshots**
I can't take a screenshot of it broken because doing so fixes it :grin: 

**Smartphone (please complete the following information):**
 - Device: Pixel 5a

**Additional context**
This may not be a bubblewrap issue

**Comment by andreban** [comment]
Unfortunately, this is not an issue with Bubblewrap. I'd recommend filing an issue at https://bugs.chromium.org/p/chromium/issues/list.
