### ISSUE TITLE
Picture in Picture

### ISSUE THREAD

**Issue by iktumi** [GoogleChromeLabs/bubblewrap#725]
When requesting picture in picture in a PWA the video does not go PIP.

I am requesting with this code on a video element  videoElement.requestPictureInPicture();

There is something going one because the video element goes black and there seems to happen a resize of the screen like it was setting the PIP.

Besides not working in a PWA wrapped with BubbleWrapp, it also does not work on a standard PWA, but it seems more like a bug instead of intendend functionality. 
Maybe if with bubblewrap we could add android:supportsPictureInPicture="true" to the activity, and this could do the trick ?

**Comment by iktumi** [comment]
Just realized I could add to the AndroidManifest but that doesn't change a thing.

This seems more to be a bug at the PWA level for Android.

**Comment by andreban** [comment]
The TWA is used to bootstrap the application to run inside Chrome. At this point, there's not much Bubblewrap can do.  May be worth filing an issue on https://bugs.chromium.org/.
