### ISSUE TITLE
Android 13 Notifications - No prompt shown

### ISSUE THREAD

**Issue by Benny739** [GoogleChromeLabs/bubblewrap#730]
**Is your feature request related to a problem? Please describe.**
Starting with android 13 apps do not get the notification permission automatically anymore.
With the notification delegation feature the app doesn't show anything and the user never receives notifications. The user has to manually enable notifications for the app.

**Describe the solution you'd like**
Add notification permission to the manifest file and request permission on startup

**Comment by Fouad14** [comment]
Hello, 
did you find a solution ? 
I have the same problem for my TWA.

**Comment by bitcras** [comment]
Starting with android 13 apps do not get the notification permission automatically anymore.
With the notification delegation feature the app doesn't show anything and the user never receives notifications. The user has to manually enable notifications for the app.
