### ISSUE TITLE
How to track app installs campaigns in the app created through Bubblewrap

### ISSUE THREAD

**Issue by Srkahlon** [GoogleChromeLabs/bubblewrap#732]
I was able to successfully create and publish an app on the Play store very quickly thanks to Bubblewrap.
Now we want to do app install campaigns, but the only integration that I could find was of AppsFlyer. 
Is there any other way we can track the ads and the user signing up using those ads?

In the PWA of the application, we do the same using GA events and UTM. But that doesn't seem possible here.

Any help would be appreciated.

Thanks.

**Comment by andreban** [comment]
You need an android analytics that is able to track Play install, similar to AppsFlyer. I don't know if GA supports it or not, though. If it this, a similar integration should be possible, but is currently outside priorities.
