### ISSUE TITLE
Bubblewrap for iOS?

### ISSUE THREAD

**Issue by pimvanderheijden** [GoogleChromeLabs/bubblewrap#737]
I read that Apple may soon become more tolerant in terms of PWAs in the App Store. There is even talk of allowing other web-kits. This sounds very promising. Read more here: https://arstechnica.com/gadgets/2022/12/report-apple-engineers-are-working-on-third-party-app-store-support-in-ios/

If PWA on iOS becomes real, will Bubblewrap move in that direction too?

**Comment by andreban** [comment]
Bubblewrap is a tool for using Trusted Web Activity, unlikely to be extended to iOS.  You may want to check out https://www.pwabuilder.com/ for iOS.
