### ISSUE TITLE
Possible to remove the URL under the top bar?

### ISSUE THREAD

**Issue by rmittl** [GoogleChromeLabs/bubblewrap#740]
I created a PWA with bubblewrap. Under the top bar the url is showing. Is there a way to remove this? I my research I didn't find any similar issue. Thanks in advance.

![Screenshot_20221207-123658_Chrome~2](https://user-images.githubusercontent.com/4217742/208248187-5178f233-1fae-4a93-993a-05e81dab55a6.png)

**Comment by EiraGe** [comment]
The top url bar normally means your app is not verified by the browser. 
Have you set up the [Digital Asset Links](https://developer.chrome.com/docs/android/trusted-web-activity/quick-start/#creating-your-asset-link-file) on your website?

**Comment by rmittl** [comment]
Great - thanks [Digital Asset Links](https://developer.chrome.com/docs/android/trusted-web-activity/quick-start/#creating-your-asset-link-file) was the solution 👍
