### ISSUE TITLE
App not on fullscreen after social login

### ISSUE THREAD

**Issue by KaioSpa** [GoogleChromeLabs/bubblewrap#749]
I have 2 apps, both use social login (twitter and google) or email/password. 
On my first app (estudoon), I can login with social login and after the app goes back to fullscreen:
![2](https://user-images.githubusercontent.com/66890107/213711868-b96df790-6d14-477f-a306-e41eeb06d451.png)

And the other one, does not:
![1](https://user-images.githubusercontent.com/66890107/213711932-be203fc9-2270-4d40-acd5-3fa05bb22f72.png)

I want for the second app to behave like the first one.

The only difference I could find is that the first app (the one that goes back to fullscreen) is older, so, I upload it to playstore as an .apk and the other one I'm required to upload as .aab

I checked the assestlinks.json, it's correct.
I'm using laravel as backend, if it's relevant.

I hope someone can helpme.

**Comment by PEConn** [comment]
Hey, just something quick to check, are you absolutely sure that the origin that you launch, and the origin the login flow redirects to are the same? I've seen this issue a few times where you launch to `example.com`, which is verified, then redirect to `www.example.com`, which is a separate origin that is not verified.

**Comment by KaioSpa** [comment]
Just checked, i'm always using "https://www.cursosuniproon.com.br/..."
This also happens when logging in with google, just used twitter as an example

**Comment by KaioSpa** [comment]
So... It just started working? I don't know why, because I have done nothing.

But, it's working, so, i'm closing this.
