### ISSUE TITLE
Bump SDKs versions to latest android 13

### ISSUE THREAD

**Issue by khmyznikov** [GoogleChromeLabs/bubblewrap#750]
https://github.com/GoogleChromeLabs/bubblewrap/blob/1f77a46120a2dcb481dfc9c1faa9c5e4a840b8fc/packages/core/template_project/app/build.gradle#L57

sdks:
```
compileSdkVersion 33, 
targetSdkVersion 33
```

dependencies:
```implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.4.0'```

**Comment by FluorescentHallucinogen** [comment]
@andreban I would love to create a pull request for this. :wink:

**Comment by andreban** [comment]
Sounds good to me :)

**Comment by khmyznikov** [comment]
@andreban can you release new version with this?

**Comment by lukastribus** [comment]
@nmetulev on April 17th bubblewrap v1.20.0 was released with the SDK version bump.

**Comment by lad-joy** [comment]
> Google asks to renew app for android 13. Сan anyone help me with this?
PWA on my website. Earlyer i have made it with bubble wrap. i'll pay
Sory if i amwrong, i am rather new on github.

**Comment by khmyznikov** [comment]
@lad-joy you just need to take your keys and use bubblewrap again or pwabuilder.com to re-generate the package.

**Comment by lad-joy** [comment]
Может вы могли бы помочь?!
Я бы оплатил.



Отправлено с iPhone

**Comment by lad-joy** [comment]
Если можешь, помоги, пожалуйста, я отблагодарю.
Я путаюсь в настройках, не понимаю откуда скачать ключ(прошлый с моим прошлым компом перегорел).
Помоги, проведи, пожалуйста.




Отправлено с iPhone

> 21 марта 2024 г., в 16:57, Andrey Bayda ***@***.***> написал(а):
>
