### ISSUE TITLE
[help] MetaSpace exception

### ISSUE THREAD

**Issue by its-dibo** [GoogleChromeLabs/bubblewrap#751]
I just ran bubblewrap` to turn my PWA into an android app for the first time
I run this cmd in a freshly installed windows 10 machine

These are the commands I just used
```
bubblewrap init --manifest https://www.almogtama3.com/config/manifest.webmanifest
bubblewrap build
```
but I get this exception (adding `--info` or `--debug` to **`bubblewrap build`**) outputs the exact same message

![jpg](https://user-images.githubusercontent.com/57308531/214352518-0462d0df-354c-43a7-807c-c34c54ed71c6.jpg)

**Comment by andreban** [comment]
Unfortunately, I think this issue is related to the JVM. Can you check if the solution mentioned here solves it? https://github.com/GoogleChromeLabs/bubblewrap/issues/611#issuecomment-947452202
