### ISSUE TITLE
Where can I download Android SDK tools?

### ISSUE THREAD

**Issue by ghnp5** [GoogleChromeLabs/bubblewrap#752]
Hello,

In the README, at the bottom, https://github.com/googleChromeLabs/bubblewrap/blob/main/packages/cli/README.md

It says:

> Download a version of Android command line tools that is compatible with your OS from https://developer.android.com/studio#command-tools.

Unfortunately, the `#command-tools` anchor no longer exists.

There is another one, https://developer.android.com/studio#command-line-tools-only
But this only downloads the `bin` and `lib` folders.
Everything else that used to exist in the SDK folder doesn't seem to be available in this page anymore, unless I'm mistaken.

Any tips, please? I'm confused about the current procedure, as it seems things have changed.
Thank you very much!

**Comment by ghnp5** [comment]
Ok. I see that if I run `bubblewrap updateConfig`, it will ask if I want it to install JDK and SDK for me, which puts the files under my home folder.

Going to `\.bubblewrap\android_sdk\tools`, I see it only contains `bin` and `lib`.

Then I ran:

`bubblewrap build`

It asked if I accept the Terms to install Android Build Tools, which I accepted:

> January 16, 2019---------------------------------------
> Accept? (y/N): y
> [=======================================] 100% Unzipping... android-11/renderscr

--

Looks like it worked.
So, all seems to be good.

(maybe just the link in `README` might need to be updated)

**Comment by andreban** [comment]
https://developer.android.com/studio#command-line-tools-only is the right place. I haven't looked into the latest version, but it should either include everything you need or an installer via sdkmanager. I updated the docs on https://github.com/GoogleChromeLabs/bubblewrap/pull/754

**Comment by FluorescentHallucinogen** [comment]
@andreban It seems this issue can be closed. ;)

**Comment by andreban** [comment]
Thanks for the ping. Closing down.
