### ISSUE TITLE
[Discussion] Drop support for Node 12

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/bubblewrap#759]
One of the Bubblewrap, dependencies, lerna, dropped support for Node 12 and the project fails to build. We should drop support in Bubblewrap as well.

See:
https://github.com/lerna/lerna/blob/main/package.json#L15

**Comment by FluorescentHallucinogen** [comment]
@andreban I would love to create a pull request for this. :wink:

**Comment by andreban** [comment]
SGTM - Looping @PEConn in case he has any concerns around dropping Node 12.

**Comment by PEConn** [comment]
I have no concerns.
