### ISSUE TITLE
Access to webview settings: setMediaPlaybackRequiresUserGesture

### ISSUE THREAD

**Issue by patrickhuijten** [GoogleChromeLabs/bubblewrap#767]
**Is your feature request related to a problem? Please describe.**
In my team we're trying to build Android apps from PWAs for older Android devices (8.1). Everything is working great, but a problem we're running into is the inability to play sounds on these devices. A quick google search showed us this: https://stackoverflow.com/a/48543264/16287854

Can I access the webview settings in any way from Bubblewrap? I would really like to be able to modify more of the underlying settings of the webview instance.

**Describe the solution you'd like**
* Access to webview settings (i.e. `setMediaPlaybackRequiresUserGesture`) from bubblewrap CLI.

**Describe alternatives you've considered**
We do not really have any alternatives. We are building for Android 8.1 honeywell devices with barcode scanners. This barcode scanner does not register scanning as a user gesture, so the sound playback from web (mp3 sounds) is not available. Hypothetically honeywell devices might be able to register the scan button as a user gesture, but that'll likely be a long shot.

**Additional context**
We also have to support apps for Android 11, and there we don't have the problem at all, due to the underlying browser for the webview being Chrome.

The webview instance on Android 8.1 devices is 61, IIRC.

**Comment by andreban** [comment]
The WebView fallback is part of the [android-browser-helper](https://github.com/GoogleChrome/android-browser-helper/) library, and the source-code is [here](https://github.com/GoogleChrome/android-browser-helper/blob/main/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/WebViewFallbackActivity.java). Support would need to be added there first.

**Comment by patrickhuijten** [comment]
Thanks @andreban, I'll reach out to them 👍

**Comment by andreban** [comment]
Should be fixed since using android-browser-helper v2.5.0.
