### ISSUE TITLE
white space on position of navigation bar

### ISSUE THREAD

**Issue by Rafalstrus** [GoogleChromeLabs/bubblewrap#777]
**Describe the bug**
After building app with bubblewrap, and set .well-known/assetlink.json when scrolling down, I see white space the size of the navigation bar below app content. Because of this space navbar which has css position "sticky", and set to top 0 is above the view.

**To Reproduce**
1. bubblewrap init --manifest ...
in manifest.json i have except icons only
  "start_url": "/",
  "scope": ".",
  "display": "fullscreen",
  "theme_color": "#000000",
  "background_color": "#ffffff"
2. bubblewrap build (set Display mode to "fullscreen")
3. install app.
**Expected behavior**
no white space in app bottom when scrolling down.

**Screenshots**
![image](https://user-images.githubusercontent.com/76953304/229081394-88a75b1a-34ff-42dd-917a-da46aff1da12.png)

**Smartphone (please complete the following information):**
 - Device: xiaomi redmi note 7
 - OS: 10 QKQ1.190910.002
 - Browser chrome
 - Version 111.0.5563.116

**Additional context**
That problem occurs when selected is fullscreen mode and occurs only in portarait view, in landscape everything is fine.
 But on standalone display mode issue didn't occurs at all. 
In PWA installed app problem does not exist. Bottom navigation from screen has position "fixed" and bottom 0

**Comment by andreban** [comment]
Bubblewrap only generates the packaging for the app, and rendering is implemented by the browser in a Trusted Web Activity. I'd recommend filing an issue on bugs.chromium.org in this case.
