### ISSUE TITLE
Public docker image is not accessible anonymously

### ISSUE THREAD

**Issue by monsterbitar** [GoogleChromeLabs/bubblewrap#780]
**Describe the bug**
In the documentation, there is a section about how to use the public docker image to run commands in an environment that comes with all necessary requirements pre-installed. Trying to run this command results in an error about case capitalization, and once lowercased as required results in an access error. 

**To Reproduce**
1. Run "docker run --rm -ti ghcr.io/GoogleChromeLabs/bubblewrap:latest help"
2. Run "docker run --rm -ti ghcr.io/googlechromelabs/bubblewrap:latest help"

**Expected behavior**
Help text from bubblewrap executable should be displated.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser N/A
 - Version N/a

**Additional context**
You can also verify the access problem by trying to access the docker image directly via https://ghcr.io/v2/googlechromelabs/bubblewrap/manifests/latest

Other projects where accessing their images work seem to have "packages" listed in the sidebar here on github.

**Comment by andreban** [comment]
Hey @anbraten, any chance you'd be able to help on this?

**Comment by anbraten** [comment]
@andreban You / a maintainer has to change the visibility of the package I guess. It should be accessible at this page: https://github.com/orgs/GoogleChromeLabs/packages/container/bubblewrap/settings

You should be able to see sth like this there:

![image](https://user-images.githubusercontent.com/6918444/233397616-b9019776-5926-44fd-8a0c-0a24b1bb21a3.png)

![image](https://user-images.githubusercontent.com/6918444/233397707-bcc74283-d0ee-4494-832f-53201c6b06b1.png)

**Comment by andreban** [comment]
Ahh, thanks for the explanation (I'm obviously not greatly knowledgeable on Docker). Unfortunately...

![Screenshot 2023-04-20 at 15 36 34](https://user-images.githubusercontent.com/1733592/233400007-0a93e490-dac9-483c-9e6e-ce07c13995d4.png)

**Comment by andreban** [comment]
@monsterbitar should be public now. Thanks for the help, @anbraten.

**Comment by anbraten** [comment]
Awesome 🎉
