### ISSUE TITLE
ERROR "playPublish" is not a valid command!

### ISSUE THREAD

**Issue by lovkyndig** [GoogleChromeLabs/bubblewrap#786]
Screenclip of error:
<img width="457" alt="playPublish not valid command" src="https://user-images.githubusercontent.com/125480548/234495730-6cd12e52-9537-4a5e-9a6b-4c7cabcbdde5.PNG">

[`bubblewrap/cli/README.md`](https://github.com/GoogleChromeLabs/bubblewrap/tree/main/packages/cli#play) give this information about _play_ and _playPublish_:
<img width="734" alt="playPublish-command" src="https://user-images.githubusercontent.com/125480548/234496000-900aa8bb-f85b-4f24-830c-f6c957ac9fef.PNG">

## Why this error?
I am using windows and the latest version of everything.
Do I need to install `core` for this command?

## Source:
I was also reading about this command in [`#621`](https://github.com/GoogleChromeLabs/bubblewrap/commit/f5d32bb32032f97161eb6e8b6a1e3727af5d357b)

**Comment by FRSgit** [comment]
Hey! I've just created a PR resolving [this one](https://github.com/GoogleChromeLabs/bubblewrap/pull/885) - hopefully it will get merged soon.

And until it does - in my repo I'm using [pnpm patch](https://pnpm.io/cli/patch) to [uncomment needed lines by myself](https://github.com/FRSOURCE/fast-angle/blob/main/patches/%40bubblewrap__cli.patch). You can do the same on your side natively in pnpm/yarn or  if you need npm then you can try [using this package](https://www.npmjs.com/package/patch-package).
