### ISSUE TITLE
Override theme color for dark mode

### ISSUE THREAD

**Issue by GCSBOSS** [GoogleChromeLabs/bubblewrap#802]
**Is your feature request related to a problem? Please describe.**
The web manifest spec has a known limitation of lacking a way to define a _different_ theme color for when a device is in Dark mode, what causes some weird color matching between app top content and android (e.g) status bar.

**Describe the solution you'd like**
It would be awesome if bubble wrap could provide a way to override the status bar color (or theme color) when the device is in Dark mode.

On the user side, probably adding a `themeColorDark` analogous to the existing `navigationColorDark`.

I'm assuming this should be doable on the generated android code.

**Describe alternatives you've considered**
There are a few ways to supposedly working around this, I could not have any of them to work. I'll briefly list them:

- swapping between two different `<meta name="theme-color"` one for dark and one for light themes
- skip defining a theme color in manifest so the system use the background color of the root element
- somehow loading different manifest for depending on device theme

**Comment by andreban** [comment]
Hum, android-browser-helper [does support it](https://github.com/GoogleChrome/android-browser-helper/blob/62fb2cab58425de79dcfdc9cd012bd6d1fffc4d8/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/LauncherActivityMetadata.java#L52-L56), but we have never added to [TwaManifest](https://github.com/GoogleChromeLabs/bubblewrap/blob/main/packages/core/src/lib/TwaManifest.ts#L137). Can't remember if there's a reason why we didn't. To make this work, we'd need to:

- Update TwaManifest to include a `themeColorDark` (setting defaults and handling manifests that don't yet have one)
- Add the theme color to app/build.gradle on the template project, similar to [this](https://github.com/GoogleChromeLabs/bubblewrap/blob/main/packages/core/template_project/app/build.gradle#L92-L95)
- Include the information on AndroidManifest.xml, [similar to this](https://github.com/GoogleChromeLabs/bubblewrap/blob/main/packages/core/template_project/app/src/main/AndroidManifest.xml#L108-L110)

I may be forgetting something, but those should at least be the initial steps.

**Comment by GCSBOSS** [comment]
Just for the record, I was able to accomplish it with this hack:

```js
function reflectColorScheme(scheme){
    // scheme = 'light', 'dark' or 'auto'

    // Hack found in https://stackoverflow.com/a/75124760
    for(var s = 0; s < document.styleSheets.length; s++) 

        for(var i = 0; i < document.styleSheets[s].cssRules.length; i++) {
            const rule = document.styleSheets[s].cssRules[i];

            if(rule && rule.media && rule.media.mediaText.includes('prefers-color-scheme')) 

                switch(scheme) {
                    case 'light':
                        rule.media.appendMedium('original-prefers-color-scheme');
                        if(rule.media.mediaText.includes('light')) rule.media.deleteMedium('(prefers-color-scheme: light)');
                        if(rule.media.mediaText.includes('dark')) rule.media.deleteMedium('(prefers-color-scheme: dark)');
                        break;
                    case 'dark':
                        rule.media.appendMedium('(prefers-color-scheme: light)');
                        rule.media.appendMedium('(prefers-color-scheme: dark)');
                        if(rule.media.mediaText.includes('original')) rule.media.deleteMedium('original-prefers-color-scheme');
                        break;
                    case 'auto':
                        rule.media.appendMedium('(prefers-color-scheme: dark)');
                        if(rule.media.mediaText.includes('light')) rule.media.deleteMedium('(prefers-color-scheme: light)');
                        if(rule.media.mediaText.includes('original')) rule.media.deleteMedium('original-prefers-color-scheme');
                        break;
                }
        }

    const previousMetas = document.querySelectorAll('meta[name="theme-color"]');    
        
    if(scheme == 'light' || scheme == 'dark') {
        const meta = document.createElement('meta');
        meta.name = 'theme-color';
        meta.content = scheme == 'light' ? '#ffffff' : '#1f1f1f';
        document.head.appendChild(meta);
    }
    else{
        const meta = document.createElement('meta');
        meta.name = 'theme-color';
        meta.content = '#1f1f1f';
        meta.media = '(prefers-color-scheme: dark)';
        document.head.appendChild(meta);

        const m2 = document.createElement('meta');
        m2.name = 'theme-color';
        m2.content = '#ffffff';
        m2.media = '(prefers-color-scheme: light)';
        document.head.appendChild(m2);
    }

    previousMetas.forEach(n => n.remove());
}
```
