### ISSUE TITLE
"An SDK version you are using has been reported as outdated" warning in Google Play Console

### ISSUE THREAD

**Issue by david-buck** [GoogleChromeLabs/bubblewrap#810]
I am getting this message in Google Play Console for two out of three of my apps created using Bubblewrap. 

The SDK developer androidx.fragment has reported fragment:1.0.0 as outdated. Consider upgrading to a newer version.

<img width="948" alt="image" src="https://github.com/GoogleChromeLabs/bubblewrap/assets/5119820/f795c593-2589-4374-a0ba-23612626b149">

Is there something I can do, or is it a case of waiting for an update to Bubblewrap/Android Browser Helper?

Thanks,

**Comment by Bayernatoor** [comment]
Yep I am getting the same. I assume Bubblewrap needs to update the SDK they are using.

**Comment by andreban** [comment]
Hum, Bubblewrap doesn't include this library directly, so I'm guessing it's a transitive dependency from https://github.com/GoogleChrome/android-browser-helper/. Are you using the location delegation or play billing features?

**Comment by andreban** [comment]
It seems the Play Service location library includes Play Services Base, which in turn includes AndroidX Fragments. So, the solution is to bump the version on android-browser-helper so it can also be bumped in Bubblewrap.

**Comment by david-buck** [comment]
> Are you using the location delegation or play billing features?

Yes, the apps getting this warning use location delegation, the one not getting this warning does not.

Thanks

**Comment by GCSBOSS** [comment]
I'm getting this and I have no clue what location delegation even is.

**Comment by andreban** [comment]
@GCSBOSS Check your `twa-manifest.json` and the [features section](https://github.com/GoogleChromeLabs/bubblewrap/tree/main/packages/cli#features). If your web application doesn't use the Location API, you can probably disable it (and make your APK slightly smaller)

**Comment by andreban** [comment]
android-browser-helper has been updated to use a newer version of play-services-location: https://github.com/GoogleChrome/android-browser-helper/pull/437. One a new version of the library is published we can update Bubblewrap.

**Comment by andreban** [comment]
Deployed on Bubblewrap 1.21.0

**Comment by david-buck** [comment]
This may be a stilly question, so please forgive me but, how does this not require a version bump in ABH?

**Comment by andreban** [comment]
The library causing the warning is included via the `locationdelegation` part of ABH, which was updated via #819. There's no need to update the `core` library

**Comment by david-buck** [comment]
I have reinstalled `@bubblewrap/cli` to get the latest version and am still getting this error in Play Store Connect:

<img width="997" alt="image" src="https://github.com/GoogleChromeLabs/bubblewrap/assets/5119820/3332facb-879a-4b36-acbb-d658e2286e53">

`bubblewrap --version` is returning `version 1.21.0`

Do I need to reenable alphaDependencies or something?

**Comment by andreban** [comment]
Did you run `bubblewrap update` after updating to the last version and before rebuilding the APK?

**Comment by david-buck** [comment]
Yes I did

**Comment by mghatiya** [comment]
I am getting this error too and I have very little knowledge of how all these codes work. I had somehow managed to get bubblewrap setup for my app. 

Hope one of you would be able to guide what exactly I need to do in my app to get this problem fixed.

**Comment by mghatiya** [comment]
@david-buck did your issue get resolved? This thread seems to be in "closed" status. I wonder if anyone will look at it now.

**Comment by david-buck** [comment]
@mghatiya no it didn't. I'm not sure what the next move is tbh. I opened the project in Android Studio and the correct dependency versions are showing in the gradle file, so I can't be sure if it's not just a classic Play Store issue.

**Comment by andreban** [comment]
There may be another library being pulled in that Play is alerting about.

**Comment by david-buck** [comment]
This is the specific warning in Play

<img width="1002" alt="image" src="https://github.com/GoogleChromeLabs/bubblewrap/assets/5119820/632a49c8-d349-4999-8fe3-f5020091a9d1">

I did an update and build to generate the version for this screenshot.

**Comment by DoyinDimeji** [comment]
Hey @david-buck, did you manage to get this resolved? I am also on version 1.21.0 with the same warning popping up in Play console.

**Comment by david-buck** [comment]
No, I gave up. There's no obvious reason why bubblewrap is building with the wrong version.

**Comment by mghatiya** [comment]
How do we bring people's attention to it? @david-buck maybe you can reopen the thread?

**Comment by david-buck** [comment]
I found some time to dig into this a bit more and I can't work out how the fix mentioned above was meant to solve it. 

I cleared all gradle caches on my computer, cleared NPM caches, installed the latest JDK update, and reinstalled bubblewrap before looking into this. 

By running a `gradlew app:dependencies` on the output of my bubblewrap build I see that the`androidx.fragment:fragment:1.0.0` dependency is being used by:

`com.google.android.gms:play-services-base:18.1.0` which is a transitive dependency brought in by `com.google.android.gms:play-services-location:21.0.1.` and
`com.google.android.gms:play-services-basement:18.1.0` which is also a transitive dependency of `com.google.android.gms:play-services-location:21.0.1.` which was the change in ABH made [here](https://github.com/GoogleChrome/android-browser-helper/pull/437)

So my projects are using the right versions of `play-services-base` from ABH, but the dependencies are still not good.

My only hope is that the newer version of `play-services-base` (18.3.0) or `com.google.android.gms:play-services-location` (21.1.0) fixes this.

Please, @andreban , could you revisit this?

**Comment by david-buck** [comment]
In answer to this, it looks like Google's official packages are reliant on the outdated version https://mvnrepository.com/artifact/com.google.android.gms/play-services-base/18.3.0

<img width="479" alt="image" src="https://github.com/GoogleChromeLabs/bubblewrap/assets/5119820/d81b7151-d637-4b96-a91e-055659f5cef0">

I think we just have to ignore it until the deprecated version is updated in every upstream dependency.

**Comment by TrentBartlem** [comment]
Can you just add an explicit dependency on the updated version?

**Comment by VojtaAdam** [comment]
+1 - I still face this issue with a new app build with bubblewrap a week ago.
