### ISSUE TITLE
Address Bar after using external Link.

### ISSUE THREAD

**Issue by Globalrun** [GoogleChromeLabs/bubblewrap#812]
Our wrapped app runs without address bar. We have links to external sites. Does open with the address bar (like they should), but every other time, when we close the external site, the address bar opens up in our app. It works perfectly if we install die app as PWA. It's a Angular App and we open the link with nativeElement.click().

**Comment by andreban** [comment]
Hey Bruno, the address bar behaviour is implemented by the browser. The application created by Bubblewrap is not involved anymore at this point. Assuming this is Chrome, the best approach is filing a bug on https://bugs.chromium.org/p/chromium/issues/list and setting the `UI>Browser>Mobile>TrustedWebActivities` component.

**Comment by andreban** [comment]
Closing as unfeasible, as this seems like an issue in the browser, not Bubblewrap.
