### ISSUE TITLE
 App must target Android 13 (API level 33) or higher

### ISSUE THREAD

**Issue by hslee2008** [GoogleChromeLabs/bubblewrap#824]
## Google Play Store Policy status warning details

We've detected that your app is targeting an old version of Android. To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements.

From August 31, 2023, if your target API level is not within 1 year of the latest Android release, you won't be able to update your app.

To continue making updates to your app, ensure your app targets Android 13 (API level 33).

To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements.

Your highest non-compliant target API level is Android 12 (API level 31).

To ensure that you can continue to make updates to your app you must:

Update your app to target Android 13 (API level 33) or higher.
Publish a new version of your app to production. Before you do this, you can test your app using internal, closed, or open testing.

[Learn more about the requirements](https://support.google.com/googleplay/android-developer/answer/11926878)
[Learn how to update your app](https://support.google.com/googleplay/android-developer/answer/9859350)
[Learn what changes you may need to make in your app](https://developer.android.com/google/play/requirements/target-sdk)
[Read the policy announcement](https://support.google.com/googleplay/android-developer/answer/13411745)

## Related
https://github.com/GoogleChromeLabs/bubblewrap/issues/805

## Question
1. Is this related to bubblewrap?
2. How should a developer using bubblewrap fix this warning?

**Comment by ghnp5** [comment]
I'm not sure about this. I've rebuilt the app using the latest bubblewrap and it worked.

What you might be experiencing is that the Android SDK isn't up-to-date on your machine.

My trick is to go on the ".bubblewrap" folder (in your user home folder), delete the SDK and Java, and then bubblewrap will prompt to install the latest SDK and Java.
