### ISSUE TITLE
 cli ERROR unrecognised content at end of stream

### ISSUE THREAD

**Issue by YellowLorryRedLorry** [GoogleChromeLabs/bubblewrap#851]
**Describe the bug**
When running the command bubblewrap init --manifest https://<url> and answering the questions in the questionnaire bubblewrap starts the green progress bar "Generating Android Project" at 0% and exits "cli ERROR unrecognised content at end of stream"

**Desktop (please complete the following information):**
 - Windows 10
 - npm 10.6

**Comment by YellowLorryRedLorry** [comment]
pwabuilder.com created the icons for the manifest. Opening and saving the icons manually solved the issue.

**Comment by paulirwin** [comment]
I encountered this same issue with icons exported from PWA Builder. Using this [PNG file chunk inspector](https://www.nayuki.io/page/png-file-chunk-inspector), I confirmed that the files had a bad chunk at the end. Opening the files in GIMP and choosing the "File/Overwrite [filename]" menu option created files that pass chunk inspection.
