### ISSUE TITLE
Unable to use Bubblewrap Build

### ISSUE THREAD

**Issue by tropicthedev** [GoogleChromeLabs/bubblewrap#853]
**Describe the bug**
Unable to utilize bubblewrap. While using bubblewrap build I got a cli ERROR spawn EINVAL error.
**To Reproduce**
1. Install Bubblewrap
2. run the init command with my website manifest
3. enter the data to generate the project
4. run bubblewrap build at the root of the project using the included dependencies

**Expected behavior**
The CLI to build the android app without issues

**Screenshots**
![Screenshot 2024-05-29 203653](https://github.com/GoogleChromeLabs/bubblewrap/assets/93103500/b9fdcd7a-2a55-4e61-bc69-9abdb5ffa879)

**Additional context**
I installed the CLI via NPM and immediately tried to use it but failed

**Comment by conorw** [comment]
I encountered this on Windows 11 also.
I was able to workaround this by using a different version of node e.g. 16 instead of 20.13.1

**Comment by tropicthedev** [comment]
Will try this

**Comment by Andrey-Pavlov** [comment]
I have the same issue
Node v22.3.0

**Comment by aibrahim-** [comment]
This is due to a security patch in node, Bubblewrap needs to  use { shell: true } when spawning a process: https://github.com/nodejs/node/issues/52554

As a workaround, use older version of node.

**Comment by AhmedBaset** [comment]
> This is due to a security patch in node, Bubblewrap needs to use { shell: true } when spawning a process: [nodejs/node#52554](https://github.com/nodejs/node/issues/52554)

https://github.com/GoogleChromeLabs/bubblewrap/blob/2395d6aea6be141c146a1db435bc21fd06c41978/packages/core/src/lib/util.ts#L92

`shell: true` is already utilized. 🤔

**Comment by AhmedBaset** [comment]
https://github.com/GoogleChromeLabs/bubblewrap/blob/2395d6aea6be141c146a1db435bc21fd06c41978/packages/core/src/lib/util.ts#L92
> 
> ~`shell: true` is already utilized. 🤔~

It turned out to be because of this line:

https://github.com/AhmedBaset/bubblewrap/blob/2395d6aea6be141c146a1db435bc21fd06c41978/packages/core/src/lib/util.ts#L63

should be fixed by #881

**Comment by CRIMSON-CORP** [comment]
Im still getting this error, do i need to downgrade Node?

**Comment by Henza55** [comment]
I used node.js 16 and it worked for me, try downgrading your node.js to an older one.

**Comment by AhmedBaset** [comment]
> I used node.js 16 and it worked for me, try downgrading your node.js to an older one.

Node 16 is dead. It reached  EOL a long time ago.

**Comment by prhmhoseyni** [comment]
This bug only occurs on Windows.
Try again in Bash Terminal.
