### ISSUE TITLE
Digital Goods API not working?

### ISSUE THREAD

**Issue by vflam** [GoogleChromeLabs/bubblewrap#854]
Hello, I made a TWA of my PWA using bubblewrap, using these options in the twa-manifest.json

`  "features": {
    "playBilling": {
      "enabled": true
    }
  },
  "alphaDependencies": {
    "enabled": true
  },`

However, "getDigitalGoodsService" is never available, I am out of ideas. All the documentation I find is from 2022, it says there is an origin trials but it seems like the origin trials is over now, but the digital goods API just won't work. Was this scrapped and it's now impossible to use Play Billing with a bubblewrapped app? Or, is there anything that I am missing?

**Comment by Stevie-Ray** [comment]
Hi @vflam I can confirm it's working, still receiving payments on my app. The API is only available on mobile devices: chrome://inspect/#devices

**Comment by vflam** [comment]
Thank you, I managed to get it to work.

The problem was that the default browser on my phone was Brave browser and not Chrome, so the TWA would be started using Brave and it does not work in Brave.
