### ISSUE TITLE
Google Play Billing 6.01?

### ISSUE THREAD

**Issue by vflam** [GoogleChromeLabs/bubblewrap#864]
Hello,

I finally managed to have my bubblewrap generated TWA to work.

However, on Google Play Console, it says that the app needs to use Google Play Billing v6 and it seems impossible to configure that in Bubblewrap, I'm not even sure the js API's (Digital Goods and PaymentRequest) would support it.

Is there any way to make this work?

**Comment by ibrahimkarahan** [comment]
This is being worked on. We'll post an update to address compatibility with Play Billing Library v6 soon.

**Comment by vflam** [comment]
Great to hear, thanks !

**Comment by NeroRonnin123** [comment]
> This is being worked on. We'll post an update to address compatibility with Play Billing Library v6 soon. 


Do you have any start date?  my apk is valid and the API 34 issue was removed, but it does not detect the billing library in google developers

**Comment by OlegNitz** [comment]
> > This is being worked on. We'll post an update to address compatibility with Play Billing Library v6 soon.
> 
> Do you have any start date? my apk is valid and the API 34 issue was removed, but it does not detect the billing library in google play console.

The new version of Bubblewrap 1.22.0 was published 2 weeks ago, you need to rebuild your apk with it.
