### ISSUE TITLE
Bubblewrap broken?

### ISSUE THREAD

**Issue by vflam** [GoogleChromeLabs/bubblewrap#870]
I updated bubblewrap and now it generates APKs that instantly crash when the app is started, am I the only one who is getting this?

**Comment by vflam** [comment]
I am still getting the same issue with 1.22, tried generating bubblewrap apps out of other PWA's from pamp.rocks, same issue, tried through PWA Builder, same issue.

I would really appreciate if someone could at least tell me if bubblewrap works for them since version 1.21

**Comment by StefanNedelchev** [comment]
Are you sure you upload the aab file instead of the APK file? They encourage developers to use AAB files.

**Comment by vflam** [comment]
Yeah I did, but I think it is just a coincidence, they rejected my app claiming it crashes, I tested on an emulator, and it crashed too, I assumed this was the same problem.

However after testing more, I am now realizing that my bubblewrap app works on my actual phone, and that other apps also crash on this emulator, I'll close this thread as this shows bubblewrap is not at fault here.
