### ISSUE TITLE
Google Play installer check requires a minimum SDK version of 21 or higher. ( current is 19 )

### ISSUE THREAD

**Issue by harvalikjan** [GoogleChromeLabs/bubblewrap#896]
**Describe the bug**
minSdkVersion is set too low for google play to accept.

**To Reproduce**
When I upload .aab, google play console says "Play installer check requires a minimum SDK version of 21 or higher. The uploaded App Bundle has a minimum SDK version of 19. Update the minSdkVersion in your app's Android manifest." 

Please increase the value of minSdkVersion in build.gradle to at least 21, thank you.

**Comment by ibrahimkarahan** [comment]
@OlegNitz FYI

**Comment by jws1837** [comment]
I ran into this issue with pwabuilder first and tried to do it with bubblewrap, but it's the same.

**Comment by korywka** [comment]
Thanks for the pull request. It would be great to release it.

**Comment by OlegNitz** [comment]
> Thanks for the pull request. It would be great to release it.

Released v1.22.2
